namespace Tellma.Model.Common
{
    public static class Cultures
    {
        /// <summary>
        /// All UI cultures currently supported by the system.
        /// </summary>
        public static readonly string[] SupportedCultures = new string[] { "en", "ar", "zh", "am", "om" };
    }

    // TODO: Make it autogenerated in every project with the specific resources of that project
}
