	INSERT INTO dbo.ResourceClassifications ([ResourceDefinitionId], -- N'property-plant-and-equipment'
										[Name],								[IsLeaf],	[Node]) VALUES
	(N'property-plant-and-equipment',	N'Land and buildings',					0,			N'/1/'),
	(N'property-plant-and-equipment',	N'Land',								1,			N'/1/1/'),
	(N'property-plant-and-equipment',	N'Buildings',							1,			N'/1/2/'),
	(N'property-plant-and-equipment',	N'Machinery',							1,			N'/2/'),
	(N'property-plant-and-equipment',	N'Vehicles',							0,			N'/3/'),
	(N'property-plant-and-equipment',	N'Ships',								1,			N'/3/1/'),
	(N'property-plant-and-equipment',	N'Aircraft',							1,			N'/3/2/'),
	(N'property-plant-and-equipment',	N'Motor vehicles',						1,			N'/3/3/'),
	(N'property-plant-and-equipment',	N'Fixture and fittings',				1,			N'/4/'),
	(N'property-plant-and-equipment',	N'Office equipment',					1,			N'/5/'),
--	(N'property-plant-and-equipment',	N'Computer equipment',					1,			N'/6/'),
	(N'property-plant-and-equipment',	N'Communication and network equipment',	1,			N'/7/'),
	(N'property-plant-and-equipment',	N'Nework infrastructure',				1,			N'/8/'),
	(N'property-plant-and-equipment',	N'Bearer plants',						1,			N'/9/'),
	(N'property-plant-and-equipment',	N'Bearer plants',						1,			N'/10/'),
	(N'property-plant-and-equipment',	N'Tangible exploration and evaluation assets',1,	N'/11/'),
	(N'property-plant-and-equipment',	N'Mining assets',						1,			N'/12/'),
	(N'property-plant-and-equipment',	N'Oil and gas assets',					1,			N'/13/'),
	(N'property-plant-and-equipment',	N'Power generating assets',				1,			N'/14/'),
	(N'property-plant-and-equipment',	N'Leashold improvements',				1,			N'/15/'),
	(N'property-plant-and-equipment',	N'Construction in progress',			0,			N'/16/'),
	(N'property-plant-and-equipment',	N'Affordable complexes',				1,			N'/16/1/'),
	(N'property-plant-and-equipment',	N'Luxury Complexes',					1,			N'/16/2/');