CREATE TYPE [dbo].[AccountTypeList] AS TABLE (
	[Index]						INT PRIMARY KEY ,
	[ParentIndex]				INT,
	[Id]						INT NOT NULL DEFAULT 0,
	[ParentId]					INT,
	[IfrsConceptId]				INT,
	[Name]						NVARCHAR (255)	NOT NULL,
	[Name2]						NVARCHAR (255),
	[Name3]						NVARCHAR (255),
	[Description]				NVARCHAR (1024),
	[Description2]				NVARCHAR (1024),
	[Description3]				NVARCHAR (1024),
	[Code]						NVARCHAR (255)		NOT NULL UNIQUE,
	[IsAssignable]				BIT					NOT NULL DEFAULT 1,
	[CurrencyAssignment]		NCHAR (1)			DEFAULT N'A' CHECK([CurrencyAssignment] IN (N'A',N'E')),
	[AgentAssignment]			NCHAR (1)			DEFAULT N'N' CHECK([AgentAssignment] IN (N'N',N'A',N'E')),
	[AgentDefinitionId]			NVARCHAR (50),
	[ResourceAssignment]		NCHAR (1)			DEFAULT N'N' CHECK([ResourceAssignment] IN (N'N',N'A',N'E')),
	[ResourceDefinitionId]		NVARCHAR (50),
	[CenterAssignment]			NCHAR (1)			NOT NULL DEFAULT N'A' CHECK([CenterAssignment] IN (N'A',N'E')),
	[EntryTypeAssignment]		NCHAR (1)			NOT NULL DEFAULT N'N' CHECK([EntryTypeAssignment] IN (N'N',N'A',N'E')),
	[EntryTypeParentId]			INT,
	[IdentifierAssignment]		NCHAR (1)			NOT NULL DEFAULT N'N' CHECK([IdentifierAssignment] IN (N'N',N'A',N'E')),
	[IdentifierLabel]			NVARCHAR (50),
	[IdentifierLabel2]			NVARCHAR (50),
	[IdentifierLabel3]			NVARCHAR (50),
	[NotedAgentAssignment]		NCHAR (1)			NOT NULL DEFAULT N'N' CHECK([NotedAgentAssignment] IN (N'N',N'A',N'E')),
	[NotedAgentDefinitionId]	NVARCHAR (50),
	[DueDateLabel]				NVARCHAR (50),
	[DueDateLabel2]				NVARCHAR (50),
	[DueDateLabel3]				NVARCHAR (50),
	[Time1Label]				NVARCHAR (50),
	[Time1Label2]				NVARCHAR (50),
	[Time1Label3]				NVARCHAR (50),
	[Time2Label]				NVARCHAR (50),
	[Time2Label2]				NVARCHAR (50),
	[Time2Label3]				NVARCHAR (50),
	[ExternalReferenceLabel]	NVARCHAR (50),
	[ExternalReferenceLabel2]	NVARCHAR (50),
	[ExternalReferenceLabel3]	NVARCHAR (50),
	[AdditionalReferenceLabel]	NVARCHAR (50),
	[AdditionalReferenceLabel2]	NVARCHAR (50),
	[AdditionalReferenceLabel3]	NVARCHAR (50),
	[NotedAgentNameLabel]		NVARCHAR (50),
	[NotedAgentNameLabel2]		NVARCHAR (50),
	[NotedAgentNameLabel3]		NVARCHAR (50),
	[NotedAmountLabel]			NVARCHAR (50),
	[NotedAmountLabel2]			NVARCHAR (50),
	[NotedAmountLabel3]			NVARCHAR (50),
	[NotedDateLabel]			NVARCHAR (50),
	[NotedDateLabel2]			NVARCHAR (50),
	[NotedDateLabel3]			NVARCHAR (50)
);