CREATE TYPE [dbo].[ResourceList] AS TABLE (
	[Index]						INT					PRIMARY KEY,
	[Id]						INT					NOT NULL DEFAULT 0,
	[Name]						NVARCHAR (255)		NOT NULL,
	[Name2]						NVARCHAR (255),
	[Name3]						NVARCHAR (255),
	[Code]						NVARCHAR (50),
	[CurrencyId]				NCHAR (3),
	[CenterId]					INT,
	--[ImageId]					NVARCHAR (50),
	[Description]				NVARCHAR (2048),
	[Description2]				NVARCHAR (2048),
	[Description3]				NVARCHAR (2048),
	[LocationJson]				NVARCHAR(MAX),
	[LocationWkb]				VARBINARY(MAX),
	[FromDate]					DATE,
	[ToDate]					DATE,
	[Decimal1]					DECIMAL,
	[Decimal2]					DECIMAL,
	[Int1]						INT,
	[Int2]						INT,
	[Lookup1Id]					INT,
	[Lookup2Id]					INT,
	[Lookup3Id]					INT,
	[Lookup4Id]					INT,
	[Text1]						NVARCHAR (50),
	[Text2]						NVARCHAR (50), 
-- Specific to resources
	[Identifier]				NVARCHAR (10),
	[ResidualMonetaryValue]		Decimal (19,4),
	[ResidualValue]				Decimal (19,4),
	[ReorderLevel]				Decimal (19,4),
	[EconomicOrderQuantity]		Decimal (19,4),

--	[ParentId]					INT,
	[MonetaryValue]				Decimal (19,4),

	INDEX IX_ResourceList__Code ([Code])
);