CREATE TYPE [dbo].[PrintingTemplateList] AS TABLE
(
	[Index]				INT PRIMARY KEY,
	[Id]				INT NOT NULL DEFAULT 0,
	[Name]				NVARCHAR (255),
	[Name2]				NVARCHAR (255),
	[Name3]				NVARCHAR (255),
	[Code]				NVARCHAR (50),
	[Description]		NVARCHAR (1024),
	[Description2]		NVARCHAR (1024),
	[Description3]		NVARCHAR (1024),
	[Context]			NVARCHAR (MAX),
	[Usage]				NVARCHAR (50),
	[Collection]		NVARCHAR (50),
	[DefinitionId]		NVARCHAR (50),
	[ReportDefinitionId] INT,
	[SupportsPrimaryLanguage] BIT,
	[SupportsSecondaryLanguage] BIT,
	[SupportsTernaryLanguage] BIT,
	[DownloadName]		NVARCHAR (1024),
	[Body]				NVARCHAR (MAX),
	[IsDeployed]		BIT,
	[MainMenuSection]	NVARCHAR (50),
	[MainMenuIcon]		NVARCHAR (50),
	[MainMenuSortKey]	DECIMAL (9,4)
)