CREATE TYPE [dbo].[WideLineList] AS TABLE (
	[Index]						INT	,
	[DocumentIndex]				INT				NOT NULL DEFAULT 0 INDEX IX_WideLineList_DocumentIndex ([DocumentIndex]),
	PRIMARY KEY ([Index], [DocumentIndex]),
	[Id]						INT				NOT NULL DEFAULT 0,
	[DefinitionId]				INT,
	[PostingDate]				DATE,
	[TemplateLineId]			INT,
	[Multiplier]				DECIMAL (19,4),
	[Memo]						NVARCHAR (255),
	[Boolean1]					BIT,
	[Decimal1]					DECIMAL (19,4),
	[Text1]						NVARCHAR(10),
	
	[Id0]						INT				NOT NULL DEFAULT 0,
	[Direction0]				SMALLINT,
	[AccountId0]				INT,
	[RelationId0]				INT,
	[CustodianId0]				INT,
	[NotedRelationId0]			INT,
	[ResourceId0]				INT,
	[CenterId0]					INT,
	[CurrencyId0]				NCHAR (3),
	[EntryTypeId0]				INT,
	[MonetaryValue0]			DECIMAL (19,4),
	[Quantity0]					DECIMAL (19,4),
	[UnitId0]					INT,
	[Value0]					DECIMAL (19,4),		
	[Time10]					DATETIME2 (2),
	[Duration0]			DECIMAL (19,4),
	[DurationUnitId0]				INT,
	[Time20]					DATETIME2 (2),
	[ExternalReference0]		NVARCHAR (50),
	[ReferenceSourceId0]		INT,
	[InternalReference0]		NVARCHAR (50),
	[NotedAgentName0]			NVARCHAR (50),
	[NotedAmount0]				DECIMAL (19,4),
	[NotedDate0]				DATE,

	[Id1]						INT				NULL DEFAULT 0,
	[Direction1]				SMALLINT,
	[AccountId1]				INT,
	[RelationId1]				INT,
	[CustodianId1]				INT,
	[NotedRelationId1]			INT,
	[ResourceId1]				INT,
	[CenterId1]					INT,
	[CurrencyId1]				NCHAR (3),
	[EntryTypeId1]				INT,
	[MonetaryValue1]			DECIMAL (19,4),
	[Quantity1]					DECIMAL (19,4),
	[UnitId1]					INT,
	[Value1]					DECIMAL (19,4),		
	[Time11]					DATETIME2 (2),
	[Duration1]			DECIMAL (19,4),
	[DurationUnitId1]				INT,
	[Time21]					DATETIME2 (2),
	[ExternalReference1]		NVARCHAR (50),
	[ReferenceSourceId1]		INT,
	[InternalReference1]		NVARCHAR (50),
	[NotedAgentName1]			NVARCHAR (50),
	[NotedAmount1]				DECIMAL (19,4),
	[NotedDate1]				DATE,

	[Id2]						INT				NULL DEFAULT 0, -- since a wide line may be two entries only
	[Direction2]				SMALLINT,
	[AccountId2]				INT,
	[RelationId2]				INT,
	[CustodianId2]				INT,
	[NotedRelationId2]			INT,
	[ResourceId2]				INT,
	[CenterId2]					INT,
	[CurrencyId2]				NCHAR (3),
	[EntryTypeId2]				INT,
	[MonetaryValue2]			DECIMAL (19,4),
	[Quantity2]					DECIMAL (19,4),
	[UnitId2]					INT,
	[Value2]					DECIMAL (19,4),
	[Time12]					DATETIME2 (2),
	[Duration2]			DECIMAL (19,4),
	[DurationUnitId2]				INT,
	[Time22]					DATETIME2 (2),
	[ExternalReference2]		NVARCHAR (50),
	[ReferenceSourceId2]		INT,
	[InternalReference2]		NVARCHAR (50),
	[NotedAgentName2]			NVARCHAR (50),
	[NotedAmount2]				DECIMAL (19,4),
	[NotedDate2]				DATE,

	[Id3]						INT				NULL DEFAULT 0,
	[Direction3]				SMALLINT,
	[AccountId3]				INT,
	[RelationId3]				INT,
	[CustodianId3]				INT,
	[NotedRelationId3]			INT,
	[ResourceId3]				INT,
	[CenterId3]					INT,
	[CurrencyId3]				NCHAR (3),
	[EntryTypeId3]				INT,
	[MonetaryValue3]			DECIMAL (19,4),
	[Quantity3]					DECIMAL (19,4),
	[UnitId3]					INT,
	[Value3]					DECIMAL (19,4),		
	[Time13]					DATETIME2 (2),
	[Duration3]			DECIMAL (19,4),
	[DurationUnitId3]				INT,
	[Time23]					DATETIME2 (2),
	[ExternalReference3]		NVARCHAR (50),
	[ReferenceSourceId3]		INT,
	[InternalReference3]		NVARCHAR (50),
	[NotedAgentName3]			NVARCHAR (50),
	[NotedAmount3]				DECIMAL (19,4),
	[NotedDate3]				DATE,

	[Id4]						INT				NULL DEFAULT 0,
	[Direction4]				SMALLINT,
	[AccountId4]				INT,
	[RelationId4]				INT,
	[CustodianId4]				INT,
	[NotedRelationId4]			INT,
	[ResourceId4]				INT,
	[CenterId4]					INT,
	[CurrencyId4]				NCHAR (3),
	[EntryTypeId4]				INT,
	[MonetaryValue4]			DECIMAL (19,4),
	[Quantity4]					DECIMAL (19,4),
	[UnitId4]					INT,
	[Value4]					DECIMAL (19,4),		
	[Time14]					DATETIME2 (2),
	[Duration4]			DECIMAL (19,4),
	[DurationUnitId4]				INT,
	[Time24]					DATETIME2 (2),
	[ExternalReference4]		NVARCHAR (50),
	[ReferenceSourceId4]		INT,
	[InternalReference4]		NVARCHAR (50),
	[NotedAgentName4]			NVARCHAR (50),
	[NotedAmount4]				DECIMAL (19,4),
	[NotedDate4]				DATE,

	[Id5]						INT				NULL DEFAULT 0,
	[Direction5]				SMALLINT,
	[AccountId5]				INT,
	[RelationId5]				INT,
	[CustodianId5]				INT,
	[NotedRelationId5]			INT,
	[ResourceId5]				INT,
	[CenterId5]					INT,
	[CurrencyId5]				NCHAR (3),
	[EntryTypeId5]				INT,
	[MonetaryValue5]			DECIMAL (19,4),
	[Quantity5]					DECIMAL (19,4),
	[UnitId5]					INT,
	[Value5]					DECIMAL (19,4),		
	[Time15]					DATETIME2 (2),
	[Duration5]			DECIMAL (19,4),
	[DurationUnitId5]				INT,
	[Time25]					DATETIME2 (2),
	[ExternalReference5]		NVARCHAR (50),
	[ReferenceSourceId5]		INT,
	[InternalReference5]		NVARCHAR (50),
	[NotedAgentName5]			NVARCHAR (50),
	[NotedAmount5]				DECIMAL (19,4),
	[NotedDate5]				DATE,

	[Id6]						INT				NULL DEFAULT 0,
	[Direction6]				SMALLINT,
	[AccountId6]				INT,
	[RelationId6]				INT,
	[CustodianId6]				INT,
	[NotedRelationId6]			INT,
	[ResourceId6]				INT,
	[CenterId6]					INT,
	[CurrencyId6]				NCHAR (3),
	[EntryTypeId6]				INT,
	[MonetaryValue6]			DECIMAL (19,4),
	[Quantity6]					DECIMAL (19,4),
	[UnitId6]					INT,
	[Value6]					DECIMAL (19,4),		
	[Time16]					DATETIME2 (2),
	[Duration6]			DECIMAL (19,4),
	[DurationUnitId6]				INT,
	[Time26]					DATETIME2 (2),
	[ExternalReference6]		NVARCHAR (50),
	[ReferenceSourceId6]		INT,
	[InternalReference6]		NVARCHAR (50),
	[NotedAgentName6]			NVARCHAR (50),
	[NotedAmount6]				DECIMAL (19,4),
	[NotedDate6]				DATE,

	[Id7]						INT				NULL DEFAULT 0,
	[Direction7]				SMALLINT,
	[AccountId7]				INT,
	[RelationId7]				INT,
	[CustodianId7]				INT,
	[NotedRelationId7]			INT,
	[ResourceId7]				INT,
	[CenterId7]					INT,
	[CurrencyId7]				NCHAR (3),
	[EntryTypeId7]				INT,
	[MonetaryValue7]			DECIMAL (19,4),
	[Quantity7]					DECIMAL (19,4),
	[UnitId7]					INT,
	[Value7]					DECIMAL (19,4),		
	[Time17]					DATETIME2 (2),
	[Duration7]			DECIMAL (19,4),
	[DurationUnitId7]				INT,
	[Time27]					DATETIME2 (2),
	[ExternalReference7]		NVARCHAR (50),
	[ReferenceSourceId7]		INT,
	[InternalReference7]		NVARCHAR (50),
	[NotedAgentName7]			NVARCHAR (50),
	[NotedAmount7]				DECIMAL (19,4),
	[NotedDate7]				DATE,

	[Id8]						INT				NULL DEFAULT 0,
	[Direction8]				SMALLINT,
	[AccountId8]				INT,
	[RelationId8]				INT,
	[CustodianId8]				INT,
	[NotedRelationId8]			INT,
	[ResourceId8]				INT,
	[CenterId8]					INT,
	[CurrencyId8]				NCHAR (3),
	[EntryTypeId8]				INT,
	[MonetaryValue8]			DECIMAL (19,4),
	[Quantity8]					DECIMAL (19,4),
	[UnitId8]					INT,
	[Value8]					DECIMAL (19,4),		
	[Time18]					DATETIME2 (2),
	[Duration8]			DECIMAL (19,4),
	[DurationUnitId8]				INT,
	[Time28]					DATETIME2 (2),
	[ExternalReference8]		NVARCHAR (50),
	[ReferenceSourceId8]		INT,
	[InternalReference8]		NVARCHAR (50),
	[NotedAgentName8]			NVARCHAR (50),
	[NotedAmount8]				DECIMAL (19,4),
	[NotedDate8]				DATE,

	[Id9]						INT				NULL DEFAULT 0,
	[Direction9]				SMALLINT,
	[AccountId9]				INT,
	[RelationId9]				INT,
	[CustodianId9]				INT,
	[NotedRelationId9]			INT,
	[ResourceId9]				INT,
	[CenterId9]					INT,
	[CurrencyId9]				NCHAR (3),
	[EntryTypeId9]				INT,
	[MonetaryValue9]			DECIMAL (19,4),
	[Quantity9]					DECIMAL (19,4),
	[UnitId9]					INT,
	[Value9]					DECIMAL (19,4),		
	[Time19]					DATETIME2 (2),
	[Duration9]			DECIMAL (19,4),
	[DurationUnitId9]				INT,
	[Time29]					DATETIME2 (2),
	[ExternalReference9]		NVARCHAR (50),
	[ReferenceSourceId9]		INT,
	[InternalReference9]		NVARCHAR (50),
	[NotedAgentName9]			NVARCHAR (50),
	[NotedAmount9]				DECIMAL (19,4),
	[NotedDate9]				DATE,

	[Id10]						INT				NULL DEFAULT 0,
	[Direction10]				SMALLINT,
	[AccountId10]				INT,
	[RelationId10]				INT,
	[CustodianId10]				INT,
	[NotedRelationId10]			INT,
	[ResourceId10]				INT,
	[CenterId10]				INT,
	[CurrencyId10]				NCHAR (3),
	[EntryTypeId10]				INT,
	[MonetaryValue10]			DECIMAL (19,4),
	[Quantity10]				DECIMAL (19,4),
	[UnitId10]					INT,
	[Value10]					DECIMAL (19,4),		
	[Time110]					DATETIME2 (2),
	[Duration10]			DECIMAL (19,4),
	[DurationUnitId10]				INT,
	[Time210]					DATETIME2 (2),
	[ExternalReference10]		NVARCHAR (50),
	[ReferenceSourceId10]		INT,
	[InternalReference10]		NVARCHAR (50),
	[NotedAgentName10]			NVARCHAR (50),
	[NotedAmount10]				DECIMAL (19,4),
	[NotedDate10]				DATE,

	[Id11]						INT				NULL DEFAULT 0,
	[Direction11]				SMALLINT,
	[AccountId11]				INT,
	[RelationId11]				INT,
	[CustodianId11]				INT,
	[NotedRelationId11]			INT,
	[ResourceId11]				INT,
	[CenterId11]				INT,
	[CurrencyId11]				NCHAR (3),
	[EntryTypeId11]				INT,
	[MonetaryValue11]			DECIMAL (19,4),
	[Quantity11]				DECIMAL (19,4),
	[UnitId11]					INT,
	[Value11]					DECIMAL (19,4),		
	[Time111]					DATETIME2 (2),
	[Duration11]			DECIMAL (19,4),
	[DurationUnitId11]				INT,
	[Time211]					DATETIME2 (2),
	[ExternalReference11]		NVARCHAR (50),
	[ReferenceSourceId11]		INT,
	[InternalReference11]		NVARCHAR (50),
	[NotedAgentName11]			NVARCHAR (50),
	[NotedAmount11]				DECIMAL (19,4),
	[NotedDate11]				DATE,

	[Id12]						INT				NULL DEFAULT 0,
	[Direction12]				SMALLINT,
	[AccountId12]				INT,
	[RelationId12]				INT,
	[CustodianId12]				INT,
	[NotedRelationId12]			INT,
	[ResourceId12]				INT,
	[CenterId12]				INT,
	[CurrencyId12]				NCHAR (3),
	[EntryTypeId12]				INT,
	[MonetaryValue12]			DECIMAL (19,4),
	[Quantity12]				DECIMAL (19,4),
	[UnitId12]					INT,
	[Value12]					DECIMAL (19,4),		
	[Time112]					DATETIME2 (2),
	[Duration12]			DECIMAL (19,4),
	[DurationUnitId12]				INT,
	[Time212]					DATETIME2 (2),
	[ExternalReference12]		NVARCHAR (50),
	[ReferenceSourceId12]		INT,
	[InternalReference12]		NVARCHAR (50),
	[NotedAgentName12]			NVARCHAR (50),
	[NotedAmount12]				DECIMAL (19,4),
	[NotedDate12]				DATE,

	[Id13]						INT				NULL DEFAULT 0,
	[Direction13]				SMALLINT,
	[AccountId13]				INT,
	[RelationId13]				INT,
	[CustodianId13]				INT,
	[NotedRelationId13]			INT,
	[ResourceId13]				INT,
	[CenterId13]				INT,
	[CurrencyId13]				NCHAR (3),
	[EntryTypeId13]				INT,
	[MonetaryValue13]			DECIMAL (19,4),
	[Quantity13]				DECIMAL (19,4),
	[UnitId13]					INT,
	[Value13]					DECIMAL (19,4),		
	[Time113]					DATETIME2 (2),
	[Duration13]			DECIMAL (19,4),
	[DurationUnitId13]				INT,
	[Time213]					DATETIME2 (2),
	[ExternalReference13]		NVARCHAR (50),
	[ReferenceSourceId13]		INT,
	[InternalReference13]		NVARCHAR (50),
	[NotedAgentName13]			NVARCHAR (50),
	[NotedAmount13]				DECIMAL (19,4),
	[NotedDate13]				DATE,

	[Id14]						INT				NULL DEFAULT 0,
	[Direction14]				SMALLINT,
	[AccountId14]				INT,
	[RelationId14]				INT,
	[CustodianId14]				INT,
	[NotedRelationId14]			INT,
	[ResourceId14]				INT,
	[CenterId14]				INT,
	[CurrencyId14]				NCHAR (3),
	[EntryTypeId14]				INT,
	[MonetaryValue14]			DECIMAL (19,4),
	[Quantity14]				DECIMAL (19,4),
	[UnitId14]					INT,
	[Value14]					DECIMAL (19,4),		
	[Time114]					DATETIME2 (2),
	[Time214]					DATETIME2 (2),
	[ExternalReference14]		NVARCHAR (50),
	[ReferenceSourceId14]		INT,
	[InternalReference14]		NVARCHAR (50),
	[NotedAgentName14]			NVARCHAR (50),
	[NotedAmount14]				DECIMAL (19,4),
	[NotedDate14]				DATE,

	[Id15]						INT				NULL DEFAULT 0,
	[Direction15]				SMALLINT,
	[AccountId15]				INT,
	[RelationId15]				INT,
	[CustodianId15]				INT,
	[NotedRelationId15]			INT,
	[ResourceId15]				INT,
	[CenterId15]				INT,
	[CurrencyId15]				NCHAR (3),
	[EntryTypeId15]				INT,
	[MonetaryValue15]			DECIMAL (19,4),
	[Quantity15]				DECIMAL (19,4),
	[UnitId15]					INT,
	[Value15]					DECIMAL (19,4),		
	[Time115]					DATETIME2 (2),
	[Duration14]			DECIMAL (19,4),
	[DurationUnitId14]				INT,
	[Duration15]			DECIMAL (19,4),
	[DurationUnitId15]				INT,
	[Time215]					DATETIME2 (2),
	[ExternalReference15]		NVARCHAR (50),
	[ReferenceSourceId15]		INT,
	[InternalReference15]		NVARCHAR (50),
	[NotedAgentName15]			NVARCHAR (50),
	[NotedAmount15]				DECIMAL (19,4),
	[NotedDate15]				DATE
);