CREATE TYPE [dbo].[AgentDefinitionList] AS TABLE (
	[Index]								INT				PRIMARY KEY,
	[Id]								INT				NOT NULL DEFAULT 0,
	[Code]								NVARCHAR(255),
	[TitleSingular]						NVARCHAR (255),
	[TitleSingular2]					NVARCHAR (255),
	[TitleSingular3]					NVARCHAR (255),
	[TitlePlural]						NVARCHAR (255),
	[TitlePlural2]						NVARCHAR (255),
	[TitlePlural3]						NVARCHAR (255),
	-----Contract properties common with resources
	[CurrencyVisibility]				NVARCHAR (50),
	[CenterVisibility]					NVARCHAR (50),
	[ImageVisibility]					NVARCHAR (50),
	[DescriptionVisibility]				NVARCHAR (50),
	[LocationVisibility]				NVARCHAR (50),

	[FromDateLabel]						NVARCHAR (50),
	[FromDateLabel2]					NVARCHAR (50),
	[FromDateLabel3]					NVARCHAR (50),		
	[FromDateVisibility]				NVARCHAR (50),
	[ToDateLabel]						NVARCHAR (50),
	[ToDateLabel2]						NVARCHAR (50),
	[ToDateLabel3]						NVARCHAR (50),
	[ToDateVisibility]					NVARCHAR (50),

	[DateOfBirthVisibility]				NVARCHAR (50),
	[ContactEmailVisibility]			NVARCHAR (50),
	[ContactMobileVisibility]			NVARCHAR (50),
	[ContactAddressVisibility]			NVARCHAR (50),

	[Date1Label]						NVARCHAR (50),
	[Date1Label2]						NVARCHAR (50),
	[Date1Label3]						NVARCHAR (50),		
	[Date1Visibility]					NVARCHAR (50),

	[Date2Label]						NVARCHAR (50),
	[Date2Label2]						NVARCHAR (50),
	[Date2Label3]						NVARCHAR (50),		
	[Date2Visibility]					NVARCHAR (50),

	[Date3Label]						NVARCHAR (50),
	[Date3Label2]						NVARCHAR (50),
	[Date3Label3]						NVARCHAR (50),		
	[Date3Visibility]					NVARCHAR (50),

	[Date4Label]						NVARCHAR (50),
	[Date4Label2]						NVARCHAR (50),
	[Date4Label3]						NVARCHAR (50),		
	[Date4Visibility]					NVARCHAR (50),

	[Decimal1Label]						NVARCHAR (50),
	[Decimal1Label2]					NVARCHAR (50),
	[Decimal1Label3]					NVARCHAR (50),		
	[Decimal1Visibility]				NVARCHAR (50),

	[Decimal2Label]						NVARCHAR (50),
	[Decimal2Label2]					NVARCHAR (50),
	[Decimal2Label3]					NVARCHAR (50),		
	[Decimal2Visibility]				NVARCHAR (50),

	[Int1Label]							NVARCHAR (50),
	[Int1Label2]						NVARCHAR (50),
	[Int1Label3]						NVARCHAR (50),		
	[Int1Visibility]					NVARCHAR (50),

	[Int2Label]							NVARCHAR (50),
	[Int2Label2]						NVARCHAR (50),
	[Int2Label3]						NVARCHAR (50),		
	[Int2Visibility]					NVARCHAR (50),

	[Lookup1Label]						NVARCHAR (50),
	[Lookup1Label2]						NVARCHAR (50),
	[Lookup1Label3]						NVARCHAR (50),
	[Lookup1Visibility]					NVARCHAR (50),
	[Lookup1DefinitionId]				INT,
	[Lookup2Label]						NVARCHAR (50),
	[Lookup2Label2]						NVARCHAR (50),
	[Lookup2Label3]						NVARCHAR (50),
	[Lookup2Visibility]					NVARCHAR (50),
	[Lookup2DefinitionId]				INT,
	[Lookup3Label]						NVARCHAR (50),
	[Lookup3Label2]						NVARCHAR (50),
	[Lookup3Label3]						NVARCHAR (50),
	[Lookup3Visibility]					NVARCHAR (50),
	[Lookup3DefinitionId]				INT,
	[Lookup4Label]						NVARCHAR (50),
	[Lookup4Label2]						NVARCHAR (50),
	[Lookup4Label3]						NVARCHAR (50),
	[Lookup4Visibility]					NVARCHAR (50),
	[Lookup4DefinitionId]				INT,
	[Lookup5Label]						NVARCHAR (50),
	[Lookup5Label2]						NVARCHAR (50),
	[Lookup5Label3]						NVARCHAR (50),
	[Lookup5Visibility]					NVARCHAR (50),
	[Lookup5DefinitionId]				INT,
	[Lookup6Label]						NVARCHAR (50),
	[Lookup6Label2]						NVARCHAR (50),
	[Lookup6Label3]						NVARCHAR (50),
	[Lookup6Visibility]					NVARCHAR (50),
	[Lookup6DefinitionId]				INT,
	[Lookup7Label]						NVARCHAR (50),
	[Lookup7Label2]						NVARCHAR (50),
	[Lookup7Label3]						NVARCHAR (50),
	[Lookup7Visibility]					NVARCHAR (50),
	[Lookup7DefinitionId]				INT,
	[Lookup8Label]						NVARCHAR (50),
	[Lookup8Label2]						NVARCHAR (50),
	[Lookup8Label3]						NVARCHAR (50),
	[Lookup8Visibility]					NVARCHAR (50),
	[Lookup8DefinitionId]				INT,

	[Text1Label]						NVARCHAR (50),
	[Text1Label2]						NVARCHAR (50),
	[Text1Label3]						NVARCHAR (50),		
	[Text1Visibility]					NVARCHAR (50),

	[Text2Label]						NVARCHAR (50),
	[Text2Label2]						NVARCHAR (50),
	[Text2Label3]						NVARCHAR (50),		
	[Text2Visibility]					NVARCHAR (50),

	[Text3Label]						NVARCHAR (50),
	[Text3Label2]						NVARCHAR (50),
	[Text3Label3]						NVARCHAR (50),		
	[Text3Visibility]					NVARCHAR (50),

	[Text4Label]						NVARCHAR (50),
	[Text4Label2]						NVARCHAR (50),
	[Text4Label3]						NVARCHAR (50),		
	[Text4Visibility]					NVARCHAR (50),
	
	[PreprocessScript]					NVARCHAR (MAX),
	[ValidateScript]					NVARCHAR (MAX),
	-----Properties applicable to contracts only
	[Agent1Label]						NVARCHAR (50),
	[Agent1Label2]						NVARCHAR (50),
	[Agent1Label3]						NVARCHAR (50),
	[Agent1Visibility]					NVARCHAR (50),
	[Agent1DefinitionIndex]				INT,
	[Agent1DefinitionId]				INT,

	[Agent2Label]						NVARCHAR (50),
	[Agent2Label2]						NVARCHAR (50),
	[Agent2Label3]						NVARCHAR (50),
	[Agent2Visibility]					NVARCHAR (50),
	[Agent2DefinitionIndex]				INT,
	[Agent2DefinitionId]				INT,

	[TaxIdentificationNumberVisibility] NVARCHAR (50),

	[BankAccountNumberVisibility]		NVARCHAR (50),
	[ExternalReferenceVisibility]		NVARCHAR (50),
	[ExternalReferenceLabel]			NVARCHAR (50),
	[ExternalReferenceLabel2]			NVARCHAR (50),
	[ExternalReferenceLabel3]			NVARCHAR (50),

	[UserCardinality]					NVARCHAR (50),	
	[HasAttachments]					BIT,
	[AttachmentsCategoryDefinitionId]	INT,

	[MainMenuIcon]						NVARCHAR (50),
	[MainMenuSection]					NVARCHAR (50),
	[MainMenuSortKey]					DECIMAL (9,4)
);