using System;

namespace Tellma.Controllers.Templating
{
    public static class AmountInWordsEn
    {
        private static readonly string[] Units = { "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen" };
        private static readonly string[] Tens = { "", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety" };

        /// <summary>
        /// Converts a decimal amounts to words in the English language. Optionally adds a currency postfix.
        /// </summary>
        public static string ConvertAmount(decimal amount, string currencyIso = null, int? decimals = null)
        {
            // Get the number of decimal places depending on the currency
            decimals ??= AmountInWordsCommon.Decimals(currencyIso); // Some currencies do 2 decimal places, some 3, some 0
            int fractionMultiplier = decimals switch
            {
                0 => 1,
                2 => 100,
                3 => 1000,
                _ => throw new InvalidOperationException($"[Bug] Unhandled decimal {decimals}")
            };

            // Remember if it's negative
            bool isNegative = amount < 0;
            amount = Math.Abs(amount);

            // disect the number into the whole part and the decimal part
            long wholePart = (long)amount;
            long fractionPart = fractionMultiplier == 1 ? 0 : (long)Math.Round((amount - wholePart) * fractionMultiplier);

            // Get the names of the currency and its fractional unit (e.g. dollars and cents)
            string currency = CurrencyName(currencyIso, wholePart == 1 ? Form.Singular : Form.Plural);
            string fractionalUnit = FractionalUnit(currencyIso, fractionPart == 1 ? Form.Singular : Form.Plural);

            string result;
            if (fractionPart == 0)
            {
                if (currency != "")
                {
                    currency += " "; // 5 dollars only
                }

                result = ConvertInner(wholePart) + $" {currency}only";
            }
            else
            {
                if (currency == "")
                {
                    fractionalUnit = "";
                    currency = "point"; // 3 point 5 only
                }
                else if (fractionalUnit == "")
                {
                    currency += " point"; // 3 dollars point 5 only
                }
                else
                {
                    fractionalUnit += " "; // 3 dollars 5 cents only
                }

                result = ConvertInner(wholePart) + $" {currency} " + ConvertInner(fractionPart) + $" {fractionalUnit}only";
            }

            if (isNegative)
            {
                result = "negative " + result;
            }

            // Capitalize
            if (result.Length > 0)
            {
                result = char.ToUpper(result[0]) + result[1..];
            }

            // Return
            return result;
        }

        private static string ConvertInner(long n)
        {
            if (n < 20L)
            {
                return Units[n];
            }
            else if (n < 100L)
            {
                return Tens[n / 10L] + ((n % 10L > 0) ? " " + ConvertInner(n % 10L) : "");
            }
            else if (n < 1000L)
            {
                return Units[n / 100L] + " hundred" + ((n % 100L > 0) ? " and " + ConvertInner(n % 100L) : "");
            }
            else if (n < 1000000L)
            {
                return ConvertInner(n / 1000) + " thousand" + ((n % 1000L > 0) ? " " + ConvertInner(n % 1000L) : "");
            }
            else if (n < 1000000000L)
            {
                return ConvertInner(n / 1000000L) + " million" + ((n % 1000000L > 0) ? " " + ConvertInner(n % 1000000L) : "");
            }
            else if (n < 1000000000000L)
            {
                return ConvertInner(n / 1000000000L) + " billion" + ((n % 1000000000L > 0) ? " " + ConvertInner(n % 1000000000L) : "");
            }
            else if (n < 1000000000000000L)
            {
                return ConvertInner(n / 1000000000000L) + " trillion" + ((n % 1000000000000L > 0) ? " " + ConvertInner(n % 1000000000000L) : "");
            }
            else if (n <= long.MaxValue)
            {
                return ConvertInner(n / 1000000000000000L) + " quadrillion" + ((n % 1000000000000000L > 0) ? " " + ConvertInner(n % 1000000000000000L) : "");
            }
            else
            {
                throw new InvalidOperationException($"Conversion to words can only handle amounts less than or equal {long.MaxValue:N2}");
            }
        }

        private static string CurrencyName(string currencyIso, Form form)
        {
            if (form == Form.Singular)
            {
                return currencyIso switch
                {
                    "RUB" => "ruble",
                    "AFN" => "afghani",
                    "EUR" => "euro",
                    "ALL" => "lek",
                    "GBP" => "pound",
                    "GGP" => "pound",
                    "DZD" => "dinar",
                    "AOA" => "kwanza",
                    "XCD" => "dollar",
                    "ARS" => "peso",
                    "AMD" => "dram",
                    "AWG" => "florin",
                    "SHP" => "pound",
                    "AUD" => "dollar",
                    "AZN" => "manat",
                    "BSD" => "dollar",
                    "BHD" => "dinar",
                    "BDT" => "taka",
                    "BBD" => "dollar",
                    "BYN" => "ruble",
                    "BZD" => "dollar",
                    "XOF" => "franc",
                    "BMD" => "dollar",
                    "BTN" => "ngultrum",
                    "INR" => "rupee",
                    "BOB" => "boliviano",
                    "USD" => "dollar",
                    "BAM" => "mark",
                    "BWP" => "pula",
                    "BRL" => "real",
                    "BND" => "dollar",
                    "SGD" => "dollar",
                    "BGN" => "lev",
                    "BIF" => "franc",
                    "KHR" => "riel",
                    "XAF" => "franc",
                    "CAD" => "dollar",
                    "CVE" => "escudo",
                    "KYD" => "dollar",
                    "CLP" => "peso",
                    "CNY" => "yuan",
                    "COP" => "peso",
                    "KMF" => "franc",
                    "CDF" => "franc",
                    "CKD" => "dollar",
                    "NZD" => "dollar",
                    "CRC" => "colón",
                    "HRK" => "kuna",
                    "CUP" => "peso",
                    "CUC" => "peso",
                    "ANG" => "guilder",
                    "CZK" => "koruna",
                    "DKK" => "krone",
                    "DJF" => "franc",
                    "DOP" => "peso",
                    "EGP" => "pound",
                    "ERN" => "nakfa",
                    "SZL" => "lilangeni",
                    "ZAR" => "rand",
                    "ETB" => "birr",
                    "FKP" => "pound",
                    "FOK" => "króna",
                    "FJD" => "dollar",
                    "XPF" => "franc",
                    "GMD" => "dalasi",
                    "GEL" => "lari",
                    "GHS" => "cedi",
                    "GIP" => "pound",
                    "GTQ" => "quetzal",
                    "GNF" => "franc",
                    "GYD" => "dollar",
                    "HTG" => "gourde",
                    "HNL" => "lempira",
                    "HKD" => "dollar",
                    "HUF" => "forint",
                    "ISK" => "króna",
                    "IDR" => "rupiah",
                    "IRR" => "rial",
                    "IQD" => "dinar",
                    "IMP" => "pound",
                    "ILS" => "shekel",
                    "JMD" => "dollar",
                    "JPY" => "yen",
                    "JEP" => "pound",
                    "JOD" => "dinar",
                    "KZT" => "tenge",
                    "KES" => "shilling",
                    "KID" => "dollar",
                    "KPW" => "won",
                    "KRW" => "won",
                    "KWD" => "dinar",
                    "KGS" => "som",
                    "LAK" => "kip",
                    "LBP" => "pound",
                    "LSL" => "loti",
                    "LRD" => "dollar",
                    "LYD" => "dinar",
                    "CHF" => "franc",
                    "MOP" => "pataca",
                    "MGA" => "ariary",
                    "MWK" => "kwacha",
                    "MYR" => "ringgit",
                    "MVR" => "rufiyaa",
                    "MRU" => "ouguiya",
                    "MUR" => "rupee",
                    "MXN" => "peso",
                    "MDL" => "leu",
                    "MNT" => "tögrög",
                    "MAD" => "dirham",
                    "MZN" => "metical",
                    "MMK" => "kyat",
                    "NAD" => "dollar",
                    "NPR" => "rupee",
                    "NIO" => "córdoba",
                    "NGN" => "naira",
                    "MKD" => "denar",
                    "TRY" => "lira",
                    "NOK" => "krone",
                    "OMR" => "rial",
                    "PKR" => "rupee",
                    "PAB" => "balboa",
                    "PGK" => "kina",
                    "PYG" => "guaraní",
                    "PEN" => "sol",
                    "PHP" => "peso",
                    "PND" => "dollar",
                    "PLN" => "złoty",
                    "QAR" => "riyal",
                    "RON" => "leu",
                    "RWF" => "franc",
                    "WST" => "tālā",
                    "STN" => "dobra",
                    "SAR" => "riyal",
                    "RSD" => "dinar",
                    "SCR" => "rupee",
                    "SLL" => "leone",
                    "SBD" => "dollar",
                    "SOS" => "shilling",
                    "SLS" => "shilling",
                    "SSP" => "pound",
                    "LKR" => "rupee",
                    "SDG" => "pound",
                    "SRD" => "dollar",
                    "SEK" => "krona",
                    "SYP" => "pound",
                    "TWD" => "dollar",
                    "TJS" => "somoni",
                    "TZS" => "shilling",
                    "THB" => "baht",
                    "TOP" => "paʻanga",
                    "PRB" => "ruble",
                    "TTD" => "dollar",
                    "TND" => "dinar",
                    "TMT" => "manat",
                    "TVD" => "dollar",
                    "UGX" => "shilling",
                    "UAH" => "hryvnia",
                    "AED" => "dirham",
                    "UYU" => "peso",
                    "UZS" => "soʻm",
                    "VUV" => "vatu",
                    "VES" => "bolívar",
                    "VND" => "đồng",
                    "YER" => "rial",
                    "ZMW" => "kwacha",
                    _ => "",
                };
            }
            else
            {
                return currencyIso switch
                {
                    "RUB" => "ruble",
                    "AFN" => "afghani",
                    "EUR" => "euros",
                    "ALL" => "lek",
                    "GBP" => "pounds",
                    "GGP" => "pounds",
                    "DZD" => "dinar",
                    "AOA" => "kwanza",
                    "XCD" => "dollars",
                    "ARS" => "peso",
                    "AMD" => "dram",
                    "AWG" => "florin",
                    "SHP" => "pounds",
                    "AUD" => "dollars",
                    "AZN" => "manat",
                    "BSD" => "dollars",
                    "BHD" => "dinar",
                    "BDT" => "taka",
                    "BBD" => "dollars",
                    "BYN" => "ruble",
                    "BZD" => "dollars",
                    "XOF" => "franc",
                    "BMD" => "dollars",
                    "BTN" => "ngultrum",
                    "INR" => "rupee",
                    "BOB" => "boliviano",
                    "USD" => "dollars",
                    "BAM" => "mark",
                    "BWP" => "pula",
                    "BRL" => "real",
                    "BND" => "dollars",
                    "SGD" => "dollars",
                    "BGN" => "lev",
                    "BIF" => "franc",
                    "KHR" => "riel",
                    "XAF" => "franc",
                    "CAD" => "dollars",
                    "CVE" => "escudo",
                    "KYD" => "dollars",
                    "CLP" => "peso",
                    "CNY" => "yuan",
                    "COP" => "peso",
                    "KMF" => "franc",
                    "CDF" => "franc",
                    "CKD" => "dollars",
                    "NZD" => "dollars",
                    "CRC" => "colón",
                    "HRK" => "kuna",
                    "CUP" => "peso",
                    "CUC" => "peso",
                    "ANG" => "guilder",
                    "CZK" => "koruna",
                    "DKK" => "krone",
                    "DJF" => "franc",
                    "DOP" => "peso",
                    "EGP" => "pounds",
                    "ERN" => "nakfa",
                    "SZL" => "lilangeni",
                    "ZAR" => "rand",
                    "ETB" => "birr",
                    "FKP" => "pounds",
                    "FOK" => "króna",
                    "FJD" => "dollars",
                    "XPF" => "franc",
                    "GMD" => "dalasi",
                    "GEL" => "lari",
                    "GHS" => "cedi",
                    "GIP" => "pounds",
                    "GTQ" => "quetzal",
                    "GNF" => "franc",
                    "GYD" => "dollars",
                    "HTG" => "gourde",
                    "HNL" => "lempira",
                    "HKD" => "dollars",
                    "HUF" => "forint",
                    "ISK" => "króna",
                    "IDR" => "rupiah",
                    "IRR" => "rial",
                    "IQD" => "dinar",
                    "IMP" => "pounds",
                    "ILS" => "shekel",
                    "JMD" => "dollars",
                    "JPY" => "yen",
                    "JEP" => "pounds",
                    "JOD" => "dinar",
                    "KZT" => "tenge",
                    "KES" => "shilling",
                    "KID" => "dollars",
                    "KPW" => "won",
                    "KRW" => "won",
                    "KWD" => "dinar",
                    "KGS" => "som",
                    "LAK" => "kip",
                    "LBP" => "pounds",
                    "LSL" => "loti",
                    "LRD" => "dollars",
                    "LYD" => "dinar",
                    "CHF" => "franc",
                    "MOP" => "pataca",
                    "MGA" => "ariary",
                    "MWK" => "kwacha",
                    "MYR" => "ringgit",
                    "MVR" => "rufiyaa",
                    "MRU" => "ouguiya",
                    "MUR" => "rupee",
                    "MXN" => "peso",
                    "MDL" => "leu",
                    "MNT" => "tögrög",
                    "MAD" => "dirham",
                    "MZN" => "metical",
                    "MMK" => "kyat",
                    "NAD" => "dollars",
                    "NPR" => "rupee",
                    "NIO" => "córdoba",
                    "NGN" => "naira",
                    "MKD" => "denar",
                    "TRY" => "lira",
                    "NOK" => "krone",
                    "OMR" => "rial",
                    "PKR" => "rupee",
                    "PAB" => "balboa",
                    "PGK" => "kina",
                    "PYG" => "guaraní",
                    "PEN" => "sol",
                    "PHP" => "peso",
                    "PND" => "dollars",
                    "PLN" => "złoty",
                    "QAR" => "riyal",
                    "RON" => "leu",
                    "RWF" => "franc",
                    "WST" => "tālā",
                    "STN" => "dobra",
                    "SAR" => "riyal",
                    "RSD" => "dinar",
                    "SCR" => "rupee",
                    "SLL" => "leone",
                    "SBD" => "dollars",
                    "SOS" => "shilling",
                    "SLS" => "shilling",
                    "SSP" => "pounds",
                    "LKR" => "rupee",
                    "SDG" => "pounds",
                    "SRD" => "dollars",
                    "SEK" => "krona",
                    "SYP" => "pounds",
                    "TWD" => "dollars",
                    "TJS" => "somoni",
                    "TZS" => "shilling",
                    "THB" => "baht",
                    "TOP" => "paʻanga",
                    "PRB" => "ruble",
                    "TTD" => "dollars",
                    "TND" => "dinar",
                    "TMT" => "manat",
                    "TVD" => "dollars",
                    "UGX" => "shilling",
                    "UAH" => "hryvnia",
                    "AED" => "dirham",
                    "UYU" => "peso",
                    "UZS" => "soʻm",
                    "VUV" => "vatu",
                    "VES" => "bolívar",
                    "VND" => "đồng",
                    "YER" => "rial",
                    "ZMW" => "kwacha",
                    _ => "",
                };
            };
        }

        private static string FractionalUnit(string currencyIso, Form form)
        {
            if (form == Form.Singular)
            {
                return currencyIso switch
                {
                    "RUB" => "kopek",
                    "AFN" => "pul",
                    "EUR" => "cent",
                    "ALL" => "qindarkë",
                    "GBP" => "penny",
                    "GGP" => "penny",
                    "DZD" => "santeem",
                    "AOA" => "cêntimo",
                    "XCD" => "cent",
                    "ARS" => "centavo",
                    "AMD" => "luma",
                    "AWG" => "cent",
                    "SHP" => "penny",
                    "AUD" => "cent",
                    "AZN" => "qəpik",
                    "BSD" => "cent",
                    "BHD" => "fils",
                    "BDT" => "poisha",
                    "BBD" => "cent",
                    "BYN" => "kapyeyka",
                    "BZD" => "cent",
                    "XOF" => "centime",
                    "BMD" => "cent",
                    "BTN" => "chetrum",
                    "INR" => "paisa",
                    "BOB" => "centavo",
                    "USD" => "cent",
                    "BAM" => "fening",
                    "BWP" => "thebe",
                    "BRL" => "centavo",
                    "BND" => "sen",
                    "SGD" => "cent",
                    "BGN" => "stotinka",
                    "BIF" => "centime",
                    "KHR" => "sen",
                    "XAF" => "centime",
                    "CAD" => "cent",
                    "CVE" => "centavo",
                    "KYD" => "cent",
                    "CLP" => "centavo",
                    "CNY" => "jiao",
                    "COP" => "centavo",
                    "KMF" => "centime",
                    "CDF" => "centime",
                    "CKD" => "cent",
                    "NZD" => "cent",
                    "CRC" => "céntimo",
                    "HRK" => "lipa",
                    "CUP" => "centavo",
                    "CUC" => "centavo",
                    "ANG" => "cent",
                    "CZK" => "haléř",
                    "DKK" => "øre",
                    "DJF" => "centime",
                    "DOP" => "centavo",
                    "EGP" => "piastre",
                    "ERN" => "cent",
                    "SZL" => "cent",
                    "ZAR" => "cent",
                    "ETB" => "santim",
                    "FKP" => "penny",
                    "FOK" => "oyra",
                    "FJD" => "cent",
                    "XPF" => "centime",
                    "GMD" => "butut",
                    "GEL" => "tetri",
                    "GHS" => "pesewa",
                    "GIP" => "penny",
                    "GTQ" => "centavo",
                    "GNF" => "centime",
                    "GYD" => "cent",
                    "HTG" => "centime",
                    "HNL" => "centavo",
                    "HKD" => "cent",
                    "HUF" => "fillér",
                    "ISK" => "eyrir",
                    "IDR" => "sen",
                    "IRR" => "rial",
                    "IQD" => "fils",
                    "IMP" => "penny",
                    "ILS" => "agora",
                    "JMD" => "cent",
                    "JPY" => "sen",
                    "JEP" => "penny",
                    "JOD" => "piastre",
                    "KZT" => "tıyn",
                    "KES" => "cent",
                    "KID" => "cent",
                    "KPW" => "chon",
                    "KRW" => "jeon",
                    "KWD" => "fils",
                    "KGS" => "tyiyn",
                    "LAK" => "att",
                    "LBP" => "piastre",
                    "LSL" => "sente",
                    "LRD" => "cent",
                    "LYD" => "dirham",
                    "CHF" => "rappen",
                    "MOP" => "avo",
                    "MGA" => "iraimbilanja",
                    "MWK" => "tambala",
                    "MYR" => "sen",
                    "MVR" => "laari",
                    "MRU" => "khoums",
                    "MUR" => "cent",
                    "MXN" => "centavo",
                    "MDL" => "ban",
                    "MNT" => "möngö",
                    "MAD" => "centime",
                    "MZN" => "centavo",
                    "MMK" => "pya",
                    "NAD" => "cent",
                    "NPR" => "paisa",
                    "NIO" => "centavo",
                    "NGN" => "kobo",
                    "MKD" => "deni",
                    "TRY" => "kuruş",
                    "NOK" => "øre",
                    "OMR" => "baisa",
                    "PKR" => "paisa",
                    "PAB" => "centésimo",
                    "PGK" => "toea",
                    "PYG" => "céntimo",
                    "PEN" => "céntimo",
                    "PHP" => "sentimo",
                    "PND" => "cent",
                    "PLN" => "grosz",
                    "QAR" => "dirham",
                    "RON" => "ban",
                    "RWF" => "centime",
                    "WST" => "sene",
                    "STN" => "cêntimo",
                    "SAR" => "halala",
                    "RSD" => "para",
                    "SCR" => "cent",
                    "SLL" => "cent",
                    "SBD" => "cent",
                    "SOS" => "cent",
                    "SLS" => "cent",
                    "SSP" => "piaster",
                    "LKR" => "cent",
                    "SDG" => "qirsh",
                    "SRD" => "cent",
                    "SEK" => "öre",
                    "SYP" => "piastre",
                    "TWD" => "cent",
                    "TJS" => "diram",
                    "TZS" => "cent",
                    "THB" => "satang",
                    "TOP" => "seniti",
                    "PRB" => "kopek",
                    "TTD" => "cent",
                    "TND" => "millime",
                    "TMT" => "tennesi",
                    "TVD" => "cent",
                    "UGX" => "cent",
                    "UAH" => "kopiyka",
                    "AED" => "fils",
                    "UYU" => "centésimo",
                    "UZS" => "tiyin",
                    "VUV" => "",
                    "VES" => "céntimo",
                    "VND" => "hào",
                    "YER" => "fils",
                    "ZMW" => "ngwee",
                    _ => "",
                };
            }
            else
            {
                return currencyIso switch
                {
                    "RUB" => "kopek",
                    "AFN" => "pul",
                    "EUR" => "cents",
                    "ALL" => "qindarkë",
                    "GBP" => "pennies",
                    "GGP" => "pennies",
                    "DZD" => "santeem",
                    "AOA" => "cêntimo",
                    "XCD" => "cents",
                    "ARS" => "centavo",
                    "AMD" => "luma",
                    "AWG" => "cents",
                    "SHP" => "pennies",
                    "AUD" => "cents",
                    "AZN" => "qəpik",
                    "BSD" => "cents",
                    "BHD" => "fils",
                    "BDT" => "poisha",
                    "BBD" => "cents",
                    "BYN" => "kapyeyka",
                    "BZD" => "cents",
                    "XOF" => "centime",
                    "BMD" => "cents",
                    "BTN" => "chetrum",
                    "INR" => "paisa",
                    "BOB" => "centavo",
                    "USD" => "cents",
                    "BAM" => "fening",
                    "BWP" => "thebe",
                    "BRL" => "centavo",
                    "BND" => "sen",
                    "SGD" => "cents",
                    "BGN" => "stotinka",
                    "BIF" => "centime",
                    "KHR" => "sen",
                    "XAF" => "centime",
                    "CAD" => "cents",
                    "CVE" => "centavo",
                    "KYD" => "cents",
                    "CLP" => "centavo",
                    "CNY" => "jiao",
                    "COP" => "centavo",
                    "KMF" => "centime",
                    "CDF" => "centime",
                    "CKD" => "cents",
                    "NZD" => "cents",
                    "CRC" => "céntimo",
                    "HRK" => "lipa",
                    "CUP" => "centavo",
                    "CUC" => "centavo",
                    "ANG" => "cents",
                    "CZK" => "haléř",
                    "DKK" => "øre",
                    "DJF" => "centime",
                    "DOP" => "centavo",
                    "EGP" => "piastre",
                    "ERN" => "cents",
                    "SZL" => "cents",
                    "ZAR" => "cents",
                    "ETB" => "santim",
                    "FKP" => "pennies",
                    "FOK" => "oyra",
                    "FJD" => "cents",
                    "XPF" => "centime",
                    "GMD" => "butut",
                    "GEL" => "tetri",
                    "GHS" => "pesewa",
                    "GIP" => "pennies",
                    "GTQ" => "centavo",
                    "GNF" => "centime",
                    "GYD" => "cents",
                    "HTG" => "centime",
                    "HNL" => "centavo",
                    "HKD" => "cents",
                    "HUF" => "fillér",
                    "ISK" => "eyrir",
                    "IDR" => "sen",
                    "IRR" => "rial",
                    "IQD" => "fils",
                    "IMP" => "pennies",
                    "ILS" => "agora",
                    "JMD" => "cents",
                    "JPY" => "sen",
                    "JEP" => "pennies",
                    "JOD" => "piastre",
                    "KZT" => "tıyn",
                    "KES" => "cents",
                    "KID" => "cents",
                    "KPW" => "chon",
                    "KRW" => "jeon",
                    "KWD" => "fils",
                    "KGS" => "tyiyn",
                    "LAK" => "att",
                    "LBP" => "piastre",
                    "LSL" => "sente",
                    "LRD" => "cents",
                    "LYD" => "dirham",
                    "CHF" => "rappen",
                    "MOP" => "avo",
                    "MGA" => "iraimbilanja",
                    "MWK" => "tambala",
                    "MYR" => "sen",
                    "MVR" => "laari",
                    "MRU" => "khoums",
                    "MUR" => "cents",
                    "MXN" => "centavo",
                    "MDL" => "ban",
                    "MNT" => "möngö",
                    "MAD" => "centime",
                    "MZN" => "centavo",
                    "MMK" => "pya",
                    "NAD" => "cents",
                    "NPR" => "paisa",
                    "NIO" => "centavo",
                    "NGN" => "kobo",
                    "MKD" => "deni",
                    "TRY" => "kuruş",
                    "NOK" => "øre",
                    "OMR" => "baisa",
                    "PKR" => "paisa",
                    "PAB" => "centésimo",
                    "PGK" => "toea",
                    "PYG" => "céntimo",
                    "PEN" => "céntimo",
                    "PHP" => "sentimo",
                    "PND" => "cents",
                    "PLN" => "grosz",
                    "QAR" => "dirham",
                    "RON" => "ban",
                    "RWF" => "centime",
                    "WST" => "sene",
                    "STN" => "cêntimo",
                    "SAR" => "halala",
                    "RSD" => "para",
                    "SCR" => "cents",
                    "SLL" => "cents",
                    "SBD" => "cents",
                    "SOS" => "cents",
                    "SLS" => "cents",
                    "SSP" => "piaster",
                    "LKR" => "cents",
                    "SDG" => "qirsh",
                    "SRD" => "cents",
                    "SEK" => "öre",
                    "SYP" => "piastre",
                    "TWD" => "cents",
                    "TJS" => "diram",
                    "TZS" => "cents",
                    "THB" => "satang",
                    "TOP" => "seniti",
                    "PRB" => "kopek",
                    "TTD" => "cents",
                    "TND" => "millime",
                    "TMT" => "tennesi",
                    "TVD" => "cents",
                    "UGX" => "cents",
                    "UAH" => "kopiyka",
                    "AED" => "fils",
                    "UYU" => "centésimo",
                    "UZS" => "tiyin",
                    "VUV" => "",
                    "VES" => "céntimo",
                    "VND" => "hào",
                    "YER" => "fils",
                    "ZMW" => "ngwee",
                    _ => "",
                };

            }
        }

        private enum Form { Singular, Plural };
    }

    internal static class AmountInWordsCommon
    {
        /// <summary>
        /// Returns the number of decimal places used by a specific currency.
        /// </summary>
        /// <param name="currencyIso">The ISO 4217 Code of the currency</param>
        public static int Decimals(string currencyIso)
        {
            return currencyIso switch
            {
                "RUB" => 2,
                "AFN" => 2,
                "EUR" => 2,
                "ALL" => 2,
                "GBP" => 2,
                "DZD" => 2,
                "AOA" => 2,
                "XCD" => 2,
                "ARS" => 2,
                "AMD" => 2,
                "AWG" => 2,
                "SHP" => 2,
                "AUD" => 2,
                "AZN" => 2,
                "BSD" => 2,
                "BHD" => 3,
                "BDT" => 2,
                "BBD" => 2,
                "BYN" => 2,
                "BZD" => 2,
                "XOF" => 0,
                "BMD" => 2,
                "BTN" => 2,
                "INR" => 2,
                "BOB" => 2,
                "USD" => 2,
                "BAM" => 2,
                "BWP" => 2,
                "BRL" => 2,
                "BND" => 2,
                "SGD" => 2,
                "BGN" => 2,
                "BIF" => 0,
                "KHR" => 2,
                "XAF" => 0,
                "CAD" => 2,
                "CVE" => 2,
                "KYD" => 2,
                "CLP" => 0,
                "CNY" => 2,
                "COP" => 2,
                "KMF" => 0,
                "CDF" => 2,
                "NZD" => 2,
                "CRC" => 2,
                "HRK" => 2,
                "CUP" => 2,
                "CUC" => 2,
                "ANG" => 2,
                "CZK" => 2,
                "DKK" => 2,
                "DJF" => 0,
                "DOP" => 2,
                "EGP" => 2,
                "ERN" => 2,
                "SZL" => 2,
                "ZAR" => 2,
                "ETB" => 2,
                "FKP" => 2,
                "FJD" => 2,
                "XPF" => 0,
                "GMD" => 2,
                "GEL" => 2,
                "GHS" => 2,
                "GIP" => 2,
                "GTQ" => 2,
                "GNF" => 0,
                "GYD" => 2,
                "HTG" => 2,
                "HNL" => 2,
                "HKD" => 2,
                "HUF" => 2,
                "ISK" => 0,
                "IDR" => 2,
                "IRR" => 2,
                "IQD" => 3,
                "ILS" => 2,
                "JMD" => 2,
                "JPY" => 0,
                "JOD" => 3,
                "KZT" => 2,
                "KES" => 2,
                "KPW" => 2,
                "KRW" => 0,
                "KWD" => 3,
                "KGS" => 2,
                "LAK" => 2,
                "LBP" => 2,
                "LSL" => 2,
                "LRD" => 2,
                "LYD" => 3,
                "CHF" => 2,
                "MOP" => 2,
                "MGA" => 2,
                "MWK" => 2,
                "MYR" => 2,
                "MVR" => 2,
                "MRU" => 2,
                "MUR" => 2,
                "MXN" => 2,
                "MDL" => 2,
                "MNT" => 2,
                "MAD" => 2,
                "MZN" => 2,
                "MMK" => 2,
                "NAD" => 2,
                "NPR" => 2,
                "NIO" => 2,
                "NGN" => 2,
                "MKD" => 2,
                "TRY" => 2,
                "NOK" => 2,
                "OMR" => 3,
                "PKR" => 2,
                "PAB" => 2,
                "PGK" => 2,
                "PYG" => 0,
                "PEN" => 2,
                "PHP" => 2,
                "PLN" => 2,
                "QAR" => 2,
                "RON" => 2,
                "RWF" => 0,
                "WST" => 2,
                "STN" => 2,
                "SAR" => 2,
                "RSD" => 2,
                "SCR" => 2,
                "SLL" => 2,
                "SBD" => 2,
                "SOS" => 2,
                "SSP" => 2,
                "LKR" => 2,
                "SDG" => 2,
                "SRD" => 2,
                "SEK" => 2,
                "SYP" => 2,
                "TWD" => 2,
                "TJS" => 2,
                "TZS" => 2,
                "THB" => 2,
                "TOP" => 2,
                "TTD" => 2,
                "TND" => 3,
                "TMT" => 2,
                "UGX" => 0,
                "UAH" => 2,
                "AED" => 2,
                "UYU" => 2,
                "UZS" => 2,
                "VUV" => 0,
                "VES" => 2,
                "VND" => 0,
                "YER" => 2,
                "ZMW" => 2,
                _ => 2,
            };
        }
    }
}
