CREATE FUNCTION [dbo].[fw_TransactionLines__Json] (
	@Json NVARCHAR(MAX)
)
RETURNS TABLE
AS
RETURN
	SELECT c.*
	FROM OPENJSON (@json) p
		CROSS APPLY OpenJson(p.value, N'$.TransactionLines') 
	WITH (
		[Index]					INT,
		[DocumentIndex]			INT,

		[TransactionLineType]	NVARCHAR (255),
		[TemplateLineId]		INT, -- depending on the line type, the user may/may not be allowed to edit
		[ScalingFactor]			FLOAT, -- Qty sold for Price list, Qty produced for BOM
		[Memo]					NVARCHAR (255),

		[Direction1]			SMALLINT,
		[AccountId1]			INT,
		[ResponsibilityCenterId1]INT,
		[NoteId1]				NVARCHAR (255),
		[AgentAccountId1]		INT,
		[ResourceId1]			INT,
		[MoneyAmount1]			MONEY,
		[Mass1]					DECIMAL,
		[Volume1]				DECIMAL,
		[Count1]				DECIMAL,
		[Time1]					DECIMAL,
		[Value1]				VTYPE,
		[ExpectedClosingDate1]	DATETIMEOFFSET(7),
		[Reference1]			NVARCHAR (255),
		[Memo1]					NVARCHAR (255),
		[RelatedReference1]		NVARCHAR (255),
		[RelatedResourceId1]	INT,
		[RelatedAgentAccountId1]INT,
		[RelatedMoneyAmount1]	MONEY,
		[RelatedMass1]			DECIMAL,
		[RelatedVolume1]		DECIMAL,
		[RelatedCount1]			DECIMAL,
		[RelatedTime1]			DECIMAL,
		[RelatedValue1]			VTYPE,

		[Direction2]			SMALLINT,
		[AccountId2]			INT,
		[ResponsibilityCenterId2]INT,
		[NoteId2]				NVARCHAR (255),
		[AgentAccountId2]		INT,
		[ResourceId2]			INT,
		[MoneyAmount2]			MONEY,
		[Mass2]					DECIMAL,
		[Volume2]				DECIMAL,
		[Count2]				DECIMAL,
		[Time2]					DECIMAL,
		[Value2]				VTYPE,
		[ExpectedClosingDate2]	DATETIMEOFFSET(7),
		[Reference2]			NVARCHAR (255),
		[Memo2]					NVARCHAR (255),
		[RelatedReference2]		NVARCHAR (255),
		[RelatedResourceId2]	INT,
		[RelatedAgentAccountId2]INT,
		[RelatedMoneyAmount2]	MONEY,
		[RelatedMass2]			DECIMAL,
		[RelatedVolume2]		DECIMAL,
		[RelatedCount2]			DECIMAL,
		[RelatedTime2]			DECIMAL,
		[RelatedValue2]			VTYPE,

		[Direction3]			SMALLINT,
		[AccountId3]			INT,
		[ResponsibilityCenterId3]INT,
		[NoteId3]				NVARCHAR (255),
		[AgentAccountId3]		INT,
		[ResourceId3]			INT,
		[MoneyAmount3]			MONEY,
		[Mass3]					DECIMAL,
		[Volume3]				DECIMAL,
		[Count3]				DECIMAL,
		[Time3]					DECIMAL,
		[Value3]				VTYPE,
		[ExpectedClosingDate3]	DATETIMEOFFSET(7),
		[Reference3]			NVARCHAR (255),
		[Memo3]					NVARCHAR (255),
		[RelatedReference3]		NVARCHAR (255),
		[RelatedResourceId3]	INT,
		[RelatedAgentAccountId3]INT,
		[RelatedMoneyAmount3]	MONEY,
		[RelatedMass3]			DECIMAL,
		[RelatedVolume3]		DECIMAL,
		[RelatedCount3]			DECIMAL,
		[RelatedTime3]			DECIMAL,
		[RelatedValue3]			VTYPE,

		[Direction4]			SMALLINT,
		[AccountId4]			INT,
		[ResponsibilityCenterId4]INT,
		[NoteId4]				NVARCHAR (255),
		[AgentAccountId4]		INT,
		[ResourceId4]			INT,
		[MoneyAmount4]			MONEY,
		[Mass4]					DECIMAL,
		[Volume4]				DECIMAL,
		[Count4]				DECIMAL,
		[Time4]					DECIMAL,
		[Value4]				VTYPE,
		[ExpectedClosingDate4]	DATETIMEOFFSET(7),
		[Reference4]			NVARCHAR (255),
		[Memo4]					NVARCHAR (255),
		[RelatedReference4]		NVARCHAR (255),
		[RelatedResourceId4]	INT,
		[RelatedAgentAccountId4]INT,
		[RelatedMoneyAmount4]	MONEY,
		[RelatedMass4]			DECIMAL,
		[RelatedVolume4]		DECIMAL,
		[RelatedCount4]			DECIMAL,
		[RelatedTime4]			DECIMAL,
		[RelatedValue4]			VTYPE,

		[EntityState1]			NVARCHAR (255) '$.EntityState'
	) c;