CREATE PROCEDURE [dal].[ResourceDefinitions__Save]
	@Entities [ResourceDefinitionList] READONLY
AS
SET NOCOUNT ON;
	DECLARE @Now DATETIMEOFFSET(7) = SYSDATETIMEOFFSET();
	DECLARE @UserId INT = CONVERT(INT, SESSION_CONTEXT(N'UserId'));

	MERGE INTO [dbo].[ResourceDefinitions] AS t
	USING (
		SELECT 
			[Index],
			[Id],
			[TitleSingular],
			[TitleSingular2],
			[TitleSingular3],
			[TitlePlural],
			[TitlePlural2],
			[TitlePlural3],
			[ParentAccountTypeId],
			-- If null, no restriction. Otherwise, it restricts the types to those stemming from one of the nodes in the parent list
			--[CodeRegEx], -- Null means manually defined
			--[NameRegEx], -- Null means manually defined
			-- Resource properties
			-- [ResourceClassificationVisibility],
			[IdentifierLabel],
			[IdentifierLabel2],
			[IdentifierLabel3],		
			[IdentifierVisibility],
			[CurrencyVisibility],
			[CountUnitVisibility],
			[MassUnitVisibility],
			[VolumeUnitVisibility],
			[TimeUnitVisibility],
			-- [CustomsReferenceVisibility],
			-- [PreferredSupplierVisibility],
			[DescriptionVisibility],
			[AvailableSinceLabel],
			[AvailableSinceLabel2],
			[AvailableSinceLabel3],
			[AvailableSinceVisibility],
			[AvailableTillLabel],
			[AvailableTillLabel2],
			[AvailableTillLabel3],
			[AvailableTillVisibility],
			[Lookup1Label],
			[Lookup1Label2],
			[Lookup1Label3],
			[Lookup1Visibility],
			[Lookup1DefinitionId],
			[Lookup2Label],
			[Lookup2Label2],
			[Lookup2Label3],
			[Lookup2Visibility],
			[Lookup2DefinitionId],
			--[Lookup3Visibility]				 DEFAULT N'None' CHECK ([Lookup3Visibility] IN (N'None', N'Required', N'Optional')),
			--[Lookup3DefinitionId]				 CONSTRAINT [FK_ResourceDefinitions__Lookup3DefinitionId] REFERENCES dbo.LookupDefinitions([Id]),
			--[Lookup3Label],
			--[Lookup3Label2],
			--[Lookup3Label3],
			--[Lookup4Visibility]				 DEFAULT N'None' CHECK ([Lookup4Visibility] IN (N'None', N'Required', N'Optional')),
			--[Lookup4DefinitionId]				 CONSTRAINT [FK_ResourceDefinitions__Lookup4DefinitionId] REFERENCES dbo.LookupDefinitions([Id]),
			--[Lookup4Label],
			--[Lookup4Label2],
			--[Lookup4Label3],
			[DueDateLabel],
			[DueDateLabel2],
			[DueDateLabel3],
			[DueDateVisibility],
			-- more properties from Resource Instances to come..
			[MainMenuIcon],
			[MainMenuSection],			-- IF Null, it does not show on the main menu
			[MainMenuSortKey]
		FROM @Entities 
	) AS s ON (t.Id = s.[Id])
	WHEN MATCHED 
	THEN
		UPDATE SET 
			t.[TitleSingular] = s.[TitleSingular],
			t.[TitleSingular2] = s.[TitleSingular2],
			t.[TitleSingular3] = s.[TitleSingular3],
			t.[TitlePlural] = s.[TitlePlural],
			t.[TitlePlural2] = s.[TitlePlural2],
			t.[TitlePlural3] = s.[TitlePlural3],
			t.[ParentAccountTypeId] = s.[ParentAccountTypeId],
			-- If null, no restriction. Otherwise, it restricts the types to those stemming from one of the nodes in the parent list
			--t.[CodeRegEx] = s.[CodeRegEx], -- Null means manually defined
			--t.[NameRegEx] = s.[NameRegEx], -- Null means manually defined
			-- Resource properties
			t.[IdentifierLabel] = s.[IdentifierLabel],
			t.[IdentifierLabel2] = s.[IdentifierLabel2],
			t.[IdentifierLabel3] = s.[IdentifierLabel3],		
			t.[IdentifierVisibility] = s.[IdentifierVisibility],
			t.[CurrencyVisibility] = s.[CurrencyVisibility],
			t.[CountUnitVisibility] = s.[CountUnitVisibility],
			t.[MassUnitVisibility] = s.[MassUnitVisibility],
			t.[VolumeUnitVisibility] = s.[VolumeUnitVisibility],
			t.[TimeUnitVisibility] = s.[TimeUnitVisibility],
			-- [CustomsReferenceVisibility] = s.[CustomsReferenceVisibility],
			-- [PreferredSupplierVisibility] = s.[PreferredSupplierVisibility],
			t.[DescriptionVisibility] = s.[DescriptionVisibility],
			t.[AvailableSinceLabel] = s.[AvailableSinceLabel],
			t.[AvailableSinceLabel2] = s.[AvailableSinceLabel2],
			t.[AvailableSinceLabel3] = s.[AvailableSinceLabel3],
			t.[AvailableSinceVisibility] = s.[AvailableSinceVisibility],
			t.[AvailableTillLabel] = s.[AvailableTillLabel],
			t.[AvailableTillLabel2] = s.[AvailableTillLabel2],
			t.[AvailableTillLabel3] = s.[AvailableTillLabel3],
			t.[AvailableTillVisibility] = s.[AvailableTillVisibility],
			t.[Lookup1Label] = s.[Lookup1Label],
			t.[Lookup1Label2] = s.[Lookup1Label2],
			t.[Lookup1Label3] = s.[Lookup1Label3],
			t.[Lookup1Visibility] = s.[Lookup1Visibility],
			t.[Lookup1DefinitionId] = s.[Lookup1DefinitionId],
			t.[Lookup2Label] = s.[Lookup2Label],
			t.[Lookup2Label2] = s.[Lookup2Label2],
			t.[Lookup2Label3] = s.[Lookup2Label3],
			t.[Lookup2Visibility] = s.[Lookup2Visibility],
			t.[Lookup2DefinitionId] = s.[Lookup2DefinitionId],
			--t.[Lookup3Visibility] = s.[Lookup3Visibility],
			--t.[Lookup3DefinitionId] = s.[Lookup3DefinitionId],
			--t.[Lookup3Label] = s.[Lookup3Label],
			--t.[Lookup3Label2] = s.[Lookup3Label2],
			--t.[Lookup3Label3] = s.[Lookup3Label3],
			--t.[Lookup4Visibility] = s.[Lookup4Visibility],
			--t.[Lookup4DefinitionId] = s.[Lookup4DefinitionId],
			--t.[Lookup4Label] = s.[Lookup4Label],
			--t.[Lookup4Label2] = s.[Lookup4Label2],
			--t.[Lookup4Label3] = s.[Lookup4Label3],
			t.[DueDateLabel] = s.[DueDateLabel],
			t.[DueDateLabel2] = s.[DueDateLabel2],
			t.[DueDateLabel3] = s.[DueDateLabel3],
			t.[DueDateVisibility] = s.[DueDateVisibility],
			-- more properties from Resource Instances to come..
			t.[MainMenuIcon] = s.[MainMenuIcon],
			t.[MainMenuSection] = s.[MainMenuSection],			-- IF Null, it does not show on the main menu
			t.[MainMenuSortKey] = s.[MainMenuSortKey],
			t.[SavedById]					= @UserId
	WHEN NOT MATCHED THEN
		INSERT (
			[Id],
			[TitleSingular],
			[TitleSingular2],
			[TitleSingular3],
			[TitlePlural],
			[TitlePlural2],
			[TitlePlural3],
			[ParentAccountTypeId],
			-- If null, no restriction. Otherwise, it restricts the types to those stemming from one of the nodes in the parent list
			--[CodeRegEx], -- Null means manually defined
			--[NameRegEx], -- Null means manually defined
			-- Resource properties
			[IdentifierLabel],
			[IdentifierLabel2],
			[IdentifierLabel3],		
			[IdentifierVisibility],
			[CurrencyVisibility],
			[CountUnitVisibility],
			[MassUnitVisibility],
			[VolumeUnitVisibility],
			[TimeUnitVisibility],
			-- [CustomsReferenceVisibility],
			-- [PreferredSupplierVisibility],
			[DescriptionVisibility],
			[AvailableSinceLabel],
			[AvailableSinceLabel2],
			[AvailableSinceLabel3],
			[AvailableSinceVisibility],
			[AvailableTillLabel],
			[AvailableTillLabel2],
			[AvailableTillLabel3],
			[AvailableTillVisibility],
			[Lookup1Label],
			[Lookup1Label2],
			[Lookup1Label3],
			[Lookup1Visibility],
			[Lookup1DefinitionId],
			[Lookup2Label],
			[Lookup2Label2],
			[Lookup2Label3],
			[Lookup2Visibility],
			[Lookup2DefinitionId],
			--[Lookup3Visibility]				 DEFAULT N'None' CHECK ([Lookup3Visibility] IN (N'None', N'Required', N'Optional')),
			--[Lookup3DefinitionId]				 CONSTRAINT [FK_ResourceDefinitions__Lookup3DefinitionId] REFERENCES dbo.LookupDefinitions([Id]),
			--[Lookup3Label],
			--[Lookup3Label2],
			--[Lookup3Label3],
			--[Lookup4Visibility]				 DEFAULT N'None' CHECK ([Lookup4Visibility] IN (N'None', N'Required', N'Optional')),
			--[Lookup4DefinitionId]				 CONSTRAINT [FK_ResourceDefinitions__Lookup4DefinitionId] REFERENCES dbo.LookupDefinitions([Id]),
			--[Lookup4Label],
			--[Lookup4Label2],
			--[Lookup4Label3],
			[DueDateLabel],
			[DueDateLabel2],
			[DueDateLabel3],
			[DueDateVisibility],
			-- more properties from Resource Instances to come..
			[MainMenuIcon],
			[MainMenuSection],			-- IF Null, it does not show on the main menu
			[MainMenuSortKey]
			
			)
		VALUES (
			s.[Id],
			s.[TitleSingular],
			s.[TitleSingular2],
			s.[TitleSingular3],
			s.[TitlePlural],
			s.[TitlePlural2],
			s.[TitlePlural3],
			s.[ParentAccountTypeId],
			-- If null, no restriction. Otherwise, it restricts the types to those stemming from one of the nodes in the parent list
			--s.[CodeRegEx], -- Null means manually defined
			--s.[NameRegEx], -- Null means manually defined
			-- Resource properties
			s.[IdentifierLabel],
			s.[IdentifierLabel2],
			s.[IdentifierLabel3],		
			s.[IdentifierVisibility],
			s.[CurrencyVisibility],
			s.[CountUnitVisibility],
			s.[MassUnitVisibility],
			s.[VolumeUnitVisibility],
			s.[TimeUnitVisibility],
			-- [CustomsReferenceVisibility],
			-- [PreferredSupplierVisibility],
			s.[DescriptionVisibility],
			s.[AvailableSinceLabel],
			s.[AvailableSinceLabel2],
			s.[AvailableSinceLabel3],
			s.[AvailableSinceVisibility],
			s.[AvailableTillLabel],
			s.[AvailableTillLabel2],
			s.[AvailableTillLabel3],
			s.[AvailableTillVisibility],
			s.[Lookup1Label],
			s.[Lookup1Label2],
			s.[Lookup1Label3],
			s.[Lookup1Visibility],
			s.[Lookup1DefinitionId],
			s.[Lookup2Label],
			s.[Lookup2Label2],
			s.[Lookup2Label3],
			s.[Lookup2Visibility],
			s.[Lookup2DefinitionId],
			--s.[Lookup3Visibility]				 DEFAULT N'None' CHECK ([Lookup3Visibility] IN (N'None', N'Required', N'Optional')),
			--s.[Lookup3DefinitionId]				 CONSTRAINT [FK_ResourceDefinitions__Lookup3DefinitionId] REFERENCES dbo.LookupDefinitions([Id]),
			--s.[Lookup3Label],
			--s.[Lookup3Label2],
			--s.[Lookup3Label3],
			--s.[Lookup4Visibility]				 DEFAULT N'None' CHECK ([Lookup4Visibility] IN (N'None', N'Required', N'Optional')),
			--s.[Lookup4DefinitionId]				 CONSTRAINT [FK_ResourceDefinitions__Lookup4DefinitionId] REFERENCES dbo.LookupDefinitions([Id]),
			--s.[Lookup4Label],
			--s.[Lookup4Label2],
			--s.[Lookup4Label3],
			s.[DueDateLabel],
			s.[DueDateLabel2],
			s.[DueDateLabel3],
			s.[DueDateVisibility],
			-- more properties from Resource Instances to come..
			s.[MainMenuIcon],
			s.[MainMenuSection],			-- IF Null, it does not show on the main menu
			s.[MainMenuSortKey]
			
			);
