import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
  //{
  //  path: '',
  //  redirectTo: '/auto-generated',
  //  pathMatch: 'full',
  //},
  //{
  //  path: 'auto-generated',
  //  component: AutoGeneratedComponent,
  //}
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class RootRoutingModule { }
