CREATE FUNCTION [dbo].[fn_PeriodEndET__GC] (@GCDate DATE)
RETURNS DATE
AS
BEGIN
RETURN
	CASE
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),1,1) AND DATEFROMPARTS(YEAR(@GCDate),1,9)
			THEN DATEFROMPARTS(YEAR(@GCDate),1,9) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),1,10) AND DATEFROMPARTS(YEAR(@GCDate),2,7)
			THEN DATEFROMPARTS(YEAR(@GCDate),2,7) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),2,8) AND DATEFROMPARTS(YEAR(@GCDate),3,9)
			THEN DATEFROMPARTS(YEAR(@GCDate),3,9) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),3,10) AND DATEFROMPARTS(YEAR(@GCDate),4,8)
			THEN DATEFROMPARTS(YEAR(@GCDate),4,8) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),4,9) AND DATEFROMPARTS(YEAR(@GCDate),5,8)
			THEN DATEFROMPARTS(YEAR(@GCDate),5,8) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),5,9) AND DATEFROMPARTS(YEAR(@GCDate),6,7)
			THEN DATEFROMPARTS(YEAR(@GCDate),6,7) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),6,8) AND DATEFROMPARTS(YEAR(@GCDate),7,7)
			THEN DATEFROMPARTS(YEAR(@GCDate),7,7) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),7,8) AND DATEFROMPARTS(YEAR(@GCDate),8,6)
			THEN DATEFROMPARTS(YEAR(@GCDate),8,6) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),8,7) AND DATEFROMPARTS(YEAR(@GCDate),9,10)
			THEN DATEFROMPARTS(YEAR(@GCDate),9,10) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),9,11) AND DATEFROMPARTS(YEAR(@GCDate),10,10)
			THEN DATEFROMPARTS(YEAR(@GCDate),10,10) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),10,11) AND DATEFROMPARTS(YEAR(@GCDate),11,9)
			THEN DATEFROMPARTS(YEAR(@GCDate),11,9) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),11,10) AND DATEFROMPARTS(YEAR(@GCDate),12,9)
			THEN DATEFROMPARTS(YEAR(@GCDate),12,9) 
		WHEN @GCDate BETWEEN DATEFROMPARTS(YEAR(@GCDate),12,10) AND DATEFROMPARTS(YEAR(@GCDate),12,31)
			THEN DATEFROMPARTS(YEAR(@GCDate)+1,1,9) 
		ELSE @GCDate
	END
END
GO