CREATE TABLE [dbo].[Reconciliations] (
	[Id]			INT					CONSTRAINT [PK_Reconciliations] PRIMARY KEY IDENTITY,
	[CreatedAt]		DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[CreatedById]	INT	NOT NULL DEFAULT CONVERT(INT, SESSION_CONTEXT(N'UserId'))
);