CREATE TABLE [dbo].[Agents]
(
	[Id]				INT					CONSTRAINT [PK_Agents] PRIMARY KEY IDENTITY,
	[Name]				NVARCHAR (50)		NOT NULL,
	[Name2]				NVARCHAR (50),
	[Name3]				NVARCHAR (50),
	[IsRelated]			BIT					NOT NULL DEFAULT 0,
	[IsActive]			BIT					NOT NULL DEFAULT 1,
	[CreatedAt]			DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[CreatedById]		INT					NOT NULL DEFAULT CONVERT(INT, SESSION_CONTEXT(N'UserId')) CONSTRAINT [FK_Agents__CreatedById] REFERENCES [dbo].[Users] ([Id]),
	[ModifiedAt]		DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(), 
	[ModifiedById]		INT					NOT NULL DEFAULT CONVERT(INT, SESSION_CONTEXT(N'UserId')) CONSTRAINT [FK_Agents__ModifiedById] REFERENCES [dbo].[Users] ([Id])
)