using System;

namespace Tellma.Api.Templating
{
    public static class AmountInWordsEnglish
    {
        private static readonly string[] Units = { 
            "zero", 
            "one",
            "two",
            "three",
            "four", 
            "five", 
            "six", 
            "seven", 
            "eight", 
            "nine", 
            "ten", 
            "eleven", 
            "twelve", 
            "thirteen", 
            "fourteen", 
            "fifteen", 
            "sixteen", 
            "seventeen", 
            "eighteen", 
            "nineteen" 
        };

        private static readonly string[] Tens = { 
            "", 
            "", 
            "twenty", 
            "thirty", 
            "forty", 
            "fifty", 
            "sixty", 
            "seventy", 
            "eighty", 
            "ninety" 
        };

        /// <summary>
        /// Converts a decimal amount to words in the English language. Optionally adds a currency postfix.
        /// </summary>
        public static string ConvertAmount(decimal amount, string currencyIso = null, int? decimals = null)
        {
            // Get the number of decimal places depending on the currency
            decimals ??= AmountInWordsCommon.Decimals(currencyIso); // Some currencies do 2 decimal places, some 3, some 0
            int fractionMultiplier = decimals switch
            {
                0 => 1,
                2 => 100,
                3 => 1000,
                _ => throw new InvalidOperationException($"[Bug] Unhandled decimal {decimals}")
            };

            // Remember if it's negative
            bool isNegative = amount < 0;
            amount = Math.Abs(amount);

            // disect the number into the whole part and the decimal part
            long wholePart = (long)amount;
            long fractionPart = fractionMultiplier == 1 ? 0 : (long)Math.Round((amount - wholePart) * fractionMultiplier);

            // Get the names of the currency and its fractional unit (e.g. dollars and cents)
            string currency = CurrencyName(currencyIso, wholePart == 1 ? Form.Singular : Form.Plural);
            string fractionalUnit = FractionalUnit(currencyIso, fractionPart == 1 ? Form.Singular : Form.Plural);

            string result;
            if (fractionPart == 0)
            {
                if (currency != "")
                {
                    currency += " "; // 5 dollars only
                }

                result = ConvertInner(wholePart) + $" {currency}only";
            }
            else
            {
                if (currency == "")
                {
                    fractionalUnit = "";
                    currency = "point"; // 3 point 5 only
                }
                else if (fractionalUnit == "")
                {
                    currency += " point"; // 3 dollars point 5 only
                }
                else
                {
                    fractionalUnit += " "; // 3 dollars 5 cents only
                }

                result = ConvertInner(wholePart) + $" {currency} " + ConvertInner(fractionPart) + $" {fractionalUnit}only";
            }

            if (isNegative)
            {
                result = "negative " + result;
            }

            // Capitalize
            if (result.Length > 0)
            {
                result = char.ToUpper(result[0]) + result[1..];
            }

            // Return
            return result;
        }

        private static string ConvertInner(long n)
        {
            if (n < 20L)
            {
                return Units[n];
            }
            else if (n < 100L)
            {
                return Tens[n / 10L] + ((n % 10L > 0) ? " " + ConvertInner(n % 10L) : "");
            }
            else if (n < 1000L)
            {
                return Units[n / 100L] + " hundred" + ((n % 100L > 0) ? " " + ConvertInner(n % 100L) : "");
            }
            else if (n < 1000000L)
            {
                return ConvertInner(n / 1000) + " thousand" + ((n % 1000L > 0) ? " " + ConvertInner(n % 1000L) : "");
            }
            else if (n < 1000000000L)
            {
                return ConvertInner(n / 1000000L) + " million" + ((n % 1000000L > 0) ? " " + ConvertInner(n % 1000000L) : "");
            }
            else if (n < 1000000000000L)
            {
                return ConvertInner(n / 1000000000L) + " billion" + ((n % 1000000000L > 0) ? " " + ConvertInner(n % 1000000000L) : "");
            }
            else if (n < 1000000000000000L)
            {
                return ConvertInner(n / 1000000000000L) + " trillion" + ((n % 1000000000000L > 0) ? " " + ConvertInner(n % 1000000000000L) : "");
            }
            else if (n <= long.MaxValue)
            {
                return ConvertInner(n / 1000000000000000L) + " quadrillion" + ((n % 1000000000000000L > 0) ? " " + ConvertInner(n % 1000000000000000L) : "");
            }
            else
            {
                throw new InvalidOperationException($"Conversion to words can only handle amounts less than or equal {long.MaxValue:N2}");
            }
        }

        private static string CurrencyName(string currencyIso, Form form)
        {
            if (form == Form.Singular)
            {
                return currencyIso switch
                {
                    "RUB" => "ruble",
                    "AFN" => "afghani",
                    "EUR" => "euro",
                    "ALL" => "lek",
                    "GBP" => "pound",
                    "GGP" => "pound",
                    "DZD" => "dinar",
                    "AOA" => "kwanza",
                    "XCD" => "dollar",
                    "ARS" => "peso",
                    "AMD" => "dram",
                    "AWG" => "florin",
                    "SHP" => "pound",
                    "AUD" => "dollar",
                    "AZN" => "manat",
                    "BSD" => "dollar",
                    "BHD" => "dinar",
                    "BDT" => "taka",
                    "BBD" => "dollar",
                    "BYN" => "ruble",
                    "BZD" => "dollar",
                    "XOF" => "franc",
                    "BMD" => "dollar",
                    "BTN" => "ngultrum",
                    "INR" => "rupee",
                    "BOB" => "boliviano",
                    "USD" => "dollar",
                    "BAM" => "mark",
                    "BWP" => "pula",
                    "BRL" => "real",
                    "BND" => "dollar",
                    "SGD" => "dollar",
                    "BGN" => "lev",
                    "BIF" => "franc",
                    "KHR" => "riel",
                    "XAF" => "franc",
                    "CAD" => "dollar",
                    "CVE" => "escudo",
                    "KYD" => "dollar",
                    "CLP" => "peso",
                    "CNY" => "yuan",
                    "COP" => "peso",
                    "KMF" => "franc",
                    "CDF" => "franc",
                    "CKD" => "dollar",
                    "NZD" => "dollar",
                    "CRC" => "colón",
                    "HRK" => "kuna",
                    "CUP" => "peso",
                    "CUC" => "peso",
                    "ANG" => "guilder",
                    "CZK" => "koruna",
                    "DKK" => "krone",
                    "DJF" => "franc",
                    "DOP" => "peso",
                    "EGP" => "pound",
                    "ERN" => "nakfa",
                    "SZL" => "lilangeni",
                    "ZAR" => "rand",
                    "ETB" => "birr",
                    "FKP" => "pound",
                    "FOK" => "króna",
                    "FJD" => "dollar",
                    "XPF" => "franc",
                    "GMD" => "dalasi",
                    "GEL" => "lari",
                    "GHS" => "cedi",
                    "GIP" => "pound",
                    "GTQ" => "quetzal",
                    "GNF" => "franc",
                    "GYD" => "dollar",
                    "HTG" => "gourde",
                    "HNL" => "lempira",
                    "HKD" => "dollar",
                    "HUF" => "forint",
                    "ISK" => "króna",
                    "IDR" => "rupiah",
                    "IRR" => "rial",
                    "IQD" => "dinar",
                    "IMP" => "pound",
                    "ILS" => "shekel",
                    "JMD" => "dollar",
                    "JPY" => "yen",
                    "JEP" => "pound",
                    "JOD" => "dinar",
                    "KZT" => "tenge",
                    "KES" => "shilling",
                    "KID" => "dollar",
                    "KPW" => "won",
                    "KRW" => "won",
                    "KWD" => "dinar",
                    "KGS" => "som",
                    "LAK" => "kip",
                    "LBP" => "pound",
                    "LSL" => "loti",
                    "LRD" => "dollar",
                    "LYD" => "dinar",
                    "CHF" => "franc",
                    "MOP" => "pataca",
                    "MGA" => "ariary",
                    "MWK" => "kwacha",
                    "MYR" => "ringgit",
                    "MVR" => "rufiyaa",
                    "MRU" => "ouguiya",
                    "MUR" => "rupee",
                    "MXN" => "peso",
                    "MDL" => "leu",
                    "MNT" => "tögrög",
                    "MAD" => "dirham",
                    "MZN" => "metical",
                    "MMK" => "kyat",
                    "NAD" => "dollar",
                    "NPR" => "rupee",
                    "NIO" => "córdoba",
                    "NGN" => "naira",
                    "MKD" => "denar",
                    "TRY" => "lira",
                    "NOK" => "krone",
                    "OMR" => "rial",
                    "PKR" => "rupee",
                    "PAB" => "balboa",
                    "PGK" => "kina",
                    "PYG" => "guaraní",
                    "PEN" => "sol",
                    "PHP" => "peso",
                    "PND" => "dollar",
                    "PLN" => "złoty",
                    "QAR" => "riyal",
                    "RON" => "leu",
                    "RWF" => "franc",
                    "WST" => "tālā",
                    "STN" => "dobra",
                    "SAR" => "riyal",
                    "RSD" => "dinar",
                    "SCR" => "rupee",
                    "SLL" => "leone",
                    "SBD" => "dollar",
                    "SOS" => "shilling",
                    "SLS" => "shilling",
                    "SSP" => "pound",
                    "LKR" => "rupee",
                    "SDG" => "pound",
                    "SRD" => "dollar",
                    "SEK" => "krona",
                    "SYP" => "pound",
                    "TWD" => "dollar",
                    "TJS" => "somoni",
                    "TZS" => "shilling",
                    "THB" => "baht",
                    "TOP" => "paʻanga",
                    "PRB" => "ruble",
                    "TTD" => "dollar",
                    "TND" => "dinar",
                    "TMT" => "manat",
                    "TVD" => "dollar",
                    "UGX" => "shilling",
                    "UAH" => "hryvnia",
                    "AED" => "dirham",
                    "UYU" => "peso",
                    "UZS" => "soʻm",
                    "VUV" => "vatu",
                    "VES" => "bolívar",
                    "VND" => "đồng",
                    "YER" => "rial",
                    "ZMW" => "kwacha",
                    _ => "",
                };
            }
            else
            {
                return currencyIso switch
                {
                    "RUB" => "ruble",
                    "AFN" => "afghani",
                    "EUR" => "euros",
                    "ALL" => "lek",
                    "GBP" => "pounds",
                    "GGP" => "pounds",
                    "DZD" => "dinar",
                    "AOA" => "kwanza",
                    "XCD" => "dollars",
                    "ARS" => "peso",
                    "AMD" => "dram",
                    "AWG" => "florin",
                    "SHP" => "pounds",
                    "AUD" => "dollars",
                    "AZN" => "manat",
                    "BSD" => "dollars",
                    "BHD" => "dinar",
                    "BDT" => "taka",
                    "BBD" => "dollars",
                    "BYN" => "ruble",
                    "BZD" => "dollars",
                    "XOF" => "franc",
                    "BMD" => "dollars",
                    "BTN" => "ngultrum",
                    "INR" => "rupee",
                    "BOB" => "boliviano",
                    "USD" => "dollars",
                    "BAM" => "mark",
                    "BWP" => "pula",
                    "BRL" => "real",
                    "BND" => "dollars",
                    "SGD" => "dollars",
                    "BGN" => "lev",
                    "BIF" => "franc",
                    "KHR" => "riel",
                    "XAF" => "franc",
                    "CAD" => "dollars",
                    "CVE" => "escudo",
                    "KYD" => "dollars",
                    "CLP" => "peso",
                    "CNY" => "yuan",
                    "COP" => "peso",
                    "KMF" => "franc",
                    "CDF" => "franc",
                    "CKD" => "dollars",
                    "NZD" => "dollars",
                    "CRC" => "colón",
                    "HRK" => "kuna",
                    "CUP" => "peso",
                    "CUC" => "peso",
                    "ANG" => "guilder",
                    "CZK" => "koruna",
                    "DKK" => "krone",
                    "DJF" => "franc",
                    "DOP" => "peso",
                    "EGP" => "pounds",
                    "ERN" => "nakfa",
                    "SZL" => "lilangeni",
                    "ZAR" => "rand",
                    "ETB" => "birr",
                    "FKP" => "pounds",
                    "FOK" => "króna",
                    "FJD" => "dollars",
                    "XPF" => "franc",
                    "GMD" => "dalasi",
                    "GEL" => "lari",
                    "GHS" => "cedi",
                    "GIP" => "pounds",
                    "GTQ" => "quetzal",
                    "GNF" => "franc",
                    "GYD" => "dollars",
                    "HTG" => "gourde",
                    "HNL" => "lempira",
                    "HKD" => "dollars",
                    "HUF" => "forint",
                    "ISK" => "króna",
                    "IDR" => "rupiah",
                    "IRR" => "rial",
                    "IQD" => "dinar",
                    "IMP" => "pounds",
                    "ILS" => "shekel",
                    "JMD" => "dollars",
                    "JPY" => "yen",
                    "JEP" => "pounds",
                    "JOD" => "dinar",
                    "KZT" => "tenge",
                    "KES" => "shilling",
                    "KID" => "dollars",
                    "KPW" => "won",
                    "KRW" => "won",
                    "KWD" => "dinar",
                    "KGS" => "som",
                    "LAK" => "kip",
                    "LBP" => "pounds",
                    "LSL" => "loti",
                    "LRD" => "dollars",
                    "LYD" => "dinar",
                    "CHF" => "franc",
                    "MOP" => "pataca",
                    "MGA" => "ariary",
                    "MWK" => "kwacha",
                    "MYR" => "ringgit",
                    "MVR" => "rufiyaa",
                    "MRU" => "ouguiya",
                    "MUR" => "rupee",
                    "MXN" => "peso",
                    "MDL" => "leu",
                    "MNT" => "tögrög",
                    "MAD" => "dirham",
                    "MZN" => "metical",
                    "MMK" => "kyat",
                    "NAD" => "dollars",
                    "NPR" => "rupee",
                    "NIO" => "córdoba",
                    "NGN" => "naira",
                    "MKD" => "denar",
                    "TRY" => "lira",
                    "NOK" => "krone",
                    "OMR" => "rial",
                    "PKR" => "rupee",
                    "PAB" => "balboa",
                    "PGK" => "kina",
                    "PYG" => "guaraní",
                    "PEN" => "sol",
                    "PHP" => "peso",
                    "PND" => "dollars",
                    "PLN" => "złoty",
                    "QAR" => "riyal",
                    "RON" => "leu",
                    "RWF" => "franc",
                    "WST" => "tālā",
                    "STN" => "dobra",
                    "SAR" => "riyal",
                    "RSD" => "dinar",
                    "SCR" => "rupee",
                    "SLL" => "leone",
                    "SBD" => "dollars",
                    "SOS" => "shilling",
                    "SLS" => "shilling",
                    "SSP" => "pounds",
                    "LKR" => "rupee",
                    "SDG" => "pounds",
                    "SRD" => "dollars",
                    "SEK" => "krona",
                    "SYP" => "pounds",
                    "TWD" => "dollars",
                    "TJS" => "somoni",
                    "TZS" => "shilling",
                    "THB" => "baht",
                    "TOP" => "paʻanga",
                    "PRB" => "ruble",
                    "TTD" => "dollars",
                    "TND" => "dinar",
                    "TMT" => "manat",
                    "TVD" => "dollars",
                    "UGX" => "shilling",
                    "UAH" => "hryvnia",
                    "AED" => "dirham",
                    "UYU" => "peso",
                    "UZS" => "soʻm",
                    "VUV" => "vatu",
                    "VES" => "bolívar",
                    "VND" => "đồng",
                    "YER" => "rial",
                    "ZMW" => "kwacha",
                    _ => "",
                };
            };
        }

        private static string FractionalUnit(string currencyIso, Form form)
        {
            if (form == Form.Singular)
            {
                return currencyIso switch
                {
                    "RUB" => "kopek",
                    "AFN" => "pul",
                    "EUR" => "cent",
                    "ALL" => "qindarkë",
                    "GBP" => "penny",
                    "GGP" => "penny",
                    "DZD" => "santeem",
                    "AOA" => "cêntimo",
                    "XCD" => "cent",
                    "ARS" => "centavo",
                    "AMD" => "luma",
                    "AWG" => "cent",
                    "SHP" => "penny",
                    "AUD" => "cent",
                    "AZN" => "qəpik",
                    "BSD" => "cent",
                    "BHD" => "fils",
                    "BDT" => "poisha",
                    "BBD" => "cent",
                    "BYN" => "kapyeyka",
                    "BZD" => "cent",
                    "XOF" => "centime",
                    "BMD" => "cent",
                    "BTN" => "chetrum",
                    "INR" => "paisa",
                    "BOB" => "centavo",
                    "USD" => "cent",
                    "BAM" => "fening",
                    "BWP" => "thebe",
                    "BRL" => "centavo",
                    "BND" => "sen",
                    "SGD" => "cent",
                    "BGN" => "stotinka",
                    "BIF" => "centime",
                    "KHR" => "sen",
                    "XAF" => "centime",
                    "CAD" => "cent",
                    "CVE" => "centavo",
                    "KYD" => "cent",
                    "CLP" => "centavo",
                    "CNY" => "jiao",
                    "COP" => "centavo",
                    "KMF" => "centime",
                    "CDF" => "centime",
                    "CKD" => "cent",
                    "NZD" => "cent",
                    "CRC" => "céntimo",
                    "HRK" => "lipa",
                    "CUP" => "centavo",
                    "CUC" => "centavo",
                    "ANG" => "cent",
                    "CZK" => "haléř",
                    "DKK" => "øre",
                    "DJF" => "centime",
                    "DOP" => "centavo",
                    "EGP" => "piastre",
                    "ERN" => "cent",
                    "SZL" => "cent",
                    "ZAR" => "cent",
                    "ETB" => "santim",
                    "FKP" => "penny",
                    "FOK" => "oyra",
                    "FJD" => "cent",
                    "XPF" => "centime",
                    "GMD" => "butut",
                    "GEL" => "tetri",
                    "GHS" => "pesewa",
                    "GIP" => "penny",
                    "GTQ" => "centavo",
                    "GNF" => "centime",
                    "GYD" => "cent",
                    "HTG" => "centime",
                    "HNL" => "centavo",
                    "HKD" => "cent",
                    "HUF" => "fillér",
                    "ISK" => "eyrir",
                    "IDR" => "sen",
                    "IRR" => "rial",
                    "IQD" => "fils",
                    "IMP" => "penny",
                    "ILS" => "agora",
                    "JMD" => "cent",
                    "JPY" => "sen",
                    "JEP" => "penny",
                    "JOD" => "piastre",
                    "KZT" => "tıyn",
                    "KES" => "cent",
                    "KID" => "cent",
                    "KPW" => "chon",
                    "KRW" => "jeon",
                    "KWD" => "fils",
                    "KGS" => "tyiyn",
                    "LAK" => "att",
                    "LBP" => "piastre",
                    "LSL" => "sente",
                    "LRD" => "cent",
                    "LYD" => "dirham",
                    "CHF" => "rappen",
                    "MOP" => "avo",
                    "MGA" => "iraimbilanja",
                    "MWK" => "tambala",
                    "MYR" => "sen",
                    "MVR" => "laari",
                    "MRU" => "khoums",
                    "MUR" => "cent",
                    "MXN" => "centavo",
                    "MDL" => "ban",
                    "MNT" => "möngö",
                    "MAD" => "centime",
                    "MZN" => "centavo",
                    "MMK" => "pya",
                    "NAD" => "cent",
                    "NPR" => "paisa",
                    "NIO" => "centavo",
                    "NGN" => "kobo",
                    "MKD" => "deni",
                    "TRY" => "kuruş",
                    "NOK" => "øre",
                    "OMR" => "baisa",
                    "PKR" => "paisa",
                    "PAB" => "centésimo",
                    "PGK" => "toea",
                    "PYG" => "céntimo",
                    "PEN" => "céntimo",
                    "PHP" => "sentimo",
                    "PND" => "cent",
                    "PLN" => "grosz",
                    "QAR" => "dirham",
                    "RON" => "ban",
                    "RWF" => "centime",
                    "WST" => "sene",
                    "STN" => "cêntimo",
                    "SAR" => "halala",
                    "RSD" => "para",
                    "SCR" => "cent",
                    "SLL" => "cent",
                    "SBD" => "cent",
                    "SOS" => "cent",
                    "SLS" => "cent",
                    "SSP" => "piaster",
                    "LKR" => "cent",
                    "SDG" => "qirsh",
                    "SRD" => "cent",
                    "SEK" => "öre",
                    "SYP" => "piastre",
                    "TWD" => "cent",
                    "TJS" => "diram",
                    "TZS" => "cent",
                    "THB" => "satang",
                    "TOP" => "seniti",
                    "PRB" => "kopek",
                    "TTD" => "cent",
                    "TND" => "millime",
                    "TMT" => "tennesi",
                    "TVD" => "cent",
                    "UGX" => "cent",
                    "UAH" => "kopiyka",
                    "AED" => "fils",
                    "UYU" => "centésimo",
                    "UZS" => "tiyin",
                    "VUV" => "",
                    "VES" => "céntimo",
                    "VND" => "hào",
                    "YER" => "fils",
                    "ZMW" => "ngwee",
                    _ => "",
                };
            }
            else
            {
                return currencyIso switch
                {
                    "RUB" => "kopek",
                    "AFN" => "pul",
                    "EUR" => "cents",
                    "ALL" => "qindarkë",
                    "GBP" => "pennies",
                    "GGP" => "pennies",
                    "DZD" => "santeem",
                    "AOA" => "cêntimo",
                    "XCD" => "cents",
                    "ARS" => "centavo",
                    "AMD" => "luma",
                    "AWG" => "cents",
                    "SHP" => "pennies",
                    "AUD" => "cents",
                    "AZN" => "qəpik",
                    "BSD" => "cents",
                    "BHD" => "fils",
                    "BDT" => "poisha",
                    "BBD" => "cents",
                    "BYN" => "kapyeyka",
                    "BZD" => "cents",
                    "XOF" => "centime",
                    "BMD" => "cents",
                    "BTN" => "chetrum",
                    "INR" => "paisa",
                    "BOB" => "centavo",
                    "USD" => "cents",
                    "BAM" => "fening",
                    "BWP" => "thebe",
                    "BRL" => "centavo",
                    "BND" => "sen",
                    "SGD" => "cents",
                    "BGN" => "stotinka",
                    "BIF" => "centime",
                    "KHR" => "sen",
                    "XAF" => "centime",
                    "CAD" => "cents",
                    "CVE" => "centavo",
                    "KYD" => "cents",
                    "CLP" => "centavo",
                    "CNY" => "jiao",
                    "COP" => "centavo",
                    "KMF" => "centime",
                    "CDF" => "centime",
                    "CKD" => "cents",
                    "NZD" => "cents",
                    "CRC" => "céntimo",
                    "HRK" => "lipa",
                    "CUP" => "centavo",
                    "CUC" => "centavo",
                    "ANG" => "cents",
                    "CZK" => "haléř",
                    "DKK" => "øre",
                    "DJF" => "centime",
                    "DOP" => "centavo",
                    "EGP" => "piastre",
                    "ERN" => "cents",
                    "SZL" => "cents",
                    "ZAR" => "cents",
                    "ETB" => "santim",
                    "FKP" => "pennies",
                    "FOK" => "oyra",
                    "FJD" => "cents",
                    "XPF" => "centime",
                    "GMD" => "butut",
                    "GEL" => "tetri",
                    "GHS" => "pesewa",
                    "GIP" => "pennies",
                    "GTQ" => "centavo",
                    "GNF" => "centime",
                    "GYD" => "cents",
                    "HTG" => "centime",
                    "HNL" => "centavo",
                    "HKD" => "cents",
                    "HUF" => "fillér",
                    "ISK" => "eyrir",
                    "IDR" => "sen",
                    "IRR" => "rial",
                    "IQD" => "fils",
                    "IMP" => "pennies",
                    "ILS" => "agora",
                    "JMD" => "cents",
                    "JPY" => "sen",
                    "JEP" => "pennies",
                    "JOD" => "piastre",
                    "KZT" => "tıyn",
                    "KES" => "cents",
                    "KID" => "cents",
                    "KPW" => "chon",
                    "KRW" => "jeon",
                    "KWD" => "fils",
                    "KGS" => "tyiyn",
                    "LAK" => "att",
                    "LBP" => "piastre",
                    "LSL" => "sente",
                    "LRD" => "cents",
                    "LYD" => "dirham",
                    "CHF" => "rappen",
                    "MOP" => "avo",
                    "MGA" => "iraimbilanja",
                    "MWK" => "tambala",
                    "MYR" => "sen",
                    "MVR" => "laari",
                    "MRU" => "khoums",
                    "MUR" => "cents",
                    "MXN" => "centavo",
                    "MDL" => "ban",
                    "MNT" => "möngö",
                    "MAD" => "centime",
                    "MZN" => "centavo",
                    "MMK" => "pya",
                    "NAD" => "cents",
                    "NPR" => "paisa",
                    "NIO" => "centavo",
                    "NGN" => "kobo",
                    "MKD" => "deni",
                    "TRY" => "kuruş",
                    "NOK" => "øre",
                    "OMR" => "baisa",
                    "PKR" => "paisa",
                    "PAB" => "centésimo",
                    "PGK" => "toea",
                    "PYG" => "céntimo",
                    "PEN" => "céntimo",
                    "PHP" => "sentimo",
                    "PND" => "cents",
                    "PLN" => "grosz",
                    "QAR" => "dirham",
                    "RON" => "ban",
                    "RWF" => "centime",
                    "WST" => "sene",
                    "STN" => "cêntimo",
                    "SAR" => "halala",
                    "RSD" => "para",
                    "SCR" => "cents",
                    "SLL" => "cents",
                    "SBD" => "cents",
                    "SOS" => "cents",
                    "SLS" => "cents",
                    "SSP" => "piaster",
                    "LKR" => "cents",
                    "SDG" => "qirsh",
                    "SRD" => "cents",
                    "SEK" => "öre",
                    "SYP" => "piastre",
                    "TWD" => "cents",
                    "TJS" => "diram",
                    "TZS" => "cents",
                    "THB" => "satang",
                    "TOP" => "seniti",
                    "PRB" => "kopek",
                    "TTD" => "cents",
                    "TND" => "millime",
                    "TMT" => "tennesi",
                    "TVD" => "cents",
                    "UGX" => "cents",
                    "UAH" => "kopiyka",
                    "AED" => "fils",
                    "UYU" => "centésimo",
                    "UZS" => "tiyin",
                    "VUV" => "",
                    "VES" => "céntimo",
                    "VND" => "hào",
                    "YER" => "fils",
                    "ZMW" => "ngwee",
                    _ => "",
                };

            }
        }

        private enum Form { Singular, Plural };
    }
}
