// <auto-generated />
using BSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSharp.Data.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181125211519_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BSharp.Data.Model.Application.Translation", b =>
                {
                    b.Property<int>("TenantId");

                    b.Property<string>("Tier")
                        .HasMaxLength(50);

                    b.Property<string>("Culture")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(450);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.HasKey("TenantId", "Tier", "Culture", "Name");

                    b.HasIndex("TenantId");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
