CREATE FUNCTION [map].[Resources] ()
RETURNS TABLE
AS
RETURN (
	SELECT
		[Id],
		[DefinitionId],
		[Name],
		[Name2],
		[Name3],
		[Code],
		[CurrencyId],
		[CenterId],
		[ImageId],
		[Description],
		[Description2],
		[Description3],
		[Location],
		[LocationJson],
		[FromDate],
		[ToDate],
		[Date1],
		[Date2],
		[Date3],
		[Date4],
		[Decimal1],
		[Decimal2],
		[Decimal3],
		[Decimal4],
		[Int1],
		[Int2],
		[Lookup1Id],
		[Lookup2Id],
		[Lookup3Id],
		[Lookup4Id],
		[Text1],
		[Text2],
		[Identifier],
		[VatRate],
		[ReorderLevel],
		[EconomicOrderQuantity],
		[UnitId],
		[UnitMass],
		[UnitMassUnitId],
		[MonetaryValue],
		[Agent1Id],
		[Agent2Id],
		[Resource1Id],
		[Resource2Id],
		[IsActive],
		[CreatedAt],
		[CreatedById],
		[ModifiedAt],
		[ModifiedById],
		[Location].STAsBinary() AS [LocationWkb]
	FROM [dbo].[Resources]
);
