CREATE FUNCTION [map].[AccountTypes] ()
RETURNS TABLE
AS
RETURN (
SELECT
    Q.[Id],
    Q.[ParentId],
    Q.[Code],
    Q.[Concept],
    Q.[Name],
    Q.[Name2],
    Q.[Name3],
    Q.[Description],
    Q.[Description2],
    Q.[Description3],
    Q.[Node],
    Q.[IsMonetary],
    Q.[IsAssignable],
    Q.[StandardAndPure],
    Q.[RelationDefinitionId],
    Q.[CustodianDefinitionId],
    Q.[NotedRelationDefinitionId],
    Q.[EntryTypeParentId],
    Q.[Time1Label],
    Q.[Time1Label2],
    Q.[Time1Label3],
    Q.[Time2Label],
    Q.[Time2Label2],
    Q.[Time2Label3],
    Q.[ExternalReferenceLabel],
    Q.[ExternalReferenceLabel2],
    Q.[ExternalReferenceLabel3],
    Q.[InternalReferenceLabel],
    Q.[InternalReferenceLabel2],
    Q.[InternalReferenceLabel3],
    Q.[NotedAgentNameLabel],
    Q.[NotedAgentNameLabel2],
    Q.[NotedAgentNameLabel3],
    Q.[NotedAmountLabel],
    Q.[NotedAmountLabel2],
    Q.[NotedAmountLabel3],
    Q.[NotedDateLabel],
    Q.[NotedDateLabel2],
    Q.[NotedDateLabel3],
    Q.[IsActive],
    Q.[IsSystem],
    Q.[SavedById],
    Q.[ValidFrom],
    Q.[ValidTo],
    Q.[IsBusinessUnit],
    [Node].GetAncestor(1)  AS [ParentNode],
    [Node].GetLevel() AS [Level],
    [Node].ToString() AS [Path],
	Q.[ActiveChildCount],
	Q.[ChildCount]
FROM [dbo].[AccountTypes] Q
);
