INSERT INTO @Accounts([Index], [AccountTypeId], [ClassificationId],[Code],[Name],[Name2],[AgentDefinitionId],[ResourceDefinitionId],[NotedAgentDefinitionId]) VALUES
(11010100,@Land,NULL, '11010100', N'Land', N'أراضي -',@LandMemberAD,@DepreciationBasesRD,NULL),
(11010200,@Buildings,NULL, '11010200', N'Buildings', N'مباني -',@BuildingsMemberAD,@DepreciationBasesRD,NULL),
(11010310,@Machinery,NULL, '11010310', N'Machinery', N'الالات -',@MachineryMemberAD,@DepreciationBasesRD,NULL),
(11010320,@Machinery,NULL, '11010320', N'Power generating assets', N'أصول مولدة للطاقة',@PowerGeneratingAssetsMemberAD,@DepreciationBasesRD,NULL),
(11010400,@Ships,NULL, '11010400', N'Ships', N'السفن',@ShipsMemberAD,@DepreciationBasesRD,NULL),
(11010500,@Aircraft,NULL, '11010500', N'Aircrafts', N'الطائرات',@AircraftMemberAD,@DepreciationBasesRD,NULL),
(11010600,@MotorVehicles,NULL, '11010600', N'Motor Vehicles', N'العربات',@MotorVehiclesMemberAD,@DepreciationBasesRD,NULL),
(11010710,@FixturesAndFittings,NULL, '11010710', N'Fixtures and fittings', N'التركيبات والتجهيزات -',@FixturesAndFittingsMemberAD,@DepreciationBasesRD,NULL),
(11010720,@FixturesAndFittings,NULL, '11010720', N'Network infrastructure', N'البنية التحتية للشبكة',@NetworkInfrastructureMemberAD,@DepreciationBasesRD,NULL),
(11010730,@FixturesAndFittings,NULL, '11010730', N'Leasehold improvements', N'تحسينات عقارية',@LeaseholdImprovementsMemberAD,@DepreciationBasesRD,NULL),
(11010810,@OfficeEquipment,NULL, '11010810', N'Office equipment', N'المعدات المكتبية',@OfficeEquipmentMemberAD,@DepreciationBasesRD,NULL),
(11010820,@OfficeEquipment,NULL, '11010820', N'Computer equipment', N'معدات الحاسوب',@ComputerEquipmentMemberAD,@DepreciationBasesRD,NULL),
(11010830,@OfficeEquipment,NULL, '11010830', N'Communication and network equipment', N'الاتصالات ومعدات الشبكة',@CommunicationAndNetworkEquipmentMemberAD,@DepreciationBasesRD,NULL),
(11010900,@BearerPlants,NULL, '11010900', N'Bearer plants', N'النباتات المثمرة -',@BearerPlantsMemberAD,@DepreciationBasesRD,NULL),
(11011000,@TangibleExplorationAndEvaluationAssets,NULL, '11011000', N'Tangible exploration and evaluation assets', N'أصول الاستكشاف والتقييم الملموسة -',@TangibleExplorationAndEvaluationAssetsMemberAD,@DepreciationBasesRD,NULL),
(11011100,@MiningAssets,NULL, '11011100', N'Mining assets', N'أصول التعدين -',@MiningAssetsMemberAD,@DepreciationBasesRD,NULL),
(11011200,@OilAndGasAssets,NULL, '11011200', N'Oil and gas assets', N'أصول النفط والغاز -',@OilAndGasAssetsMemberAD,@DepreciationBasesRD,NULL),
(11011300,@ConstructionInProgress,NULL, '11011300', N'Construction in progress', N'الإنشاءات قيد الإنجاز (بالمشروع)',@ConstructionInProgressMemberAD,NULL,NULL),
(11011400,@OwneroccupiedPropertyMeasuredUsingInvestmentPropertyFairValueModel,NULL, '11011400', N'Owner-occupied property measured using investment property fair value model -', N'العقارات التي يشغلها مالكوها (قياسها باستخدام نموذج القيمة العادلة) -',@OwneroccupiedPropertyMeasuredUsingInvestmentPropertyFairValueModelMemberAD,@DepreciationBasesRD,NULL),
(11019900,@OtherPropertyPlantAndEquipment,NULL, '11019900', N'Other property, plant and equipment', N'الممتلكات والمصانع والمعدات الأخرى -',@OtherPropertyPlantAndEquipmentMemberAD,@DepreciationBasesRD,NULL),
(11020100,@InvestmentPropertyCompleted,NULL, '11020100', N'Investment property', N'العقارات الاستثمارية المستكملة (بالمشروع)',@InvestmentPropertyCompletedMemberAD,NULL,NULL),
(11020200,@InvestmentPropertyUnderConstructionOrDevelopment,NULL, '11020200', N'Investment property under construction or development', N'عقارات استثمارية قيد الإنشاء أو التطوير (بالمشروع)',@InvestmentPropertyUnderConstructionOrDevelopmentMemberAD,NULL,NULL),
(11030000,@Goodwill,NULL, '11030000', N'Goodwill', N'الشهرة',NULL,NULL,NULL),
(11040100,@BrandNames,NULL, '11040100', N'Brand names', N'أسماء العلامات',@BrandNamesMemberAD,@AmortizationBasesRD,NULL),
(11040200,@IntangibleExplorationAndEvaluationAssets,NULL, '11040200', N'Intangible exploration and evaluation assets', N'أصول الاكتشاف والتقييم غير الملموسة',@IntangibleExplorationAndEvaluationAssetsMemberAD,@AmortizationBasesRD,NULL),
(11040300,@MastheadsAndPublishingTitles,NULL, '11040300', N'Mastheads and publishing titles', N'أسماء الصحف وعناوين النشر',@MastheadsAndPublishingTitlesMemberAD,@AmortizationBasesRD,NULL),
(11040400,@ComputerSoftware,NULL, '11040400', N'Computer software', N'برمجيات الحاسوب',@ComputerSoftwareMemberAD,@AmortizationBasesRD,NULL),
(11040501,@LicencesAndFranchises,NULL, '11040501', N'GSM licences', N'تراخيص GSM',@GSMLicencesMemberAD,@AmortizationBasesRD,NULL),
(11040502,@LicencesAndFranchises,NULL, '11040502', N'UMTS licences', N'تراخيص UMTS',@UMTSLicencesMemberAD,@AmortizationBasesRD,NULL),
(11040503,@LicencesAndFranchises,NULL, '11040503', N'LTE licences', N'تراخيص LTE',@LTELicencesMemberAD,@AmortizationBasesRD,NULL),
(11040504,@LicencesAndFranchises,NULL, '11040504', N'Gaming licences', N'تراخيص الألعاب',@GamingLicencesMemberAD,@AmortizationBasesRD,NULL),
(11040505,@LicencesAndFranchises,NULL, '11040505', N'Franchises', N'الامتيازات',@FranchisesMemberAD,@AmortizationBasesRD,NULL),
(11040601,@CopyrightsPatentsAndOtherIndustrialPropertyRightsServiceAndOperatingRights,NULL, '11040601', N'Airport landing rights', N'حقوق الهبوط في المطار',@AirportLandingRightsMemberAD,@AmortizationBasesRD,NULL),
(11040602,@CopyrightsPatentsAndOtherIndustrialPropertyRightsServiceAndOperatingRights,NULL, '11040602', N'Mining rights', N'حقوق التعدين',@MiningRightsMemberAD,@AmortizationBasesRD,NULL),
(11040603,@CopyrightsPatentsAndOtherIndustrialPropertyRightsServiceAndOperatingRights,NULL, '11040603', N'Broadcasting rights', N'حقوق البث',@BroadcastingRightsMemberAD,@AmortizationBasesRD,NULL),
(11040604,@CopyrightsPatentsAndOtherIndustrialPropertyRightsServiceAndOperatingRights,NULL, '11040604', N'Service concession rights', N'حقوق امتياز الخدمة',@ServiceConcessionRightsMemberAD,@AmortizationBasesRD,NULL),
(11040700,@RecipesFormulaeModelsDesignsAndPrototypes,NULL, '11040700', N'Recipes, formulae, models, designs and prototypes', N'الوصفات والصيغ والنماذج والتصاميم والنماذج',@RecipesFormulaeModelsDesignsAndPrototypesMemberAD,@AmortizationBasesRD,NULL),
(11040800,@IntangibleAssetsUnderDevelopment,NULL, '11040800', N'Intangible assets under development', N'الأصول غير الملموسة قيد التطوير',@IntangibleAssetsUnderDevelopmentMemberAD,NULL,NULL),
(11040900,@OtherIntangibleAssets,NULL, '11040900', N'Other intangible assets', N'أصول غير ملموسة أخرى',@OtherIntangibleAssetsMemberAD,@AmortizationBasesRD,NULL),
(11050100,@InvestmentsInAssociatesAccountedForUsingEquityMethod,NULL, '11050100', N'Investments in associates (eq. method)', N'الاستثمارات في المشاريع المشتركة التي يتم محاسبتها باستخدام طريقة حقوق الملكية',@AssociateAD,NULL,NULL),
(11050200,@InvestmentsInJointVenturesAccountedForUsingEquityMethod,NULL, '11050200', N'Investments in JV (Eq. Method)', N'الاستثمارات في المنشآت الزميلة (طريقة حقوق الملكية)',@JointVentureAD,NULL,NULL),
(11060100,@InvestmentsInSubsidiaries,NULL, '11060100', N'Investments in subsidiaries', N'الاستثمارات في الشركات التابعة',@SubsidiaryAD,NULL,NULL),
(11060200,@InvestmentsInJointVentures,NULL, '11060200', N'Investments in JVs', N'الاستثمارات في المشاريع المشتركة',@JointVentureAD,NULL,NULL),
(11060300,@InvestmentsInAssociates,NULL, '11060300', N'Investments in Associates', N'الاستثمارات في الشركات الزميلة',@AssociateAD,NULL,NULL),
(11070100,@NoncurrentBiologicalAssets,NULL, '11070100', N'Non current living animals', N'الحيوانات الحية غير المتداولة',@FarmAD,@LivingAnimalsMemberRD,NULL),
(11080100,@NoncurrentTradeReceivables,NULL, '11080100', N'Non-current trade receivables -', N'الذمم المدينة التجارية غير المتداولة -',@CustomerAD,NULL,NULL),
(11080200,@NoncurrentReceivablesDueFromRelatedParties,NULL, '11080200', N'Non-current receivables due from related parties -', N'الذمم المدينة غير المتداولة المستحقة من أطراف ذات علاقة -',@CustomerAD,NULL,NULL),
(11080300,@NoncurrentPrepayments,NULL, '11080300', N'Non-current prepayments -', N'دفعات مسبقة غير متداولة -',@SupplierAD,NULL,NULL),
(11080410,@NoncurrentAccruedIncome,NULL, '11080410', N'Non-current accrued income', N'الدخل المستحق غير المتداول',@CustomerAD,NULL,NULL),
(11080450,@NoncurrentAccruedIncome,NULL, '11080450', N'Non-current accrued rental income', N'الإيجار المستحق غير المتداول',@RentalCustomerAD,NULL,NULL),
(11080501,@NoncurrentValueAddedTaxReceivables,NULL, '11080501', N'Non-current value added tax receivables', N'الذمم المدينة لضريبة القيمة المضافة غير المتداولة',@TaxDepartmentAD,NULL,@SupplierAD),
(11080600,@NoncurrentReceivablesFromSaleOfProperties,NULL, '11080600', N'Non-current receivables from sale of properties -', N'الذمم المدينة غير المتداولة من بيع العقارات -',@CustomerAD,NULL,NULL),
(11080700,@NoncurrentReceivablesFromRentalOfProperties,NULL, '11080700', N'Non-current receivables from rental of properties -', N'الذمم المدينة غير المتداولة من إيجار العقارات -',@RentalCustomerAD,NULL,NULL),
(11089901,@OtherNoncurrentReceivables,NULL, '11089901', N'Other non-current receivable (by name)', N'ذمم مدينة أخرى غير متداولة (باسم المدين)',NULL,NULL,NULL),
(11090000,@NoncurrentInventories,NULL, '11090000', N'Non current inventories', N'المخزون غير المتداول',NULL,NULL,NULL),
(11100000,@DeferredTaxAssets,NULL, '11100000', N'Deferred tax assets -', N'أصول الضريبة المؤجلة',NULL,NULL,NULL),
(11120110,@NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition,NULL, '11120110', N'Non-current financial assets at fair value through profit or loss, designated upon initial recogniti', N'الأصول المالية غير المتداولة بالقيمة العادلة من خلال الربح أو الخسارة، التي يتم تحديدها عند الاعتراف',NULL,NULL,NULL),
(11120120,@NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossMeasuredAsSuchInAccordanceWithExemptionForRepurchaseOfOwnFinancialLiabil,NULL, '11120120', N'Non-current financial assets at fair value through profit or loss, measured as such in accordance wi', N'الأصول المالية غير المتداولة بالقيمة العادلة من خلال الربح أو الخسارة ، مقاسة على هذا النحو وفقًا لل',NULL,NULL,NULL),
(11120130,@NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossMeasuredAsSuchInAccordanceWithExemptionForReacquisitionOfOwnEquityInstru,NULL, '11120130', N'Non-current financial assets at fair value through profit or loss, measured as such in accordance wi', N'الموجودات المالية غير المتداولة بالقيمة العادلة من خلال الربح أو الخسارة ، ويتم قياسها على هذا النحو',NULL,NULL,NULL),
(11120140,@NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading,NULL, '11120140', N'Non-current financial assets at fair value through profit or loss, classified as held for trading', N'الأصول المالية غير المتداولة بالقيمة العادلة من خلال الربح أو الخسارة، المصنفة على أنها محتفظ بها لل',NULL,NULL,NULL),
(11120150,@NoncurrentFinancialAssetsAtFairValueThroughProfitOrLossMandatorilyMeasuredAtFairValue,NULL, '11120150', N'Non-current financial assets at fair value through profit or loss, mandatorily measured at fair valu', N'الأصول المالية غير المتداولة بالقيمة العادلة من خلال الربح أو الخسارة، المقاسة إلزاميا بالقيمة العاد',NULL,NULL,NULL),
(11200200,@NoncurrentFinancialAssetsAvailableforsale,NULL, '11200200', N'Non-current financial assets available-for-sale', N'الأصول المالية غير المتداولة المتوفرة برسم البيع',NULL,NULL,NULL),
(11120301,@NoncurrentHeldtomaturityInvestments,NULL, '11120301', N'Government Bond 1', N'السندات الحكومية 1',NULL,NULL,NULL),
(11120410,@NoncurrentLoansAndReceivables,NULL, '11120410', N'Non-current staff loans', N'قروض طويلة الأجل لموظفين',@EmployeeAD,NULL,NULL),
(11120510,@NoncurrentFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome,NULL, '11120510', N'Non-current financial assets measured at fair value through other comprehensive income', N'الأصول المالية غير المتداولة المقاسة بالقيمة العادلة من خلال دخل شامل آخر',NULL,NULL,NULL),
(11120520,@NoncurrentInvestmentsInEquityInstrumentsDesignatedAtFairValueThroughOtherComprehensiveIncome,NULL, '11120520', N'Non-current investments in equity instruments designated at fair value through other comprehensive i', N'الاستثمارات غير المتداولة في أدوات حقوق الملكية المحددة باقليمة العادلة من خلال دخل شامل آخر',NULL,NULL,NULL),
(11120600,@NoncurrentFinancialAssetsAtAmortisedCost,NULL, '11120600', N'Non-current financial assets at amortised cost', N'الأصول المالية غير المتداولة بالتكلفة المطفأة',NULL,NULL,NULL),
(11130000,@OtherNoncurrentNonfinancialAssets,NULL, '11130000', N'Other non-current non-financial assets', N'أصول غير مالية غير متداولة أخرى',NULL,NULL,NULL),
(11140000,@NoncurrentNoncashAssetsPledgedAsCollateralForWhichTransfereeHasRightByContractOrCustomToSellOrRepledgeCollateral,NULL, '11140000', N'Non-current non-cash assets pledged as collateral', N'الأصول غير النقدية وغير المتداولة المرهونة كضمان',NULL,NULL,NULL),
(12010110,@Merchandise,NULL, '12010110', N'Merchandise', N'السلع',@WarehouseAD,@MerchandiseRD,NULL),
(12010120,@CurrentFoodAndBeverage,NULL, '12010120', N'Food and beverage', N'الأطعمة والمشروبات',@WarehouseAD,@CurrentFoodAndBeverageRD,NULL),
(12010130,@CurrentAgriculturalProduce,NULL, '12010130', N'Agricultural produce', N'الإنتاج الزراعي',@WarehouseAD,@CurrentAgriculturalProduceRD,NULL),
(12010140,@FinishedGoods,NULL, '12010140', N'Finished goods', N'السلع الجاهزة',@WarehouseAD,@FinishedGoodsRD,NULL),
(12010150,@PropertyIntendedForSaleInOrdinaryCourseOfBusiness,NULL, '12010150', N'Property intended for sale in ordinary course of business', N'العقارات المقصود بيعها في السياق العادي للأعمال',NULL,@PropertyIntendedForSaleInOrdinaryCourseOfBusinessRD,NULL),
(12010200,@WorkInProgress,NULL, '12010200', N'work in progress', N'الأعمال قيد التنفيذ',@ProductionOrderAD,@WorkInProgressRD,NULL),
(12010310,@RawMaterials,NULL, '12010310', N'raw materials', N'المواد الخام',@WarehouseAD,@RawMaterialsRD,NULL),
(12010320,@ProductionSupplies,NULL, '12010320', N'production supplies', N'مستلزمات الإنتاج',@WarehouseAD,@ProductionSuppliesRD,NULL),
(12010330,@CurrentPackagingAndStorageMaterials,NULL, '12010330', N'packaging and storage materials', N'مواد التعبئة والتغليف والتخزين',@WarehouseAD,@CurrentPackagingAndStorageMaterialsRD,NULL),
(12010340,@SpareParts,NULL, '12010340', N'spare parts', N'قطع الغيار',@WarehouseAD,@SparePartsRD,NULL),
(12010350,@CurrentFuel,NULL, '12010350', N'fuel', N'الوقود',@WarehouseAD,@CurrentFuelRD,NULL),
(12010400,@CurrentInventoriesInTransit,NULL, '12010400', N'inventories in transit', N'المخزون في الطريق',@IncomingShipmentAD,@MerchandiseRD,NULL),
(12019900,@OtherInventories,NULL, '12019900', N'Other inventories', N'مخزون آخر',@WarehouseAD,@OtherInventoriesRD,NULL),
(12020100,@CurrentTradeReceivables,NULL, '12020100', N'Current trade receivables', N'الذمم المدينة االتجارية المتداولة',@CustomerAD,NULL,NULL),
(12020199,@CurrentTradeReceivables,NULL, '12020199', N'ECL Allowance, Current trade receivable', N'مخصص الخسائر الائتمانية المتوقعة ، الذمم المدينة التجارية الحالية',NULL,NULL,NULL),
(12020210,@TradeAndOtherCurrentReceivablesDueFromRelatedParties,NULL, '12020210', N'Current receivables due from related customers', N'الذمم المدينة المتداولة المستحقة من زبائن ذوي علاقة -',@CustomerAD,NULL,NULL),
(12020230,@TradeAndOtherCurrentReceivablesDueFromRelatedParties,NULL, '12020230', N'Current receivables due from related rental customers', N'الذمم المدينة المتداولة المستحقة من مستأجرين ذوي علاقة -',@RentalCustomerAD,NULL,NULL),
(12020260,@TradeAndOtherCurrentReceivablesDueFromRelatedParties,NULL, '12020260', N'Current receivables due from related suppliers', N'الذمم المدينة المتداولة المستحقة من موردين ذوي علاقة -',@SupplierAD,NULL,NULL),
(12020299,@TradeAndOtherCurrentReceivablesDueFromRelatedParties,NULL, '12020299', N'ECL Allowance, Current receivables from related parties', N'مخصص الخسائر الائتمانية المتوقعة ، الذمم المدينة الحالية من الأطراف ذات العلاقة',NULL,NULL,NULL),
(12020310,@CurrentAdvancesToSuppliers,NULL, '12020310', N'Current advances to suppliers', N'دفعات حالية مقدمة للموردين',@SupplierAD,NULL,NULL),
(12020359,@CurrentAdvancesToSuppliers,NULL, '12020359', N'ECL Allowance, supplier advances', N'مخصص خسارة الائتمان المتوقعة، دفعات مقدمة للموردين',NULL,NULL,NULL),
(12020360,@CurrentPrepaidExpenses,NULL, '12020360', N'Current prepaid expenses', N'المصاريف المدفوعة مسبقا الحالية',@SupplierAD,NULL,NULL),
(12020399,@CurrentPrepaidExpenses,NULL, '12020399', N'ECL Allowance, prepaid expenses', N'مخصص خسارة الائتمان المتوقعة، المصاريف المدفوعة مسبقا',NULL,NULL,NULL),
(12020400,@CurrentAccruedIncome,NULL, '12020400', N'Current accrued income', N'الدخل المستحق الحالي',@CustomerAD,NULL,NULL),
(12020499,@CurrentAccruedIncome,NULL, '12020499', N'ECL Allowance, Current accrued income', N'مخصص خسارة الائتمان المتوقعة، الدخل المستحق الحالي',NULL,NULL,NULL),
(12020500,@CurrentBilledNotReceivedFromSuppliersExtension,NULL, '12020500', N'Current billed but not received', N'فواتير بدون استلام سلع أو خدمات',@SupplierAD,NULL,NULL),
(12020601,@CurrentValueAddedTaxReceivables,NULL, '12020601', N'Current value added tax receivables', N'الذمم المدينة لضريبة القيمة المضافة الحالية',@TaxDepartmentAD,NULL,@SupplierAD),
(12020700,@CurrentReceivablesFromRentalOfProperties,NULL, '12020700', N'Current receivables from rental of properties -', N'الذمم المدينة المتداولة من إيجار العقارات -',@RentalCustomerAD,NULL,NULL),
(12020799,@CurrentReceivablesFromRentalOfProperties,NULL, '12020799', N'ECL Allowance, Rental Receivable', N'مخصص خسارة الائتمان المتوقعة، مستحق الإيجار',NULL,NULL,NULL),
(12029810,@OtherCurrentReceivables,NULL, '12029810', N'LC Provision', N'مخصص خطاب اعتماد',@IncomingShipmentAD,NULL,NULL),
(12029820,@OtherCurrentReceivables,NULL, '12029820', N'Staff Debtors', N'مدينون متداولون موظفون',@EmployeeAD,NULL,NULL),
(12030001,@CurrentTaxAssetsCurrent,NULL, '12030001', N'Withholding tax receivables', N'الذمم المدينة لضريية الخصم',@TaxDepartmentAD,NULL,@CustomerAD),
(12040000,@CurrentBiologicalAssets,NULL, '12040000', N'Living animals flocks', N'الأصول الحية المتداولة',@FarmAD,@LivingAnimalsFlockRD,NULL),
(12050100,@CurrentFinancialAssetsAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition,NULL, '12050100', N'Current financial assets at FVTPL, designated upon initial recognition or subsequently', N'الأصول المالية المتداولة بالقيمة العادلة من خلال الربح أو الخسارة، التي يتم تحديدها عند الاعتراف الم',@EmployeeAD,NULL,NULL),
(12050200,@CurrentFinancialAssetsAtFairValueThroughProfitOrLossMeasuredAsSuchInAccordanceWithExemptionForRepurchaseOfOwnFinancialLiabiliti,NULL, '12050200', N'Current financial assets at FVTPL, measured as such in accordance with exemption for repurchase of o', N'الأصول المالية المتداولة بالقيمة العادلة من خلال الربح أو الخسارة ، مقاسة على هذا النحو وفقًا لإعفاء',@EmployeeAD,NULL,NULL),
(12050300,@CurrentFinancialAssetsAtFairValueThroughProfitOrLossMeasuredAsSuchInAccordanceWithExemptionForReacquisitionOfOwnEquityInstrumen,NULL, '12050300', N'Current financial assets at FVTPL, measured as such in accordance with exemption for reacquisition o', N'الأصول المالية المتداولة بالقيمة العادلة من خلال الربح أو الخسارة ، والتي يتم قياسها على هذا النحو و',@EmployeeAD,NULL,NULL),
(12050400,@CurrentFinancialAssetsAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading,NULL, '12050400', N'Current financial assets at FVTPL, classified as held for trading', N'الأصول المالية المتداولة بالقيمة العادلة من خلال الربح أو الخسارة، المصنفة على أنها محتفظ بها للمتاج',@EmployeeAD,NULL,NULL),
(12050500,@CurrentFinancialAssetsAtFairValueThroughProfitOrLossMandatorilyMeasuredAtFairValue,NULL, '12050500', N'Current financial assets at FVTPL, mandatorily measured at fair value', N'الأصول المالية المتداولة بالقيمة العادلة من خلال الربح أو الخسارة، المقاسة إلزاميا بالقيمة العادلة',@EmployeeAD,NULL,NULL),
(12050600,@CurrentFinancialAssetsAvailableforsale,NULL, '12050600', N'Current financial assets available-for-sale', N'الأصول المالية المتداولة المتوفرة برسم البيع',@EmployeeAD,NULL,NULL),
(12050700,@CurrentHeldtomaturityInvestments,NULL, '12050700', N'Current held-to-maturity investments', N'الاستثمارات المتداولة المحتفظ بها حتى تاريخ الاستحقاق',@EmployeeAD,NULL,NULL),
(12050800,@CurrentLoansAndReceivables,NULL, '12050800', N'Staff loans', N'سلفيات متداولة لموظفين',@EmployeeAD,NULL,NULL),
(12060100,@CurrentFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome,NULL, '12060100', N'Current financial assets measured at FVTOCI', N'الأصول المالية المتداولة بالقيمة العادلة من خلال دخل شامل آخر',NULL,NULL,NULL),
(12060200,@CurrentInvestmentsInEquityInstrumentsDesignatedAtFairValueThroughOtherComprehensiveIncome,NULL, '12060200', N'Current investments in equity instruments designated at FVTOCI', N'الاستثمارات المتداولة في أدوات حقوق الملكية المحددة باقليمة العادلة من خلال دخل شامل آخر',NULL,NULL,NULL),
(12060300,@CurrentFinancialAssetsAtAmortisedCost,NULL, '12060300', N'Current financial assets at amortised cost', N'الأصول المالية المتداولة بالتكلفة المطفأة',NULL,NULL,NULL),
(12060400,@OtherCurrentNonfinancialAssets,NULL, '12060400', N'Other current non-financial assets', N'أصول غير مالية متداولة أخرى',NULL,NULL,NULL),
(12070100,@CashOnHand,NULL, '12070100', N'Cash on hand - Safes', N'النقدية في الصندوق',@CashOnHandAccountAD,NULL,NULL),
(12070200,@CashOnHand,NULL, '12070200', N'Cash on hand - Employees', N'النثريات',@EmployeeAD,NULL,NULL),
(12070300,@BalancesWithBanks,NULL, '12070300', N'Balances with banks', N'الأرصدة لدى البنوك',@BankAccountAD,NULL,NULL),
(12070410,@ShorttermDepositsClassifiedAsCashEquivalents,NULL, '12070410', N'Short-term deposits, classified as cash equivalents', N'الودائع قصيرة الأجل، المصنفة على أنها نقد معادل',NULL,NULL,NULL),
(12070420,@ShorttermInvestmentsClassifiedAsCashEquivalents,NULL, '12070420', N'Short-term investments, classified as cash equivalents', N'الاستثمارات قصيرة الأجل، المصنفة على أنها نقد معادل',NULL,NULL,NULL),
(12070430,@BankingArrangementsClassifiedAsCashEquivalents,NULL, '12070430', N'Other banking arrangements, classified as cash equivalents', N'الترتيبات المصرفية الأخرى، المصنفة على أنها نقد معادل',NULL,NULL,NULL),
(12080100,@OtherCashAndCashEquivalents,NULL, '12080100', N'Checks on hand - Safes', N'الشيكات في الصندوق -',@CashOnHandAccountAD,@ChecksReceivedRD,NULL),
(12090120,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090120', N'Land classified as held for sale', N'الأراضي المصنفة على أنه محتفظ بها برسم البيع -',@LandMemberAD,NULL,NULL),
(12090130,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090130', N'Buildings classified as held for sale', N'المباني المصنفة على أنه محتفظ بها برسم البيع -',@BuildingsMemberAD,NULL,NULL),
(12090140,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090140', N'Machinery classified as held for sale', N'الألات المصنفة على أنه محتفظ بها برسم البيع',@MachineryMemberAD,NULL,NULL),
(12090150,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090150', N'Power generating assets classified as held for sale', N'الأصول مولدة للطاقة المصنفة على أنه محتفظ بها برسم البيع',@PowerGeneratingAssetsMemberAD,NULL,NULL),
(12090160,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090160', N'Aircrafts classified as held for sale', N'الطائرات المصنفة على أنه محتفظ بها برسم البيع',@AircraftMemberAD,NULL,NULL),
(12090170,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090170', N'Motor Vehicles classified as held for sale', N'العربات المصنفة على أنه محتفظ بها برسم البيع',@MotorVehiclesMemberAD,NULL,NULL),
(12090180,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090180', N'Office equipment classified as held for sale', N'المعدات المكتبية المصنفة على أنه محتفظ بها برسم البيع',@OfficeEquipmentMemberAD,NULL,NULL),
(12090190,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForSale,NULL, '12090190', N'Computer equipment classified as held for sale', N'معدات الحاسوب المصنفة على أنه محتفظ بها برسم البيع',@ComputerEquipmentMemberAD,NULL,NULL),
(12090210,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForDistributionToOwners,NULL, '12090210', N'Land classified as held for distribution to owners', N'الأراضي المصنفة على أنه محتفظ بها لتوزيعها على المالكين',@LandMemberAD,NULL,NULL),
(12090220,@NoncurrentAssetsOrDisposalGroupsClassifiedAsHeldForDistributionToOwners,NULL, '12090220', N'Buildings classified as held for distribution to owners', N'المباني المصنفة على أنه محتفظ بها لتوزيعها على المالكين',@BuildingsMemberAD,NULL,NULL),
(20000100,@IssuedCapital,NULL, '20000100', N'Issued capital -', N'رأس المال المصدر',@PartnerAD,NULL,NULL),
(20000200,@RetainedEarnings,NULL, '20000200', N'Retained earnings -', N'الأرباح المستبقاة',NULL,NULL,NULL),
(20000300,@SharePremium,NULL, '20000300', N'Share premium -', N'علاوة إصدار',NULL,NULL,NULL),
(20000400,@TreasuryShares,NULL, '20000400', N'Treasury shares -', N'أسهم الخزينة',NULL,NULL,NULL),
(20000500,@OtherEquityInterest,NULL, '20000500', N'Other equity interest -', N'حصة مالكين أخرى',NULL,NULL,NULL),
(20000601,@RevaluationSurplus,NULL, '20000601', N'Revaluation surplus', N'فائض إعادة التقييم',NULL,NULL,NULL),
(20000602,@ReserveOfExchangeDifferencesOnTranslation,NULL, '20000602', N'Reserve of exchange differences on translation', N'احتياطي فروق الصرف من التحويل',NULL,NULL,NULL),
(20000603,@ReserveOfCashFlowHedges,NULL, '20000603', N'Reserve of cash flow hedges', N'احتياطي تحوطات التدفقات النقدية',NULL,NULL,NULL),
(20000604,@ReserveOfGainsAndLossesOnHedgingInstrumentsThatHedgeInvestmentsInEquityInstruments,NULL, '20000604', N'Reserve of gains and losses on hedging instruments that hedge investments in equity instruments', N'احتياطي الأرباح والخسائر من أدوات التحوط التي تحوط الاستثمارات في أدوات حقوق الملكية',NULL,NULL,NULL),
(20000605,@ReserveOfChangeInValueOfTimeValueOfOptions,NULL, '20000605', N'Reserve of change in value of time value of options', N'احتياطي التغير في القيمة الزمنية للخيارات',NULL,NULL,NULL),
(20000606,@ReserveOfChangeInValueOfForwardElementsOfForwardContracts,NULL, '20000606', N'Reserve of change in value of forward elements of forward contracts', N'احتياطي التغير في قيمة العناصر الآجلة من العقود الآجلة',NULL,NULL,NULL),
(20000607,@ReserveOfChangeInValueOfForeignCurrencyBasisSpreads,NULL, '20000607', N'Reserve of change in value of foreign currency basis spreads', N'احتياطي التغير في قيمة فروقات أسعار العملة الأجنبية',NULL,NULL,NULL),
(20000608,@ReserveOfGainsAndLossesOnFinancialAssetsMeasuredAtFairValueThroughOtherComprehensiveIncome,NULL, '20000608', N'Reserve of gains and losses on financial assets measured at fair value through other comprehensive i', N'احتياطي الأرباح والخسائر من الأصول المالية المقاسة بالقيمة العادلة من خلال دخل شامل آخر',NULL,NULL,NULL),
(20000609,@ReserveOfInsuranceFinanceIncomeExpensesFromInsuranceContractsIssuedExcludedFromProfitOrLossThatWillBeReclassifiedToProfitOrLoss,NULL, '20000609', N'Reserve of insurance finance income (expenses) from insurance contracts issued excluded from profit ', N'احتياطي للدخل التأمين المالية (النفقات) من عقود التأمين الصادرة استبعادها من الربح أو الخسارة التي س',NULL,NULL,NULL),
(20000610,@ReserveOfInsuranceFinanceIncomeExpensesFromInsuranceContractsIssuedExcludedFromProfitOrLossThatWillNotBeReclassifiedToProfitOrL,NULL, '20000610', N'Reserve of insurance finance income (expenses) from insurance contracts issued excluded from profit ', N'الاحتياطي إيرادات التمويل والتأمين (النفقات) من عقود التأمين الصادرة استبعادها من الربح أو الخسارة ا',NULL,NULL,NULL),
(20000611,@ReserveOfFinanceIncomeExpensesFromReinsuranceContractsHeldExcludedFromProfitOrLoss,NULL, '20000611', N'Reserve of finance income (expenses) from reinsurance contracts held excluded from profit or loss', N'الاحتياطي إيرادات التمويل (النفقات) من عقود إعادة التأمين التي عقدت استبعادها من ربح أو خسارة',NULL,NULL,NULL),
(20000612,@ReserveOfGainsAndLossesOnRemeasuringAvailableforsaleFinancialAssets,NULL, '20000612', N'Reserve of gains and losses on remeasuring available-for-sale financial assets', N'احتياطي الارباح والخسائر الناشئة عن إعادة قياس الأصول المالية المتوافرة برسم البيع',NULL,NULL,NULL),
(20000613,@ReserveOfSharebasedPayments,NULL, '20000613', N'Reserve of share-based payments', N'احتياطي الدفعات على أساس الأسهم',NULL,NULL,NULL),
(20000614,@ReserveOfRemeasurementsOfDefinedBenefitPlans,NULL, '20000614', N'Reserve of remeasurements of defined benefit plans', N'احتياطي إعادة قياس خطط المنافع المحددة',NULL,NULL,NULL),
(20000615,@AmountRecognisedInOtherComprehensiveIncomeAndAccumulatedInEquityRelatingToNoncurrentAssetsOrDisposalGroupsHeldForSale,NULL, '20000615', N'Amount recognised in other comprehensive income and accumulated in equity relating to non-current as', N'المبلغ المعترف به في دخل شامل آخر والمتراكم في حقوق الملكية المتعلقة بأصول غير متداولة أو مجموعات تص',NULL,NULL,NULL),
(20000616,@ReserveOfGainsAndLossesFromInvestmentsInEquityInstruments,NULL, '20000616', N'Reserve of gains and losses from investments in equity instruments', N'احتياطي الأرباح والخسائر من الاستثمارات في أدوات حقوق الملكية',NULL,NULL,NULL),
(20000617,@ReserveOfChangeInFairValueOfFinancialLiabilityAttributableToChangeInCreditRiskOfLiability,NULL, '20000617', N'Reserve of change in fair value of financial liability attributable to change in credit risk of liab', N'احتياطي التغير في القيمة العادلة للالتزام المالي المنسوب إلى التغير في مخاطر ائتمان الالتزام',NULL,NULL,NULL),
(20000618,@ReserveForCatastrophe,NULL, '20000618', N'Reserve for catastrophe', N'احتياطي الكوارث',NULL,NULL,NULL),
(20000619,@ReserveForEqualisation,NULL, '20000619', N'Reserve for equalisation', N'احتياطي التكافؤ',NULL,NULL,NULL),
(20000620,@ReserveOfDiscretionaryParticipationFeatures,NULL, '20000620', N'Reserve of discretionary participation features', N'احتياطي خصائص المشاركة الاختيارية',NULL,NULL,NULL),
(20000621,@ReserveOfEquityComponentOfConvertibleInstruments,NULL, '20000621', N'Reserve of equity component of convertible instruments', N'احتياطي عنصر حقوق الملكية في الأدوات القابلة للتحويل',NULL,NULL,NULL),
(20000622,@CapitalRedemptionReserve,NULL, '20000622', N'Capital redemption reserve', N'احتياطي استرداد رأس المال',NULL,NULL,NULL),
(20000623,@MergerReserve,NULL, '20000623', N'Merger reserve', N'احتياطي الدمج',NULL,NULL,NULL),
(20000624,@StatutoryReserve,NULL, '20000624', N'Statutory reserve', N'احتياطي قانوني',NULL,NULL,NULL),
(31010100,@NoncurrentProvisionsForEmployeeBenefits,NULL, '31010100', N'Non-current provisions for employee benefits -', N'المخصصات غير المتداولة لمنافع الموظفين -',NULL,NULL,NULL),
(31010210,@LongtermWarrantyProvision,NULL, '31010210', N'Non-current warranty provision', N'مخصص الضمان غير المتداول',NULL,NULL,NULL),
(31010211,@LongtermWarrantyProvision,NULL, '31010211', N'Non-current warranty provision (Vehicles)', N'مخصص الضمان غير المتداول (عربات)',NULL,NULL,NULL),
(31010220,@LongtermRestructuringProvision,NULL, '31010220', N'Non-current restructuring provision', N'مخصص إعادة الهيكلة غير المتداول',NULL,NULL,NULL),
(31010230,@LongtermLegalProceedingsProvision,NULL, '31010230', N'Non-current legal proceedings provision', N'المخصص غير المتداول للإجراءات القانونية',NULL,NULL,NULL),
(31010240,@NoncurrentRefundsProvision,NULL, '31010240', N'Non-current refunds provision', N'مخصص الرديات غير المتداول',NULL,NULL,NULL),
(31010250,@LongtermOnerousContractsProvision,NULL, '31010250', N'Non-current onerous contracts provision', N'مخصص العقود المثقلة بالالتزامات غير المتداول',NULL,NULL,NULL),
(31010260,@LongtermProvisionForDecommissioningRestorationAndRehabilitationCosts,NULL, '31010260', N'Non-current provision for decommissioning, restoration and rehabilitation costs', N'المخصص غير المتداول لتكاليف التفكيك والإزالة والتأهيل',NULL,NULL,NULL),
(31010299,@LongtermMiscellaneousOtherProvisions,NULL, '31010299', N'Non-current miscellaneous other provisions', N'مخصصات أخرى متنوعة غير متداولة',NULL,NULL,NULL),
(31020100,@NoncurrentPayablesToTradeSuppliers,NULL, '31020100', N'Non-current trade payables -', N'الذمم الدائنة التجارية غير المتداولة -',NULL,NULL,NULL),
(31020200,@NoncurrentPayablesToRelatedParties,NULL, '31020200', N'Non-current payables to related parties -', N'الذمم الدائنة غير المتداولة إلى أطراف ذات علاقة -',NULL,NULL,NULL),
(31020310,@DeferredIncomeClassifiedAsNoncurrent,NULL, '31020310', N'Deferred income classified as non-current', N'الدخل المؤجل المصنف على أنه غير متداول',NULL,NULL,NULL),
(31020320,@RentDeferredIncomeClassifiedAsNoncurrent,NULL, '31020320', N'Rent deferred income classified as non-current', N'الدخل المؤجل للإيجار المصنف على أنه غير جاري',NULL,NULL,NULL),
(31020330,@AccrualsClassifiedAsNoncurrent,NULL, '31020330', N'Accruals classified as non-current', N'الاستحقاقات المصنفة على أنها غير متداولة',NULL,NULL,NULL),
(31020410,@NoncurrentValueAddedTaxPayables,NULL, '31020410', N'Non-current value added tax payables', N'الذمم الدائنة لضريبة القيمة المضافة غير المتداولة',NULL,NULL,@CustomerAD),
(31020420,@NoncurrentExciseTaxPayables,NULL, '31020420', N'Non-current excise tax payables', N'ذمم ضريبة انتقائية غير متداولة',NULL,NULL,NULL),
(31020500,@NoncurrentRetentionPayables,NULL, '31020500', N'Non-current retention payables', N'الذمم الدائنة غير المتداولة للاستبقاء',NULL,NULL,NULL),
(31020600,@OtherNoncurrentPayables,NULL, '31020600', N'Other non-current payables', N'ذمم دائنة أخرى غير متداولة',NULL,NULL,NULL),
(31030000,@DeferredTaxLiabilities,NULL, '31030000', N'Deferred tax liabilities', N'التزامات الضريبة المؤجلة',NULL,NULL,NULL),
(31040000,@CurrentTaxLiabilitiesNoncurrent,NULL, '31040000', N'Current tax liabilities, non-current', N'الالتزامات الضريبية المتداولة، غير متداولة',NULL,NULL,NULL),
(31050101,@NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading,NULL, '31050101', N'Non-current financial liability #1 at FVTPL, classified as held for trading', N'الالتزامات المالية غير المتداولة 1 بالقيمة العادلة من خلال الربح أو الخسارة، وتصنف على أنها محتفظ به',NULL,NULL,NULL),
(31050102,@NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading,NULL, '31050102', N'Non-current financial liability #2 at FVTPL, classified as held for trading', N'الالتزامات المالية غير المتداولة 2 بالقيمة العادلة من خلال الربح أو الخسارة، وتصنف على أنها محتفظ به',NULL,NULL,NULL),
(31050201,@NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition,NULL, '31050201', N'Non-current financial liability #1 at FVTPL, designated upon initial recognition or subsequently', N'الالتزامات المالية غير المتداولة 1 بالقيمة العادلة من خلال الربح أو الخسارة، مصنفة عند التحقق المبدئ',NULL,NULL,NULL),
(31050202,@NoncurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition,NULL, '31050202', N'Non-current financial liability #2 at FVTPL, designated upon initial recognition or subsequently', N'الالتزامات المالية غير المتداولة 2 بالقيمة العادلة من خلال الربح أو الخسارة، مصنفة عند التحقق المبدئ',NULL,NULL,NULL),
(31050301,@NoncurrentFinancialLiabilitiesAtAmortisedCost,NULL, '31050301', N'Non-current financial liability 1 at amortised cost', N'الالتزامات المالية غير المتداولة 1 بالتكلفة المطفأة',NULL,NULL,NULL),
(31050302,@NoncurrentFinancialLiabilitiesAtAmortisedCost,NULL, '31050302', N'Non-current financial liability 2 at amortised cost', N'الالتزامات المالية غير المتداولة 2 بالتكلفة المطفأة',NULL,NULL,NULL),
(31060000,@OtherNoncurrentNonfinancialLiabilities,NULL, '31060000', N'Other non-current non-financial liabilities', N'التزامات غير مالية غير متداولة أخرى',NULL,NULL,NULL),
(32010100,@CurrentProvisionsForEmployeeBenefits,NULL, '32010100', N'Current provisions for employee benefits', N'المخصصات المتداولة لمنافع الموظفين -',NULL,NULL,NULL),
(32010210,@ShorttermWarrantyProvision,NULL, '32010210', N'Current warranty provision', N'مخصص الضمان المتداول',@CustomerAD,NULL,NULL),
(32010220,@ShorttermRestructuringProvision,NULL, '32010220', N'Current restructuring provision', N'مخصص إعادة الهيكلة المتداول',NULL,NULL,NULL),
(32010230,@ShorttermLegalProceedingsProvision,NULL, '32010230', N'Current legal proceedings provision', N'مخصص الإجراءات القانونية الحالي',NULL,NULL,NULL),
(32010240,@CurrentRefundsProvision,NULL, '32010240', N'Current refunds provision', N'مخصص الرديات المتداول',NULL,NULL,NULL),
(32010250,@ShorttermOnerousContractsProvision,NULL, '32010250', N'Current onerous contracts provision', N'المخصص المتداول للعقود المثقلة بالالتزامات',NULL,NULL,NULL),
(32010260,@ShorttermProvisionForDecommissioningRestorationAndRehabilitationCosts,NULL, '32010260', N'Current provision for decommissioning, restoration and rehabilitation costs', N'المخصص المتداول لتكاليف الإزالة والترميم وإعادة التأهيل',NULL,NULL,NULL),
(32010270,@ShorttermMiscellaneousOtherProvisions,NULL, '32010270', N'Current miscellaneous other provisions', N'مخصصات أخرى متنوعة حالية',NULL,NULL,NULL),
(32020100,@TradeAndOtherCurrentPayablesToTradeSuppliers,NULL, '32020100', N'Current trade payables', N'الذمم الدائنة االتجارية المتداولة',@SupplierAD,NULL,NULL),
(32020200,@TradeAndOtherCurrentPayablesToRelatedParties,NULL, '32020200', N'Current payables to related parties', N'الذمم الدائنة المتداولة - أطراف ذات علاقة',NULL,NULL,NULL),
(32020310,@DeferredIncomeClassifiedAsCurrent,NULL, '32020310', N'Current deferred income', N'الدخل المؤجل المتداول',NULL,NULL,NULL),
(32020320,@RentDeferredIncomeClassifiedAsCurrent,NULL, '32020320', N'Current rent deferred income', N'دخل الإيجار المؤجل الجاري',@RentalCustomerAD,NULL,NULL),
(32020410,@AccrualsClassifiedAsCurrent,NULL, '32020410', N'Accrued expenses', N'الاستحقاقات المتداولة',@SupplierAD,NULL,NULL),
(32020490,@ShorttermEmployeeBenefitsAccruals,NULL, '32020490', N'Short-term employee benefits accruals', N'مستحقات منافع الموظفين قصيرة الاجل',@EmployeeAD,NULL,NULL),
(32020500,@CurrentAdvancesFromCustomersExtension,NULL, '32020500', N'Collected but not invoiced to trade customers', N'استلام من الزبائن دون إصدار فواتير',@CustomerAD,NULL,NULL),
(32020601,@CurrentValueAddedTaxPayables,NULL, '32020601', N'Current value added tax payables', N'دائنون ضريبة القيمة المضافة',@TaxDepartmentAD,NULL,@CustomerAD),
(32020602,@CurrentExciseTaxPayables,NULL, '32020602', N'Current excise tax payables', N'الذمم الدائنة المتداولة للاستبقاء',@TaxDepartmentAD,NULL,NULL),
(32020603,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020603', N'Current Social Security payables', N'دائنون ضمان اجتماعي',@TaxDepartmentAD,NULL,@EmployeeAD),
(32020604,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020604', N'Current Zakat payables', N'دائنون زكاة',@TaxDepartmentAD,NULL,NULL),
(32020605,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020605', N'Current Employee Income tax payables', N'ضريبة الدخل الدائنة - موظفين',@TaxDepartmentAD,NULL,@EmployeeAD),
(32020606,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020606', N'Current Employee Stamp tax payables', N'ضريبة الدمغة الدائنة - موظفين ',@TaxDepartmentAD,NULL,@EmployeeAD),
(32020607,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020607', N'Provident fund payable', N'الذمم الدائنة المتداولة لصناديق الادخار',@TaxDepartmentAD,NULL,@EmployeeAD),
(32020608,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020608', N'Withholding tax payable', N'ضريبة الخصم المستحقة',@TaxDepartmentAD,NULL,@SupplierAD),
(32020609,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020609', N'Cost sharing payable', N'الذمم الدائنة المتداولة لصناديق التعاون',@TaxDepartmentAD,NULL,@EmployeeAD),
(32020610,@OtherCurrentPayablesOnSocialSecurityAndTaxesOtherThanIncomeTaxExtension,NULL, '32020610', N'Dividend tax payable', N'ضريبة الأرباح المستحقة',@TaxDepartmentAD,NULL,NULL),
(32020700,@CurrentRetentionPayables,NULL, '32020700', N'Current retention payables ', N'الذمم الدائنة الحالية للمبالغ المتحفظ عليها',@SupplierAD,NULL,NULL),
(32029901,@OtherCurrentPayables,NULL, '32029901', N'Other current payables (by name)', N'ذمم دائنة متداولة اخرى (بالاسم)',NULL,NULL,NULL),
(32030001,@CurrentTaxLiabilitiesCurrent,NULL, '32030001', N'Business Profit tax payable', N'ضريبة أرباح الأعمال الدائنة',@TaxDepartmentAD,NULL,NULL),
(32040101,@CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading,NULL, '32040101', N'Current financial liability 1 at FVTPL, classified as held for trading', N'الإلتتزامات المالية الحالية 1 بالقيمة العادلة من خلال الربح أو الخسارة، وتصنف على أنها محتفظ بها للم',NULL,NULL,NULL),
(32040102,@CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossClassifiedAsHeldForTrading,NULL, '32040102', N'Current financial liability 2 at FVTPL, classified as held for trading', N'الإلتتزامات المالية الحالية 2 بالقيمة العادلة من خلال الربح أو الخسارة، وتصنف على أنها محتفظ بها للم',NULL,NULL,NULL),
(32040201,@CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition,NULL, '32040201', N'Current financial liability 1 at FVTPL, designated upon initial recognition or subsequently', N'الإلتتزامات المالية الحالية 2 بالقيمة العادلة من خلال الربح أو الخسارة، مصنفة عند التحقق المبدئي أو ',NULL,NULL,NULL),
(32040202,@CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLossDesignatedUponInitialRecognition,NULL, '32040202', N'Current financial liability 2 at FVTPL, designated upon initial recognition or subsequently', N'الإلتتزامات المالية الحالية 2 بالقيمة العادلة من خلال الربح أو الخسارة، مصنفة عند التحقق المبدئي أو ',NULL,NULL,NULL),
(32040301,@CurrentFinancialLiabilitiesAtAmortisedCost,NULL, '32040301', N'Current financial liability #1 at amortised cost', N'الإلتتزامات المالية الحالية 1 بالتكلفة المطفأة',NULL,NULL,NULL),
(32040302,@CurrentFinancialLiabilitiesAtAmortisedCost,NULL, '32040302', N'Current financial liability #2 at amortised cost', N'الإلتتزامات المالية الحالية 2 بالتكلفة المطفأة',NULL,NULL,NULL),
(32050000,@OtherCurrentNonfinancialLiabilities,NULL, '32050000', N'Other current non-financial liabilities', N'التزامات غير مالية متداولة أخرى',NULL,NULL,NULL),
(32060000,@LiabilitiesIncludedInDisposalGroupsClassifiedAsHeldForSale,NULL, '32060000', N'Liabilities in (held for sale) disposal groups', N'الالتزامات المصنفة على أنه محتفظ بها برسم البيع',NULL,NULL,NULL),
(41010100,@RevenueFromSaleOfGoods,NULL, '41010100', N'Revenue from sales of Merchandise', N'إيرادات بيع السلع',@CustomerAD,@MerchandiseRD,NULL),
(41010131,@RevenueFromSaleOfCopper,NULL, '41010131', N'Revenue from sale of copper', N'إيرادات بيع النحاس',@CustomerAD,NULL,NULL),
(41010132,@RevenueFromSaleOfGold,NULL, '41010132', N'Revenue from sale of gold', N'إيرادات بيع الذهب',@CustomerAD,NULL,NULL),
(41010133,@RevenueFromSaleOfSilver,NULL, '41010133', N'Revenue from sale of silver', N'إيرادات بيع الفضة',@CustomerAD,NULL,NULL),
(41010191,@RevenueFromSaleOfOilAndGasProducts,NULL, '41010191', N'Revenue from sale of oil and gas products', N'إيرادات بيع الغاز والنفط',@CustomerAD,NULL,NULL),
(41010195,@RevenueFromSaleOfCrudeOil,NULL, '41010195', N'Revenue from sale of crude oil', N'إيرادات بيع النفط الخام',@CustomerAD,NULL,NULL),
(41010200,@RevenueFromSaleOfAgriculturalProduce,NULL, '41010200', N'Revenue from sale of agricultural produce', N'إيرادات بيع الإنتاج الزراعي',@CustomerAD,@CurrentAgriculturalProduceRD,NULL),
(41010231,@RevenueFromSaleOfFoodAndBeverage,NULL, '41010231', N'Revenue from sale of food and beverage', N'إيرادات بيع الأطعمة والمشروبات',@CustomerAD,@CurrentFoodAndBeverageRD,NULL),
(41020100,@RevenueFromRenderingOfTelecommunicationServices,NULL, '41020100', N'Revenue from rendering of telecommunication services', N'',NULL,@TelecommunicationServicesRD,NULL),
(41020200,@RevenueFromRenderingOfTransportServices,NULL, '41020200', N'Revenue from rendering of transport services', N'إيرادات تقديم خدمات الاتصالات',NULL,@TransportServicesRD,NULL),
(41020310,@RevenueFromRenderingOfInformationTechnologyMaintenanceAndSupportServices,NULL, '41020310', N'Revenue from IT maint. and supp. serv.', N'إيرادات تقديم خدمات النقل',NULL,@InformationTechnologyMaintenanceAndSupportServicesRD,NULL),
(41020320,@RevenueFromRenderingOfInformationTechnologyConsultingServices,NULL, '41020320', N'Revenue from IT consulting services', N'إيرادات العمليات الفندقية',NULL,@InformationTechnologyConsultingServicesRD,NULL),
(41020410,@RevenueFromHotelOperations,NULL, '41020410', N'Revenue from hotel operations', N'إيرادات تقديم خدمات صيانة ودعم IT',NULL,NULL,NULL),
(41020420,@RevenueFromRoomOccupancyServices,NULL, '41020420', N'Revenue from room occupancy services', N'إيرادات تقديم خدمات استشارات IT',NULL,@RoomOccupancyServicesRD,NULL),
(41020800,@RevenueFromRenderingOfOtherPointOfTimeServicesExtension,NULL, '41020800', N'Revenue from other services', N'إيرادات خدمات أخرى',@CustomerAD,@CustomerOtherPointOfTimeServicesRD,NULL),
(41020910,@RevenueFromRenderingOfOtherPeriodOfTimeServicesExtension,NULL, '41020910', N'Revenue from rental of properties', N'إيرادات الإيجارات',@RentalCustomerAD,@CustomerOtherPeriodOfTimeServicesRD,NULL),
(41020920,@RevenueFromRenderingOfOtherPeriodOfTimeServicesExtension,NULL, '41020920', N'Revenue from software subscriptions', N'إيرادات اشتراكات البرامج',@RentalCustomerAD,@CustomerOtherPeriodOfTimeServicesRD,NULL),
(41031000,@RevenueFromConstructionContracts,NULL, '41031000', N'Revenue from construction contracts', N'إيرادات عقود الإنشاء',NULL,@PerformanceObligationsRD,NULL),
(41041000,@RevenueFromRoyalties,NULL, '41041000', N'Royalty income', N'دخل حقوق الانتفاع',NULL,NULL,NULL),
(41051000,@LicenceFeeIncome,NULL, '41051000', N'Licence fee income', N'دخل رسوم الترخيص',NULL,NULL,NULL),
(41061000,@FranchiseFeeIncome,NULL, '41061000', N'Franchise fee income', N'دخل رسوم الامتياز',NULL,NULL,NULL),
(41071000,@RevenueFromInterest,NULL, '41071000', N'Interest income', N'دخل الفائدة',NULL,NULL,NULL),
(41080101,@RevenueFromDividends,NULL, '41080101', N'Dividend income (by investment)', N'دخل أرباح الأسهم (باسم المساهمة)',NULL,NULL,NULL),
(41990001,@OtherRevenue,NULL, '41990001', N'Revenue from sale of byproducts', N'الإيرادات من بيع المنتجات الثانوية',@WarehouseAD,NULL,NULL),
(42000001,@OtherIncome,NULL, '42000001', N'Sales Cash Overage', N'الفائض النقدي للمبيعات',NULL,NULL,NULL),
(42000002,@OtherIncome,NULL, '42000002', N'Other income', N'دخل آخر',NULL,NULL,NULL),
(43020000,@RawMaterialsAndConsumablesUsed,NULL, '43020000', N'Raw Materials Used', N'المواد الخام المستخدمة',NULL,@RawMaterialsRD,NULL),
(43020001,@RawMaterialsAndConsumablesUsed,NULL, '43020001', N'Production Supplies Used', N'المواد القابلة للاستهلاك المستخدمة',NULL,@ProductionSuppliesRD,NULL),
(43020002,@RawMaterialsAndConsumablesUsed,NULL, '43020002', N'Packaging and Storage Material Used', N'مواد التعبئة والتغليف والتخزين المستخدمة',NULL,@CurrentPackagingAndStorageMaterialsRD,NULL),
(43020010,@FuelExpense,NULL, '43020010', N'Fuel expense - Supplier', N'مصاريف الوقود - عريات',@MotorVehiclesMemberAD,@CurrentFuelRD,@SupplierAD),
(43030100,@CostOfMerchandiseSold,NULL, '43030100', N'Cost of Merchandise sold', N'تكلفة السلع المباعة',NULL,@MerchandiseRD,NULL),
(43030101,@CostOfMerchandiseSold,NULL, '43030101', N'Cost of copper sold', N'تكلفة النحاس المباع',NULL,@MerchandiseRD,NULL),
(43030102,@CostOfMerchandiseSold,NULL, '43030102', N'Cost of gold sold', N'تكلفة الذهب المباع',NULL,@MerchandiseRD,NULL),
(43030103,@CostOfMerchandiseSold,NULL, '43030103', N'Cost of silver sold', N'تكلفة الفضة المباعة',NULL,@MerchandiseRD,NULL),
(43030104,@CostOfMerchandiseSold,NULL, '43030104', N'Cost of oil and gas products sold', N'تكلقة النفط والغاز المباع',NULL,@MerchandiseRD,NULL),
(43030105,@CostOfMerchandiseSold,NULL, '43030105', N'cost of crude oil sold', N'تكلقة النفط الخام المباع',NULL,@MerchandiseRD,NULL),
(43030106,@CostOfMerchandiseSold,NULL, '43030106', N'Cost of agricultural produce sold', N'تكلقة الإنتاج الزراعي المباع',NULL,@CurrentAgriculturalProduceRD,NULL),
(43030107,@CostOfMerchandiseSold,NULL, '43030107', N'Cost of food and beverage sold', N'تكلقة الأطعمة والمشروبات المباعة',NULL,@CurrentFoodAndBeverageRD,NULL),
(43040101,@InsuranceExpense,NULL, '43040101', N'Insurance expense - Shipments', N'مصروف التأمين - شحنات',@IncomingShipmentAD,NULL,@SupplierAD),
(43040102,@InsuranceExpense,NULL, '43040102', N'Insurance expense - Motor Vehicles', N'مصروف التأمين - عربات',@MotorVehiclesMemberAD,NULL,@SupplierAD),
(43040201,@ProfessionalFeesExpense,NULL, '43040201', N'Professional fees expense 1', N'مصروف الرسوم المهنية 1',NULL,NULL,@SupplierAD),
(43040202,@ProfessionalFeesExpense,NULL, '43040202', N'Professional fees expense 2', N'مصروف الرسوم المهنية 2',NULL,NULL,@SupplierAD),
(43040301,@TransportationExpense,NULL, '43040301', N'Transportation expense 1', N'مصروف النقل  - شحنات',@IncomingShipmentAD,NULL,@SupplierAD),
(43040302,@TransportationExpense,NULL, '43040302', N'Transportation expense 2', N'مصروف النقل - إدارية',NULL,NULL,@SupplierAD),
(43040401,@BankAndSimilarCharges,NULL, '43040401', N'Bank and similar charges 1', N'الرسوم البنكية والرسوم المشابهة - شحنات',@IncomingShipmentAD,NULL,@SupplierAD),
(43040402,@BankAndSimilarCharges,NULL, '43040402', N'Bank and similar charges 2', N'الرسوم البنكية والرسوم المشابهة - إدارية وتسويفية',NULL,NULL,@SupplierAD),
(43040501,@TravelExpense,NULL, '43040501', N'Travel expense 1', N'مصروفات السفر 1',NULL,NULL,@SupplierAD),
(43040502,@TravelExpense,NULL, '43040502', N'Travel expense 2', N'مصروفات السفر 1',NULL,NULL,@SupplierAD),
(43040601,@CommunicationExpense,NULL, '43040601', N'Communication expense 1', N'مصروفات الاتصالات 1',NULL,NULL,@SupplierAD),
(43040602,@CommunicationExpense,NULL, '43040602', N'Communication expense 2', N'مصروفات الاتصالات 2',NULL,NULL,@SupplierAD),
(43040701,@UtilitiesExpense,NULL, '43040701', N'Utilities expense 1', N'المصروفات الخدمية 1',NULL,NULL,@SupplierAD),
(43040702,@UtilitiesExpense,NULL, '43040702', N'Utilities expense 2', N'المصروفات الخدمية 2',NULL,NULL,@SupplierAD),
(43040801,@AdvertisingExpense,NULL, '43040801', N'Advertising expense 1', N'مصروفات الدعاية 1',NULL,NULL,@SupplierAD),
(43040802,@AdvertisingExpense,NULL, '43040802', N'Advertising expense 2', N'مصروفات الدعاية 2',NULL,NULL,@SupplierAD),
(43040901,@RentalExpense,NULL, '43040901', N'Rental expense 1', N'مصاريف الإيجار 1',NULL,NULL,@SupplierAD),
(43050101,@WagesAndSalaries,NULL, '43050101', N'Basic salary', N'الراتب الاساسي',@EmployeeAD,@EmployeeBenefitsRD,NULL),
(43050102,@WagesAndSalaries,NULL, '43050102', N'Transportation Allowance', N'بدل النقل',@EmployeeAD,@EmployeeBenefitsRD,NULL),
(43050103,@WagesAndSalaries,NULL, '43050103', N'Hardship Allowance', N'بدل المشقة',@EmployeeAD,@EmployeeBenefitsRD,NULL),
(43050104,@WagesAndSalaries,NULL, '43050104', N'Other Allowance', N'بدلات أخرى',@EmployeeAD,@EmployeeBenefitsRD,NULL),
(43050121,@WagesAndSalaries,NULL, '43050121', N'Overtime', N'أجر إضافي',@EmployeeAD,@OvertimeBenefitsRD,NULL),
(43050131,@WagesAndSalaries,NULL, '43050131', N'Penalties', N'جزاءات',@EmployeeAD,@EmployeeDeductionsRD,NULL),
(43050201,@SocialSecurityContributions,NULL, '43050201', N'Pension contributions', N'مساهمات في صندوق التقاعد',@EmployeeAD,@SocialSecurityBenefitsRD,NULL),
(43050202,@SocialSecurityContributions,NULL, '43050202', N'Contribution 2', N'مساهمات 2',@EmployeeAD,@SocialSecurityBenefitsRD,NULL),
(43050203,@SocialSecurityContributions,NULL, '43050203', N'Contribution 3', N'مساهمات 3',@EmployeeAD,@SocialSecurityBenefitsRD,NULL),
(43050301,@OtherShorttermEmployeeBenefits,NULL, '43050301', N'Short term benefits in Cash', N'منافع قصيرة الأجل نقدية',@EmployeeAD,@EmployeeBenefitsRD,NULL),
(43050351,@OtherShorttermEmployeeBenefits,NULL, '43050351', N'Short term benefits in Kind', N'منافع قصيرة الأجل عينية',@EmployeeAD,@EmployeeBenefitsRD,@SupplierAD),
(43050401,@PostemploymentBenefitExpenseDefinedContributionPlans,NULL, '43050401', N'Post-employment benefit expense, defined contribution plans -', N'مصروف منافع ما بعد التوظيف، خطط المساهمة المحددة -',@EmployeeAD,NULL,NULL),
(43050501,@PostemploymentBenefitExpenseDefinedBenefitPlans,NULL, '43050501', N'Post-employment benefit expense, defined benefit plans -', N'مصروف منافع ما بعد التوظيف، خطط المنافع المحددة-',@EmployeeAD,NULL,NULL),
(43050601,@TerminationBenefitsExpense,NULL, '43050601', N'Termination benefits in cash', N'منافع إنهاء خدمة نقدية',@EmployeeAD,NULL,NULL),
(43050602,@TerminationBenefitsExpense,NULL, '43050602', N'Termination benefits in kind', N'منافع إنهاء خدمة عينية',@EmployeeAD,NULL,@SupplierAD),
(43050701,@OtherLongtermBenefits,NULL, '43050701', N'Other long-term employee benefits in cash', N'منافع الموظفين طويلة الاجل الأخرى نقدية',@EmployeeAD,NULL,NULL),
(43050702,@OtherLongtermBenefits,NULL, '43050702', N'Other long-term employee benefits in kind', N'منافع الموظفين طويلة الاجل الأخرى عينية',@EmployeeAD,NULL,@SupplierAD),
(43059901,@OtherEmployeeExpense,NULL, '43059901', N'Other employee expense 1', N'مصروف آخر للموظفين عينية',@EmployeeAD,NULL,NULL),
(43059902,@OtherEmployeeExpense,NULL, '43059902', N'Other employee expense 2', N'مصروف آخر للموظفين نقدية',@EmployeeAD,NULL,@SupplierAD),
(43060105,@DepreciationExpense,NULL, '43060105', N'Depreciation expense - Land', N'مصروف الاستهلاك - أراضي',@LandMemberAD,@DepreciationBasesRD,@LandMemberAD),
(43060110,@DepreciationExpense,NULL, '43060110', N'Depreciation expense - Buildings', N'مصروف الاستهلاك - مباني',@BuildingsMemberAD,@DepreciationBasesRD,@BuildingsMemberAD),
(43060115,@DepreciationExpense,NULL, '43060115', N'Depreciation expense - Machinery', N'مصروف الاستهلاك - الالات',@MachineryMemberAD,@DepreciationBasesRD,@MachineryMemberAD),
(43060116,@DepreciationExpense,NULL, '43060116', N'Depreciation expense - Power generating assets', N'مصروف الاستهلاك - أصول مولدة للطاقة',@PowerGeneratingAssetsMemberAD,@DepreciationBasesRD,@PowerGeneratingAssetsMemberAD),
(43060130,@DepreciationExpense,NULL, '43060130', N'Depreciation expense - Motor Vehicles', N'مصروف الاستهلاك - العربات',@MotorVehiclesMemberAD,@DepreciationBasesRD,@MotorVehiclesMemberAD),
(43060135,@DepreciationExpense,NULL, '43060135', N'Depreciation expense - Fixtures and fittings', N'مصروف الاستهلاك - التركيبات والتجهيزات',@FixturesAndFittingsMemberAD,@DepreciationBasesRD,@FixturesAndFittingsMemberAD),
(43060136,@DepreciationExpense,NULL, '43060136', N'Depreciation expense - Network infrastructure', N'مصروف الاستهلاك - البنية التحتية للشبكة',@NetworkInfrastructureMemberAD,@DepreciationBasesRD,@NetworkInfrastructureMemberAD),
(43060137,@DepreciationExpense,NULL, '43060137', N'Depreciation expense - Leasehold improvements', N'مصروف الاستهلاك - تحسينات عقارية',@LeaseholdImprovementsMemberAD,@DepreciationBasesRD,@LeaseholdImprovementsMemberAD),
(43060140,@DepreciationExpense,NULL, '43060140', N'Depreciation expense - Office equipment', N'مصروف الاستهلاك - المعدات المكتبية',@OfficeEquipmentMemberAD,@DepreciationBasesRD,@OfficeEquipmentMemberAD),
(43060141,@DepreciationExpense,NULL, '43060141', N'Depreciation expense - Computer equipment', N'مصروف الاستهلاك - معدات الحاسوب',@ComputerEquipmentMemberAD,@DepreciationBasesRD,@ComputerEquipmentMemberAD),
(43060142,@DepreciationExpense,NULL, '43060142', N'Depreciation expense - Communication and network equipment', N'مصروف الاستهلاك - الاتصالات ومعدات الشبكة',@CommunicationAndNetworkEquipmentMemberAD,@DepreciationBasesRD,@CommunicationAndNetworkEquipmentMemberAD),
(43060145,@DepreciationExpense,NULL, '43060145', N'Depreciation expense - Bearer plants', N'مصروف الاستهلاك - النباتات المثمرة',@BearerPlantsMemberAD,@DepreciationBasesRD,@BearerPlantsMemberAD),
(43060150,@DepreciationExpense,NULL, '43060150', N'Depreciation expense - Tangible exploration and evaluation assets', N'مصروف الاستهلاك - أصول الاستكشاف والتقييم الملموسة',@TangibleExplorationAndEvaluationAssetsMemberAD,@DepreciationBasesRD,@TangibleExplorationAndEvaluationAssetsMemberAD),
(43060155,@DepreciationExpense,NULL, '43060155', N'Depreciation expense - Mining assets', N'مصروف الاستهلاك - أصول التعدين',@MiningAssetsMemberAD,@DepreciationBasesRD,@MiningAssetsMemberAD),
(43060160,@DepreciationExpense,NULL, '43060160', N'Depreciation expense - Oil and gas assets', N'مصروف الاستهلاك - أصول النفط والغاز',@OilAndGasAssetsMemberAD,@DepreciationBasesRD,@OilAndGasAssetsMemberAD),
(43060170,@DepreciationExpense,NULL, '43060170', N'Depreciation expense - Owner-occupied property measured using investment property fair value model -', N'مصروف الاستهلاك - العقارات التي يشغلها مالكوها (قياسها باستخدام نموذج القيمة العادلة)',@OwneroccupiedPropertyMeasuredUsingInvestmentPropertyFairValueModelMemberAD,@DepreciationBasesRD,@OwneroccupiedPropertyMeasuredUsingInvestmentPropertyFairValueModelMemberAD),
(43060199,@DepreciationExpense,NULL, '43060199', N'Depreciation expense - Other property, plant and equipment -', N'مصروف الاستهلاك - الممتلكات والمصانع والمعدات الأخرى',@OtherPropertyPlantAndEquipmentMemberAD,@DepreciationBasesRD,@OtherPropertyPlantAndEquipmentMemberAD),
(43060201,@AmortisationExpense,NULL, '43060201', N'Amortisation expense (by intangible asset category)', N'مصروف الإطفاء (حسب تصنيف الأصل غير الملموس)',NULL,@AmortizationBasesRD,NULL),
(43070100,@WritedownsReversalsOfInventories,NULL, '43070100', N'Write-downs (reversals of) of Merchandise', N'عمليات تخفيض قيمة (عكس) البضائع',NULL,@MerchandiseRD,NULL),
(43070110,@WritedownsReversalsOfInventories,NULL, '43070110', N'Write-downs (reversals of) of Raw Materials', N'عمليات تخفيض قيمة (عكس) مواد خام',NULL,@RawMaterialsRD,NULL),
(43070120,@WritedownsReversalsOfInventories,NULL, '43070120', N'Write-downs (reversals of) of Finished Goods', N'عمليات تخفيض قيمة (عكس) منتجات نهائية',NULL,@FinishedGoodsRD,NULL),
(43070200,@WritedownsReversalsOfPropertyPlantAndEquipment,NULL, '43070200', N'Write-downs (reversals of) of Land', N'عمليات تخفيض قيمة (وعكسه) أراضي',NULL,NULL,NULL),
(43070210,@WritedownsReversalsOfPropertyPlantAndEquipment,NULL, '43070210', N'Write-downs (reversals of) of Building', N'عمليات تخفيض قيمة (وعكسه) مباني',NULL,NULL,NULL),
(43070220,@WritedownsReversalsOfPropertyPlantAndEquipment,NULL, '43070220', N'Write-downs (reversals of) of Machinery', N'عمليات تخفيض قيمة (وعكسه) الألات',NULL,NULL,NULL),
(43070300,@ImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLossTradeReceivables,NULL, '43070300', N'Impairment loss (reversal of ) trade receivables', N'خسارة انخفاض (عكس) الذمم المدينة التجارية',NULL,NULL,NULL),
(43070400,@ImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLossLoansAndAdvances,NULL, '43070400', N'Impairment loss (reversal of) loans and advances', N'خسارة انخفاض (عكس) الديون والمدفوعات المقدمة',NULL,NULL,NULL),
(43080000,@IndirectMachineCostControlExtension,NULL, '43080000', N'Indirect machine cost control', N'استهلاك ماكينات تمت رسملته',NULL,NULL,NULL),
(43090100,@TaxExpenseOtherThanIncomeTaxExpense,NULL, '43090100', N'Tax expense other than income tax', N'مصروف ضريبة غير ضريبة الدخل',NULL,NULL,NULL),
(43990101,@OtherExpenseByNature,NULL, '43990101', N'Other expenses 1', N'مصاريف أخرى 1',NULL,NULL,NULL),
(43990102,@OtherExpenseByNature,NULL, '43990102', N'Other expenses 2', N'مصاريف أخرى 2',NULL,NULL,NULL),
(43999200,@ExpenseOfRestructuringActivities,NULL, '43999200', N'Expense of restructuring activities', N'مصروفات إعادة الهيكلة',NULL,NULL,NULL),
(43999300,@DonationsAndSubsidiesExpense,NULL, '43999300', N'Donations and subsidies expense', N'تبرعات ودعم',NULL,NULL,NULL),
(43999301,@DonationsAndSubsidiesExpense,NULL, '43999301', N'Donations to suppliers', N'تبرعات للموردين',@SupplierAD,NULL,NULL),
(43999302,@DonationsAndSubsidiesExpense,NULL, '43999302', N'Donations to customers', N'تبرعات للزبائن',@CustomerAD,NULL,NULL),
(43999303,@DonationsAndSubsidiesExpense,NULL, '43999303', N'Donations to employees', N'تبرعات للموظفين',@EmployeeAD,NULL,NULL),
(43999400,@DirectorsRemunerationExpense,NULL, '43999400', N'Directors'' remuneration expense', N'مكافآت مجلس الإدارة',NULL,NULL,NULL),
(43999990,@ReallocatedExpensesExtension,NULL, '43999990', N'Reallocated expenses', N'مصروفات محملة',NULL,NULL,NULL),
(44000210,@ReallocatedExpensesExtension,NULL, '44000210', N'Gains on disposals of property, plant and equipment', N'الأرباح من التصرف بالممتلكات والمصانع والمعدات',NULL,NULL,NULL),
(44000220,@LossesOnDisposalsOfPropertyPlantAndEquipment,NULL, '44000220', N'Losses on disposals of property, plant and equipment', N'الخسائر من التصرف بالممتلكات والمصانع والمعدات',NULL,NULL,NULL),
(44000310,@GainsOnDisposalsOfInvestmentProperties,NULL, '44000310', N'Gains on disposals of investment properties', N'الأرباح من عمليات التصرف بالعقارات الاستثمارية',NULL,NULL,NULL),
(44000320,@LossesOnDisposalsOfInvestmentProperties,NULL, '44000320', N'Losses on disposals of investment properties', N'الخسائر من عمليات التصرف بالعقارات الاستثمارية',NULL,NULL,NULL),
(44000410,@GainsOnDisposalsOfInvestments,NULL, '44000410', N'Gains on disposals of investments', N'الأرباح من عمليات التصرف بالاستثمارات',NULL,NULL,NULL),
(44000420,@LossesOnDisposalsOfInvestments,NULL, '44000420', N'Losses on disposals of investments', N'الخسائر من التصرف بالاستثمارات',NULL,NULL,NULL),
(44000501,@NetForeignExchangeGain,NULL, '44000501', N'Net foreign exchange gain', N'صافي أرباح الصرف الأجنبي',NULL,NULL,NULL),
(44000502,@NetForeignExchangeLoss,NULL, '44000502', N'Net foreign exchange loss', N'صافي خسائر الصرف الأجنبي',NULL,NULL,NULL),
(44000601,@FinanceCosts,NULL, '44000601', N'Finance costs 1', N'تكاليف التمويل 1',NULL,NULL,NULL),
(44000602,@FinanceCosts,NULL, '44000602', N'Finance costs 2', N'تكاليف التمويل 2',NULL,NULL,NULL),
(52000010,@GainsLossesOnExchangeDifferencesOnTranslationBeforeTax,NULL, '52000010', N'Gains (losses) on exch. diff. on translation, B.T.', N'الأرباح (الخسائر) من فروق الصرف عند التحويل، قبل الضريبة',NULL,NULL,NULL),
(52000020,@ReclassificationAdjustmentsOnExchangeDifferencesOnTranslationBeforeTax,NULL, '52000020', N'Reclassification adjustments on exchange differences on translation, before tax -', N'تعديلات إعادة التصنيف على فروق الصرف عند التحويل، قبل الضريبة',NULL,NULL,NULL),
(61010101,@SupplierPerformanceObligationsAtAPointInTimeControlExtension,NULL, '61010101', N'Receipts at point in time from suppliers control', N'مراقبة الاستلام من الموردين في زمن ما',NULL,NULL,@SupplierAD),
(61020101,@SupplierPerformanceObligationsOverAPeriodOfTimeControlExtension,NULL, '61020101', N'Receipts over period of time from suppliers control', N'مراقبة الاستلام  من الموردين طيلة فترة ما',NULL,NULL,@SupplierAD),
(61010201,@CustomerPerformanceObligationsAtAPointInTimeControlExtension,NULL, '61010201', N'Issues at point in time to customers control', N'مراقبة تسليم السلع/الخدمات إلى الزبائن في زمن ما',NULL,NULL,@CustomerAD),
(61020201,@CustomerPerformanceObligationsOverAPeriodOfTimeControlExtension,NULL, '61020201', N'Issues over period of time to customers control', N'مراقبة تسليم السلع/الخدمات إلى الزبائن فترة ما',NULL,NULL,@CustomerAD),
(62010101,@SupplierPaymentControlExtension,NULL, '62010101', N'Suppliers payments control', N'مراقبة دفعيات الموردين',NULL,NULL,@SupplierAD),
(62010201,@CustomerPaymentControlExtension,NULL, '62010201', N'Customers payments control', N'مراقبة دفعيات الزبائن',NULL,NULL,@CustomerAD),
(62010301,@EmployeePaymentControlExtension,NULL, '62010301', N'Employees payments control', N'مراقبة دفعيات الموظفين',NULL,NULL,@EmployeeAD),
(62010901,@OtherPaymentControlExtension,NULL, '62010901', N'Creditors payments control', N'مراقبة دفعيات دائنين',NULL,NULL,@CreditorAD),
(62010902,@OtherPaymentControlExtension,NULL, '62010902', N'Debtors payments control', N'مراقبة دفعيات مدينين',NULL,NULL,@DebtorAD),
(62010903,@OtherPaymentControlExtension,NULL, '62010903', N'Gov. payments control', N'مراقبة دفعيات حكوميين',NULL,NULL,@TaxDepartmentAD),
(62010909,@OtherPaymentControlExtension,NULL, '62010909', N'Others payments control', N'مراقبة دفعيات آخرين',NULL,NULL,@OtherAD),
(71000110,@GuaranteesExtension,NULL, '71000110', N'Checks Guarantee - Employees', N'شيكات ضمان - موظفين',@CashOnHandAccountAD,@ChecksReceivedRD,@EmployeeAD),
(71000120,@GuaranteesExtension,NULL, '71000120', N'Checks Guarantee - Customers', N'شيكات ضمان - زبائن',@CashOnHandAccountAD,@ChecksReceivedRD,@CustomerAD),
(71000200,@GuaranteesExtension,NULL, '71000200', N'Checks Dishonored -', N'شيكات مرتجعة',@CashOnHandAccountAD,@ChecksReceivedRD,NULL),
(72000100,@PayrollExtension,NULL, '72000100', N'Academic Allowances', N'علاوات أكاديمية',NULL,@AcademicDegreesRD,NULL),
(72000110,@PayrollExtension,NULL, '72000110', N'Professional Allowances', N'علاوات مهنية',NULL,@ProfessionalCertificationsRD,NULL),
(72000200,@PayrollExtension,NULL, '72000200', N'Social Allowances', N'علاوات اجتماعية',NULL,@FamilyRelationshipsRD,NULL),
(72000220,@PayrollExtension,NULL, '72000220', N'Transportation Allowances', N'بدلات ترحيل',NULL,@TransportationMeansRD,NULL),
(72000230,@PayrollExtension,NULL, '72000230', N'Housing Allowances', N'بدلات سكن',NULL,@HousingMeansRD,NULL),
(72000300,@PayrollExtension,NULL, '72000300', N'Job Allowances', N'علاوات وظيفية',NULL,@JobsRD,NULL),
(72000900,@PayrollExtension,NULL, '72000900', N'Disciplinary Deductions', N'خصومات مخالفات',NULL,@BreachesRD,NULL),
(73000000,@HRExtension,NULL, '73000000', N'Paid Leaves', N'إجازات مدفوعة',@EmployeeAD,@LeaveTypesRD,NULL),
(73000100,@HRExtension,NULL, '73000100', N'Academic Data', N'بيانات أكاديمية',@EmployeeAD,@AcademicDegreesRD,@UniversityAD),
(73000110,@HRExtension,NULL, '73000110', N'Professional Data', N'بيانات مهنية',@EmployeeAD,@ProfessionalCertificationsRD,NULL),
(73000200,@HRExtension,NULL, '73000200', N'Social Data', N'بيانات اجتماعية',@EmployeeAD,@FamilyRelationshipsRD,@FamilyMemberAD),
(73000210,@HRExtension,NULL, '73000210', N'Licenses, Permits, Ids Data', N'بيانات الرخص والأذونات والتعريفات',@EmployeeAD,@LicensesPermitsIdsRD,NULL),
(73000220,@HRExtension,NULL, '73000220', N'Transportation Data', N'بيانات ترحيل',@EmployeeAD,@TransportationMeansRD,NULL),
(73000230,@HRExtension,NULL, '73000230', N'Housing Data', N'بيانات السكن',@EmployeeAD,@HousingMeansRD,NULL),
(73000310,@HRExtension,NULL, '73000310', N'Job Data', N'بيانات وظيفية',@EmployeeAD,@JobsRD,NULL),
(73000800,@HRExtension,NULL, '73000800', N'Tasks', N'مهام',@EmployeeAD,@TasksRD,NULL),
(73000900,@HRExtension,NULL, '73000900', N'Disciplinary Data', N'بيانات مخالفات',NULL,@BreachesRD,NULL),
(74000100,@CRMExtension,NULL, '74000100', N'Pre-sale activities', N'أنشطة تسويقية قبل البيع',@ProspectAD,@MarketingActivitiesRD,NULL),
(74000200,@CRMExtension,NULL, '74000200', N'Post sale activities', N'أنشطة تسويقية بعج البيع',@CustomerAD,@MarketingActivitiesRD,NULL),
(75000100,@ProjectsExtension,NULL, '75000100', N'Projects', N'',NULL,NULL,NULL),
(99999999,@MigrationAccountsExtension,NULL, '99999999', N'Balance Migration', N'حساب الترحيل',NULL,NULL,NULL);
UPDATE [dbo].[AccountTypes] SET [IsAssignable] = 1 
WHERE [Id] IN (SELECT [AccountTypeId] FROM @Accounts);

-- INSERT INTO @ValidationErrors
INSERT INTO @ValidationErrors
EXEC [api].[Accounts__Save]
	@Entities = @Accounts,
	@ReturnIds = 0,
	@UserId = @AdminUserId;
	
IF EXISTS (SELECT [Key] FROM @ValidationErrors)
BEGIN
	Print 'Accounts: Error Provisioning'
	SET @ValidationErrorsJson = CAST ((SELECT * FROM @ValidationErrors FOR JSON AUTO) AS NVARCHAR (MAX));
	PRINT (@ValidationErrorsJson)
	GOTO Err_Label;
END;

DELETE FROM @IndexedIds;
INSERT INTO @IndexedIds([Index], [Id]) SELECT ROW_NUMBER() OVER(ORDER BY [Id]), [Id]  FROM dbo.Accounts
WHERE AccountTypeId IN (SELECT [Id] FROM dbo.AccountTypes WHERE [IsActive] = 0)
-- Detailed rental properties reveivable, staff debtors, sundry debtors
OR CODE IN (N'12020701' , N'12050101', N'12050201')
-- Detailed Cash on hand
OR CODE BETWEEN N'12070111' AND N'12070113'
-- Detaild bank account
OR CODE BETWEEN N'12070131' AND N'12070133'
--OR CODE BETWEEN N'12070131' AND N'12070133'

INSERT INTO @ValidationErrors
EXEC [api].[Accounts__Activate]
	@Ids = @IndexedIds,
	@IsActive = 0,
	@UserId = @AdminUserId;
	
IF EXISTS (SELECT [Key] FROM @ValidationErrors)
BEGIN
	Print 'Accounts: Error Deactivating'
	SET @ValidationErrorsJson = CAST ((SELECT * FROM @ValidationErrors FOR JSON AUTO) AS NVARCHAR (MAX));
	PRINT (@ValidationErrorsJson)

	GOTO Err_Label;
END;