-- Users
INSERT INTO dbo.Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]) VALUES
(N'Users',N'Administrator', N'ar', N'المشرف', N'n'),(N'Users',N'Administrator', N'am', N'አስተዳዳሪ', N'n'),(N'Users',N'Administrator', N'cn', N'管理员', N'n');
-- Roles
INSERT INTO dbo.Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]) VALUES
(N'Roles',N'Administrator', N'ar', N'المشرف', N'n'),(N'Roles',N'Administrator', N'am', N'አስተዳዳሪ', N'n'),(N'Roles',N'Administrator', N'cn', N'管理员', N'n'),
(N'Roles',N'Finance Manager', N'ar', N'المدير المالي', N'n'),(N'Roles',N'Finance Manager', N'am', N'የፋይናንስ አስተዳዳሪ', N'n'),(N'Roles',N'Finance Manager', N'cn', N'财务经理', N'n'),
(N'Roles',N'General Manager', N'ar', N'المدير العام', N'n'),(N'Roles',N'General Manager', N'am', N'ሰላም ነው', N'n'),(N'Roles',N'General Manager', N'cn', N'总经理', N'n'),
(N'Roles',N'Reader', N'ar', N'صلاحية قراءة', N'n'),(N'Roles',N'Reader', N'am', N'አንባቢ', N'n'),(N'Roles',N'Reader', N'cn', N'读者', N'n'),
(N'Roles',N'Account Manager', N'ar', N'مدير حساب العملاء', N'n'),(N'Roles',N'Account Manager', N'am', N'የደንበኛ መለያ አቀናባሪ', N'n'),(N'Roles',N'Account Manager', N'cn', N'客户客户经理', N'n'),
(N'Roles',N'Comptroller', N'ar', N'مراقب الحسابات', N'n'),(N'Roles',N'Comptroller', N'am', N'የመለያ ኮምፒተር', N'n'),(N'Roles',N'Comptroller', N'cn', N'帐户主计长', N'n'),
(N'Roles',N'Cashier', N'ar', N'أمين الصندوق', N'n'),(N'Roles',N'Cashier', N'am', N'ገንዘብ ተቀባይ', N'n'),(N'Roles',N'Cashier', N'cn', N'出纳员', N'n'),
(N'Roles',N'Admin. Affairs', N'ar', N'الشؤون الإدارية', N'n'),(N'Roles',N'Admin. Affairs', N'am', N'አስተዳደራዊ ጉዳዮች', N'n'),(N'Roles',N'Admin. Affairs', N'cn', N'政务', N'n'),
(N'Roles',N'Production Manager', N'ar', N'مدير الانتاج', N'n'),(N'Roles',N'Production Manager', N'am', N'የምርት ሥራ አስኪያጅ', N'n'),(N'Roles',N'Production Manager', N'cn', N'产品经理', N'n'),
(N'Roles',N'HR Manager', N'ar', N'مدير الموارد البشرية', N'n'),(N'Roles',N'HR Manager', N'am', N'የሰው ኃይል ሥራ አስኪያጅ', N'n'),(N'Roles',N'HR Manager', N'cn', N'人力资源经理', N'n'),
(N'Roles',N'Sales Manager', N'ar', N'مدير المبيعات', N'n'),(N'Roles',N'Sales Manager', N'am', N'የሽያጭ ሃላፊ', N'n'),(N'Roles',N'Sales Manager', N'cn', N'销售经理', N'n'),
(N'Roles',N'Sales Person', N'ar', N'مندوب مبيعات', N'n'),(N'Roles',N'Sales Person', N'am', N'የሽያጭ ሰው', N'n'),(N'Roles',N'Sales Person', N'cn', N'销售人员', N'n'),
(N'Roles',N'Inventory Custodian', N'ar', N'أمين المخزون', N'n'),(N'Roles',N'Inventory Custodian', N'am', N'ኢን Custስትሜንት ባለሞያ', N'n'),(N'Roles',N'Inventory Custodian', N'cn', N'库存保管人', N'n'),
(N'Roles',N'Public', N'ar', N'صلاحيات عامة', N'n'),(N'Roles',N'Public', N'am', N'ሕዝባዊ', N'n'),(N'Roles',N'Public', N'cn', N'上市', N'n');
-- Lookup Definitions
INSERT INTO dbo.Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]) VALUES
(N'LookupDefinitions',N'IT Manufacturer', N'ar', N'الشركة المصنعة', N's'),(N'LookupDefinitions',N'IT Manufacturer', N'am', N'የአይቲ አምራች', N's'),(N'LookupDefinitions',N'IT Manufacturer', N'cn', N'IT制造商', N's'),(N'LookupDefinitions',N'IT Manufacturers', N'ar', N'مصنعي تكنولوجيا المعلومات', N'p'),(N'LookupDefinitions',N'IT Manufacturers', N'am', N'የአይቲ አምራቾች', N'p'),(N'LookupDefinitions',N'IT Manufacturers', N'cn', N'IT厂商', N'p'),
(N'LookupDefinitions',N'Operating System', N'ar', N'نظام التشغيل', N's'),(N'LookupDefinitions',N'Operating System', N'am', N'የአሰራር ሂደት', N's'),(N'LookupDefinitions',N'Operating System', N'cn', N'操作系统', N's'),(N'LookupDefinitions',N'Operating Systems', N'ar', N'أنظمة التشغيل', N'p'),(N'LookupDefinitions',N'Operating Systems', N'am', N'ስርዓተ ክወናዎች', N'p'),(N'LookupDefinitions',N'Operating Systems', N'cn', N'操作系统', N'p'),
(N'LookupDefinitions',N'Body Color', N'ar', N'لون الجسم', N's'),(N'LookupDefinitions',N'Body Color', N'am', N'የሰውነት ቀለም', N's'),(N'LookupDefinitions',N'Body Color', N'cn', N'机身颜色', N's'),(N'LookupDefinitions',N'Body Colors', N'ar', N'ألوان الجسم', N'p'),(N'LookupDefinitions',N'Body Colors', N'am', N'የሰውነት ቀለሞች', N'p'),(N'LookupDefinitions',N'Body Colors', N'cn', N'车身颜色', N'p'),
(N'LookupDefinitions',N'Vehicle Make', N'ar', N'صناعة المركبات', N's'),(N'LookupDefinitions',N'Vehicle Make', N'am', N'የተሽከርካሪ ስራ', N's'),(N'LookupDefinitions',N'Vehicle Make', N'cn', N'车辆制造', N's'),(N'LookupDefinitions',N'Vehicle Makes', N'ar', N'يجعل السيارة', N'p'),(N'LookupDefinitions',N'Vehicle Makes', N'am', N'የተሽከርካሪ መኪናዎች ያደርጉታል', N'p'),(N'LookupDefinitions',N'Vehicle Makes', N'cn', N'车辆制造', N'p'),
(N'LookupDefinitions',N'Thickness', N'ar', N'سماكة', N's'),(N'LookupDefinitions',N'Thickness', N'am', N'ውፍረት', N's'),(N'LookupDefinitions',N'Thickness', N'cn', N'厚度', N's'),(N'LookupDefinitions',N'Thicknesses', N'ar', N'السماكات', N'p'),(N'LookupDefinitions',N'Thicknesses', N'am', N'ወፍራም', N'p'),(N'LookupDefinitions',N'Thicknesses', N'cn', N'厚度', N'p'),
(N'LookupDefinitions',N'Paper Origin', N'ar', N'أصل الورق', N's'),(N'LookupDefinitions',N'Paper Origin', N'am', N'የወረቀት አመጣጥ', N's'),(N'LookupDefinitions',N'Paper Origin', N'cn', N'纸张来源', N's'),(N'LookupDefinitions',N'Paper Origins', N'ar', N'أصول الورق', N'p'),(N'LookupDefinitions',N'Paper Origins', N'am', N'የወረቀት አመጣጥ', N'p'),(N'LookupDefinitions',N'Paper Origins', N'cn', N'纸张来源', N'p'),
(N'LookupDefinitions',N'Paper Group', N'ar', N'مجموعة الورق', N's'),(N'LookupDefinitions',N'Paper Group', N'am', N'የወረቀት ቡድን', N's'),(N'LookupDefinitions',N'Paper Group', N'cn', N'纸业集团', N's'),(N'LookupDefinitions',N'Paper Groups', N'ar', N'مجموعات الورق', N'p'),(N'LookupDefinitions',N'Paper Groups', N'am', N'የወረቀት ቡድኖች', N'p'),(N'LookupDefinitions',N'Paper Groups', N'cn', N'纸组', N'p'),
(N'LookupDefinitions',N'Paper Type', N'ar', N'نوع الورق', N's'),(N'LookupDefinitions',N'Paper Type', N'am', N'የወረቀት ዓይነት', N's'),(N'LookupDefinitions',N'Paper Type', N'cn', N'纸张类型', N's'),(N'LookupDefinitions',N'Paper Types', N'ar', N'أنواع الورق', N'p'),(N'LookupDefinitions',N'Paper Types', N'am', N'የወረቀት ዓይነቶች', N'p'),(N'LookupDefinitions',N'Paper Types', N'cn', N'纸张类型', N'p');
-- Resource Definitions
INSERT INTO dbo.Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]) VALUES
(N'ResourceDefinitions',N'Property, Plant, Equipment', N'ar', N'عقار - منشأة - آلة', N's'),(N'ResourceDefinitions',N'Property, Plant, Equipment', N'am', N'ሪል እስቴት - መገልገያ - ማሽን', N's'),(N'ResourceDefinitions',N'Property, Plant, Equipment', N'cn', N'房地产-设施-机器', N's'),(N'ResourceDefinitions',N'Property, plant, and equipment', N'ar', N'عقارات، منشآت وآلات', N'p'),(N'ResourceDefinitions',N'Property, plant, and equipment', N'am', N'ሪል እስቴት ፣ ተክል እና መሳሪያ', N'p'),(N'ResourceDefinitions',N'Property, plant, and equipment', N'cn', N'房地产，厂房和设备', N'p'),
(N'ResourceDefinitions',N'Office Equipment', N'ar', N'أداة مكتب', N's'),(N'ResourceDefinitions',N'Office Equipment', N'am', N'የቢሮ መሳሪያ', N's'),(N'ResourceDefinitions',N'Office Equipment', N'cn', N'办公工具', N's'),(N'ResourceDefinitions',N'Office Equipment', N'ar', N'معدات مكتبية', N'p'),(N'ResourceDefinitions',N'Office Equipment', N'am', N'የቢሮ መሣሪያዎች', N'p'),(N'ResourceDefinitions',N'Office Equipment', N'cn', N'办公用品', N'p'),
(N'ResourceDefinitions',N'Computer Equipment', N'ar', N'جهاز كمبيوتر', N's'),(N'ResourceDefinitions',N'Computer Equipment', N'am', N'ፒሲ', N's'),(N'ResourceDefinitions',N'Computer Equipment', N'cn', N'个人电脑', N's'),(N'ResourceDefinitions',N'Computer Equipment', N'ar', N'أجهزة كمبيوتر', N'p'),(N'ResourceDefinitions',N'Computer Equipment', N'am', N'ኮምፒተሮች', N'p'),(N'ResourceDefinitions',N'Computer Equipment', N'cn', N'电脑', N'p'),
(N'ResourceDefinitions',N'Machinery', N'ar', N'آلة', N's'),(N'ResourceDefinitions',N'Machinery', N'am', N'ማሽኖች', N's'),(N'ResourceDefinitions',N'Machinery', N'cn', N'机械', N's'),(N'ResourceDefinitions',N'Machineries', N'ar', N'آليات', N'p'),(N'ResourceDefinitions',N'Machineries', N'am', N'ማሽኖች', N'p'),(N'ResourceDefinitions',N'Machineries', N'cn', N'机械设备', N'p'),
(N'ResourceDefinitions',N'Vehicles', N'ar', N'مركبة', N's'),(N'ResourceDefinitions',N'Vehicles', N'am', N'ተሽከርካሪዎች', N's'),(N'ResourceDefinitions',N'Vehicles', N'cn', N'汽车', N's'),(N'ResourceDefinitions',N'Vehicles', N'ar', N'مركبات', N'p'),(N'ResourceDefinitions',N'Vehicles', N'am', N'ተሽከርካሪዎች', N'p'),(N'ResourceDefinitions',N'Vehicles', N'cn', N'汽车', N'p'),
(N'ResourceDefinitions',N'Building', N'ar', N'مبنى', N's'),(N'ResourceDefinitions',N'Building', N'am', N'ህንፃዎች', N's'),(N'ResourceDefinitions',N'Building', N'cn', N'建筑物', N's'),(N'ResourceDefinitions',N'Buildings', N'ar', N'مباني', N'p'),(N'ResourceDefinitions',N'Buildings', N'am', N'ህንፃዎች', N'p'),(N'ResourceDefinitions',N'Buildings', N'cn', N'建筑物', N'p'),
(N'ResourceDefinitions',N'Investment Property', N'ar', N'عقار استثماري', N's'),(N'ResourceDefinitions',N'Investment Property', N'am', N'የኢንmentስትሜንት ንብረቶች', N's'),(N'ResourceDefinitions',N'Investment Property', N'cn', N'投资物业', N's'),(N'ResourceDefinitions',N'Investment Properties', N'ar', N'عقارات استثمارية', N'p'),(N'ResourceDefinitions',N'Investment Properties', N'am', N'የኢንmentስትሜንት ንብረቶች', N'p'),(N'ResourceDefinitions',N'Investment Properties', N'cn', N'投资物业', N'p'),
(N'ResourceDefinitions',N'Raw Grain', N'ar', N'حب خام', N's'),(N'ResourceDefinitions',N'Raw Grain', N'am', N'ጥሬ እህሎች', N's'),(N'ResourceDefinitions',N'Raw Grain', N'cn', N'原始谷物', N's'),(N'ResourceDefinitions',N'Raw Grains', N'ar', N'حبوب خام', N'p'),(N'ResourceDefinitions',N'Raw Grains', N'am', N'ጥሬ እህሎች', N'p'),(N'ResourceDefinitions',N'Raw Grains', N'cn', N'原始谷物', N'p'),
(N'ResourceDefinitions',N'Cleaned Grain', N'ar', N'حب نظيف', N's'),(N'ResourceDefinitions',N'Cleaned Grain', N'am', N'የተጣራ እህል', N's'),(N'ResourceDefinitions',N'Cleaned Grain', N'cn', N'清洁谷物', N's'),(N'ResourceDefinitions',N'Cleaned Grains', N'ar', N'حبوب نظيفة', N'p'),(N'ResourceDefinitions',N'Cleaned Grains', N'am', N'የተጣራ እህል', N'p'),(N'ResourceDefinitions',N'Cleaned Grains', N'cn', N'清洁谷物', N'p'),
(N'ResourceDefinitions',N'Reject Grain', N'ar', N'مخلف حبوب', N's'),(N'ResourceDefinitions',N'Reject Grain', N'am', N'እህልን ይከልክሉ', N's'),(N'ResourceDefinitions',N'Reject Grain', N'cn', N'拒绝谷物', N's'),(N'ResourceDefinitions',N'Reject Grains', N'ar', N'مخلفات حبوب', N'p'),(N'ResourceDefinitions',N'Reject Grains', N'am', N'እህልን ይከልክሉ', N'p'),(N'ResourceDefinitions',N'Reject Grains', N'cn', N'拒绝谷物', N'p'),
(N'ResourceDefinitions',N'Vehicles Component', N'ar', N'مكون المركبات', N's'),(N'ResourceDefinitions',N'Vehicles Component', N'am', N'የተሽከርካሪዎች ክፍሎች', N's'),(N'ResourceDefinitions',N'Vehicles Component', N'cn', N'车辆零部件', N's'),(N'ResourceDefinitions',N'Vehicles Components', N'ar', N'مكونات مركبات', N'p'),(N'ResourceDefinitions',N'Vehicles Components', N'am', N'የተሽከርካሪዎች ክፍሎች', N'p'),(N'ResourceDefinitions',N'Vehicles Components', N'cn', N'车辆零部件', N'p'),
(N'ResourceDefinitions',N'Assembled Vehicle', N'ar', N'مركبة مجمعة', N's'),(N'ResourceDefinitions',N'Assembled Vehicle', N'am', N'የተሰበሰቡ ተሽከርካሪዎች', N's'),(N'ResourceDefinitions',N'Assembled Vehicle', N'cn', N'组装车', N's'),(N'ResourceDefinitions',N'Assembled Vehicles', N'ar', N'مركبات مجمعة', N'p'),(N'ResourceDefinitions',N'Assembled Vehicles', N'am', N'የተሰበሰቡ ተሽከርካሪዎች', N'p'),(N'ResourceDefinitions',N'Assembled Vehicles', N'cn', N'组装车', N'p'),
(N'ResourceDefinitions',N'Raw Material (Oil Milling)', N'ar', N'المواد الخام (طحن النفط)', N's'),(N'ResourceDefinitions',N'Raw Material (Oil Milling)', N'am', N'ጥሬ እቃዎች (ዘይት ቁፋሮ)', N's'),(N'ResourceDefinitions',N'Raw Material (Oil Milling)', N'cn', N'原料（制油）', N's'),(N'ResourceDefinitions',N'Raw Materials (Oil Milling)', N'ar', N'مواد خام (عصر زيوت)', N'p'),(N'ResourceDefinitions',N'Raw Materials (Oil Milling)', N'am', N'ጥሬ እቃዎች (ዘይት ቁፋሮ)', N'p'),(N'ResourceDefinitions',N'Raw Materials (Oil Milling)', N'cn', N'原料（制油）', N'p'),
(N'ResourceDefinitions',N'Processed Oil (Milling)', N'ar', N'زيت معالج (طحن)', N's'),(N'ResourceDefinitions',N'Processed Oil (Milling)', N'am', N'የተቀቀለ ዘይት (ወፍጮ)', N's'),(N'ResourceDefinitions',N'Processed Oil (Milling)', N'cn', N'成品油（铣削）', N's'),(N'ResourceDefinitions',N'Processed Oil (Milling)', N'ar', N'زيت معصور', N'p'),(N'ResourceDefinitions',N'Processed Oil (Milling)', N'am', N'የተቀቀለ ዘይት (ወፍጮ)', N'p'),(N'ResourceDefinitions',N'Processed Oil (Milling)', N'cn', N'成品油（铣削）', N'p'),
(N'ResourceDefinitions',N'Oil Byproduct', N'ar', N'منتج ثانوي (زيوت)', N's'),(N'ResourceDefinitions',N'Oil Byproduct', N'am', N'የዘይት ፍሬ', N's'),(N'ResourceDefinitions',N'Oil Byproduct', N'cn', N'石油副产品', N's'),(N'ResourceDefinitions',N'Oil Byproducts', N'ar', N'منتجات ثانوية (زيوت)', N'p'),(N'ResourceDefinitions',N'Oil Byproducts', N'am', N'ዘይት ያመርታል', N'p'),(N'ResourceDefinitions',N'Oil Byproducts', N'cn', N'石油副产品', N'p'),
(N'ResourceDefinitions',N'Work in Progress', N'ar', N'إنتاج قيد التنفيذ', N's'),(N'ResourceDefinitions',N'Work in Progress', N'am', N'ገና በሂደት ላይ ያለ ስራ', N's'),(N'ResourceDefinitions',N'Work in Progress', N'cn', N'工作正在进行中', N's'),(N'ResourceDefinitions',N'Work In Progress', N'ar', N'منتجات قيد التنفيذ', N'p'),(N'ResourceDefinitions',N'Work In Progress', N'am', N'ገና በሂደት ላይ ያለ ስራ', N'p'),(N'ResourceDefinitions',N'Work In Progress', N'cn', N'工作正在进行中', N'p'),
(N'ResourceDefinitions',N'Medicine', N'ar', N'دواء', N's'),(N'ResourceDefinitions',N'Medicine', N'am', N'መድሃኒት', N's'),(N'ResourceDefinitions',N'Medicine', N'cn', N'药物', N's'),(N'ResourceDefinitions',N'Medicines', N'ar', N'أدوية', N'p'),(N'ResourceDefinitions',N'Medicines', N'am', N'መድሃኒቶች', N'p'),(N'ResourceDefinitions',N'Medicines', N'cn', N'药物', N'p'),
(N'ResourceDefinitions',N'Construction Material', N'ar', N'مادة بناء', N's'),(N'ResourceDefinitions',N'Construction Material', N'am', N'የግንባታ ቁሳቁሶች', N's'),(N'ResourceDefinitions',N'Construction Material', N'cn', N'建筑材料', N's'),(N'ResourceDefinitions',N'Construction Materials', N'ar', N'مواد بناء', N'p'),(N'ResourceDefinitions',N'Construction Materials', N'am', N'የግንባታ ቁሳቁሶች', N'p'),(N'ResourceDefinitions',N'Construction Materials', N'cn', N'建筑材料', N'p'),
(N'ResourceDefinitions',N'Employee Benefit', N'ar', N'بند موظف', N's'),(N'ResourceDefinitions',N'Employee Benefit', N'am', N'የሰራተኛ ጥቅም', N's'),(N'ResourceDefinitions',N'Employee Benefit', N'cn', N'员工福利', N's'),(N'ResourceDefinitions',N'Employee Benefits', N'ar', N'بنود موظف', N'p'),(N'ResourceDefinitions',N'Employee Benefits', N'am', N'የሰራተኛ ጥቅሞች', N'p'),(N'ResourceDefinitions',N'Employee Benefits', N'cn', N'员工福利', N'p'),
(N'ResourceDefinitions',N'Revenue Service', N'ar', N'خدمة (إيراد)', N's'),(N'ResourceDefinitions',N'Revenue Service', N'am', N'የገቢ አገልግሎት', N's'),(N'ResourceDefinitions',N'Revenue Service', N'cn', N'税收服务', N's'),(N'ResourceDefinitions',N'Revenue Services', N'ar', N'خدمات (إيرادات)', N'p'),(N'ResourceDefinitions',N'Revenue Services', N'am', N'የገቢ አገልግሎቶች', N'p'),(N'ResourceDefinitions',N'Revenue Services', N'cn', N'税收服务', N'p');
-- Contract Definitions
INSERT INTO dbo.Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]) VALUES
(N'ContractDefinitions',N'Creditor', N'ar', N'الدائن', N's'),(N'ContractDefinitions',N'Creditor', N'am', N'አበዳሪ', N's'),(N'ContractDefinitions',N'Creditor', N'cn', N'债权人', N's'),(N'ContractDefinitions',N'Creditors', N'ar', N'الدائنين', N'p'),(N'ContractDefinitions',N'Creditors', N'am', N'አበዳሪዎች', N'p'),(N'ContractDefinitions',N'Creditors', N'cn', N'债权人', N'p'),
(N'ContractDefinitions',N'Debtor', N'ar', N'المدين', N's'),(N'ContractDefinitions',N'Debtor', N'am', N'አበዳሪ', N's'),(N'ContractDefinitions',N'Debtor', N'cn', N'债务人', N's'),(N'ContractDefinitions',N'Debtors', N'ar', N'المدينين', N'p'),(N'ContractDefinitions',N'Debtors', N'am', N'አበዳሪዎች', N'p'),(N'ContractDefinitions',N'Debtors', N'cn', N'债务人', N'p'),
(N'ContractDefinitions',N'Owner', N'ar', N'المالك', N's'),(N'ContractDefinitions',N'Owner', N'am', N'ባለቤት', N's'),(N'ContractDefinitions',N'Owner', N'cn', N'所有者', N's'),(N'ContractDefinitions',N'Owners', N'ar', N'المالكين', N'p'),(N'ContractDefinitions',N'Owners', N'am', N'ባለቤቶች', N'p'),(N'ContractDefinitions',N'Owners', N'cn', N'拥有者', N'p'),
(N'ContractDefinitions',N'Partner', N'ar', N'الشريك', N's'),(N'ContractDefinitions',N'Partner', N'am', N'አጋር', N's'),(N'ContractDefinitions',N'Partner', N'cn', N'伙伴', N's'),(N'ContractDefinitions',N'Partners', N'ar', N'الشركاء', N'p'),(N'ContractDefinitions',N'Partners', N'am', N'አጋሮች', N'p'),(N'ContractDefinitions',N'Partners', N'cn', N'伙伴', N'p'),
(N'ContractDefinitions',N'Supplier', N'ar', N'المورد', N's'),(N'ContractDefinitions',N'Supplier', N'am', N'አቅራቢ', N's'),(N'ContractDefinitions',N'Supplier', N'cn', N'供应商', N's'),(N'ContractDefinitions',N'Suppliers', N'ar', N'الموردين', N'p'),(N'ContractDefinitions',N'Suppliers', N'am', N'አቅራቢዎች', N'p'),(N'ContractDefinitions',N'Suppliers', N'cn', N'供应商', N'p'),
(N'ContractDefinitions',N'Customer', N'ar', N'الزبون', N's'),(N'ContractDefinitions',N'Customer', N'am', N'ደንበኛው', N's'),(N'ContractDefinitions',N'Customer', N'cn', N'顾客', N's'),(N'ContractDefinitions',N'Customers', N'ar', N'الزبائن', N'p'),(N'ContractDefinitions',N'Customers', N'am', N'ደንበኞች', N'p'),(N'ContractDefinitions',N'Customers', N'cn', N'顾客', N'p'),
(N'ContractDefinitions',N'Employee', N'ar', N'الموظف', N's'),(N'ContractDefinitions',N'Employee', N'am', N'ተቀጣሪ', N's'),(N'ContractDefinitions',N'Employee', N'cn', N'雇员', N's'),(N'ContractDefinitions',N'Employees', N'ar', N'الموظفين', N'p'),(N'ContractDefinitions',N'Employees', N'am', N'ሠራተኞች', N'p'),(N'ContractDefinitions',N'Employees', N'cn', N'雇员', N'p'),
(N'ContractDefinitions',N'Bank Account', N'ar', N'حساب البنك', N's'),(N'ContractDefinitions',N'Bank Account', N'am', N'የባንክ ሒሳብ', N's'),(N'ContractDefinitions',N'Bank Account', N'cn', N'银行账户', N's'),(N'ContractDefinitions',N'Bank Accounts', N'ar', N'الحسابات البنكية', N'p'),(N'ContractDefinitions',N'Bank Accounts', N'am', N'የባንክ ሂሳቦች', N'p'),(N'ContractDefinitions',N'Bank Accounts', N'cn', N'银行账户', N'p'),
(N'ContractDefinitions',N'Vault Cash Fund', N'ar', N'خزينة االنقد', N's'),(N'ContractDefinitions',N'Vault Cash Fund', N'am', N'የጥሬ ገንዘብ ሳጥን', N's'),(N'ContractDefinitions',N'Vault Cash Fund', N'cn', N'钱箱', N's'),(N'ContractDefinitions',N'Vault Cash Funds', N'ar', N'خزائن النقد', N'p'),(N'ContractDefinitions',N'Vault Cash Funds', N'am', N'የገንዘብ ሣጥኖች', N'p'),(N'ContractDefinitions',N'Vault Cash Funds', N'cn', N'现金储物柜', N'p'),
(N'ContractDefinitions',N'Petty Cash Fund', N'ar', N'النثرية', N's'),(N'ContractDefinitions',N'Petty Cash Fund', N'am', N'የቤት እንስሳት ገንዘብ ፈንድ', N's'),(N'ContractDefinitions',N'Petty Cash Fund', N'cn', N'小额现金基金', N's'),(N'ContractDefinitions',N'Petty Cash Funds', N'ar', N'النثريات', N'p'),(N'ContractDefinitions',N'Petty Cash Funds', N'am', N'የቤት እንስሳት ጥሬ ገንዘብ', N'p'),(N'ContractDefinitions',N'Petty Cash Funds', N'cn', N'小额现金基金', N'p'),
(N'ContractDefinitions',N'Cash Register', N'ar', N'صندوق المبيعات', N's'),(N'ContractDefinitions',N'Cash Register', N'am', N'ገንዘብ ተቀባይ', N's'),(N'ContractDefinitions',N'Cash Register', N'cn', N'出纳员', N's'),(N'ContractDefinitions',N'Cash Registers', N'ar', N'صناديق المبيعات', N'p'),(N'ContractDefinitions',N'Cash Registers', N'am', N'ገንዘብ ተቀባይ', N'p'),(N'ContractDefinitions',N'Cash Registers', N'cn', N'收银员', N'p'),
(N'ContractDefinitions',N'Warehouse', N'ar', N'المستودع', N's'),(N'ContractDefinitions',N'Warehouse', N'am', N'መጋዘን', N's'),(N'ContractDefinitions',N'Warehouse', N'cn', N'仓库', N's'),(N'ContractDefinitions',N'Warehouses', N'ar', N'المستودعات', N'p'),(N'ContractDefinitions',N'Warehouses', N'am', N'መጋዘኖች', N'p'),(N'ContractDefinitions',N'Warehouses', N'cn', N'货仓', N'p'),
(N'ContractDefinitions',N'Foreign Import', N'ar', N'الاستيراد الخارجي', N's'),(N'ContractDefinitions',N'Foreign Import', N'am', N'የውጭ አስመጪ', N's'),(N'ContractDefinitions',N'Foreign Import', N'cn', N'国外进口', N's'),(N'ContractDefinitions',N'Foreign Imports', N'ar', N'الواردات الأجنبية', N'p'),(N'ContractDefinitions',N'Foreign Imports', N'am', N'የውጭ ማስመጣት', N'p'),(N'ContractDefinitions',N'Foreign Imports', N'cn', N'国外进口', N'p'),
(N'ContractDefinitions',N'Foreign Export', N'ar', N'التصدير الخارجي', N's'),(N'ContractDefinitions',N'Foreign Export', N'am', N'የውጭ መላኪያ', N's'),(N'ContractDefinitions',N'Foreign Export', N'cn', N'对外出口', N's'),(N'ContractDefinitions',N'Foreign Exports', N'ar', N'الصادرات الأجنبية', N'p'),(N'ContractDefinitions',N'Foreign Exports', N'am', N'የውጭ ንግድ', N'p'),(N'ContractDefinitions',N'Foreign Exports', N'cn', N'国外出口', N'p');
-- Currencies
DECLARE @Translations TABLE
(
	[Id]					INT PRIMARY KEY IDENTITY,
	[TableName]				NVARCHAR(50),
	[SourceEnglishWord]		NVARCHAR (100),
	[DestinationCultureId]	NVARCHAR (5),
	[Form]					NCHAR (1)			CHECK([Form] IN (N's', N'p', N'n')),
	--UNIQUE([TableName], [SourceEnglishWord], [DestinationCultureId], [Form]),
	[DestinationWord]		NVARCHAR (100)		NOT NULL
);
INSERT INTO @Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]) VALUES
(N'Currencies',N'AE Dirham', N'ar', N'درهم إ.', N'n'),(N'Currencies',N'AE Dirham', N'am', N'ኤኢ ዲ ደርham', N'n'),(N'Currencies',N'AE Dirham', N'cn', N'阿拉伯联合酋长国迪拉姆', N'n'),(N'Currencies',N'United Arab Emirates Dirham', N'ar', N'درهم إماراتي', N'n'),(N'Currencies',N'United Arab Emirates Dirham', N'am', N'የተባበሩት አረብ ኤሚሬቶች ዲርሀም', N'n'),(N'Currencies',N'United Arab Emirates Dirham', N'cn', N'阿拉伯联合酋长国迪拉姆', N'n'),
(N'Currencies',N'afghani', N'ar', N'أفغاني', N'n'),(N'Currencies',N'afghani', N'am', N'አፍጋኒስታን', N'n'),(N'Currencies',N'afghani', N'cn', N'阿富汗阿富汗尼', N'n'),(N'Currencies',N'Afghan afghani', N'ar', N'أفغاني أفغاني', N'n'),(N'Currencies',N'Afghan afghani', N'am', N'አፍጋኒስታን አፍጋኒ', N'n'),(N'Currencies',N'Afghan afghani', N'cn', N'阿富汗阿富汗尼', N'n'),
(N'Currencies',N'Lek', N'ar', N'لك', N'n'),(N'Currencies',N'Lek', N'am', N'ሌክ', N'n'),(N'Currencies',N'Lek', N'cn', N'阿尔巴尼亚列克', N'n'),(N'Currencies',N'Albanian lek', N'ar', N'الألبانية الألبانية', N'n'),(N'Currencies',N'Albanian lek', N'am', N'የአልባኒያ ሊቅ', N'n'),(N'Currencies',N'Albanian lek', N'cn', N'阿尔巴尼亚列克', N'n'),
(N'Currencies',N'Dram', N'ar', N'دراما', N'n'),(N'Currencies',N'Dram', N'am', N'ድራም', N'n'),(N'Currencies',N'Dram', N'cn', N'亚美尼亚德拉姆', N'n'),(N'Currencies',N'Armenian dram', N'ar', N'الدراما الأرمنية', N'n'),(N'Currencies',N'Armenian dram', N'am', N'የአርሜኒያ ድራማ', N'n'),(N'Currencies',N'Armenian dram', N'cn', N'亚美尼亚德拉姆', N'n'),
(N'Currencies',N'Netherlands Antillean guilder', N'ar', N'جلدر جزر الأنتيل', N'n'),(N'Currencies',N'Netherlands Antillean guilder', N'am', N'ኔዘርላንድስ አንቲልያን ገንቢ', N'n'),(N'Currencies',N'Netherlands Antillean guilder', N'cn', N'荷兰安的列斯盾', N'n'),(N'Currencies',N'Netherlands Antillean guilder', N'ar', N'جلدر جزر الأنتيل', N'n'),(N'Currencies',N'Netherlands Antillean guilder', N'am', N'ኔዘርላንድስ አንቲልያን ገንቢ', N'n'),(N'Currencies',N'Netherlands Antillean guilder', N'cn', N'荷兰安的列斯盾', N'n'),
(N'Currencies',N'Kwanza', N'ar', N'كوانزا', N'n'),(N'Currencies',N'Kwanza', N'am', N'ኩዋንዛ', N'n'),(N'Currencies',N'Kwanza', N'cn', N'安哥拉宽扎', N'n'),(N'Currencies',N'Angolan kwanza', N'ar', N'كوانزا أنغولية', N'n'),(N'Currencies',N'Angolan kwanza', N'am', N'አንጎላን ቶንዛ', N'n'),(N'Currencies',N'Angolan kwanza', N'cn', N'安哥拉宽扎', N'n'),
(N'Currencies',N'Argentine peso', N'ar', N'البيزو الأرجنتيني', N'n'),(N'Currencies',N'Argentine peso', N'am', N'የአርጀንቲና ፔሶ', N'n'),(N'Currencies',N'Argentine peso', N'cn', N'阿根廷比索', N'n'),(N'Currencies',N'Argentine peso', N'ar', N'البيزو الأرجنتيني', N'n'),(N'Currencies',N'Argentine peso', N'am', N'የአርጀንቲና ፔሶ', N'n'),(N'Currencies',N'Argentine peso', N'cn', N'阿根廷比索', N'n'),
(N'Currencies',N'AU Dollar', N'ar', N'دولار استرالي', N'n'),(N'Currencies',N'AU Dollar', N'am', N'የአውሮፓ ዶላር', N'n'),(N'Currencies',N'AU Dollar', N'cn', N'澳元', N'n'),(N'Currencies',N'Australian dollar', N'ar', N'دولار استرالي', N'n'),(N'Currencies',N'Australian dollar', N'am', N'የአውስትራሊያ ዶላር', N'n'),(N'Currencies',N'Australian dollar', N'cn', N'澳元', N'n'),
(N'Currencies',N'Florin', N'ar', N'فلورين', N'n'),(N'Currencies',N'Florin', N'am', N'ፍሎሪን', N'n'),(N'Currencies',N'Florin', N'cn', N'阿鲁巴弗罗林', N'n'),(N'Currencies',N'Aruban florin', N'ar', N'أروبا فلورين', N'n'),(N'Currencies',N'Aruban florin', N'am', N'የአርባባን ወለል', N'n'),(N'Currencies',N'Aruban florin', N'cn', N'阿鲁巴弗罗林', N'n'),
(N'Currencies',N'Azerbaijani manat', N'ar', N'مانات أذربيجاني', N'n'),(N'Currencies',N'Azerbaijani manat', N'am', N'የአዘርባጃኒ መና', N'n'),(N'Currencies',N'Azerbaijani manat', N'cn', N'阿塞拜疆马纳特', N'n'),(N'Currencies',N'Azerbaijani manat', N'ar', N'مانات أذربيجاني', N'n'),(N'Currencies',N'Azerbaijani manat', N'am', N'የአዘርባጃኒ መና', N'n'),(N'Currencies',N'Azerbaijani manat', N'cn', N'阿塞拜疆马纳特', N'n'),
(N'Currencies',N'BH Mark', N'ar', N'مارك ب.ه', N'n'),(N'Currencies',N'BH Mark', N'am', N'BH Mark', N'n'),(N'Currencies',N'BH Mark', N'cn', N'波斯尼亚和黑塞哥维那可兑换商标', N'n'),(N'Currencies',N'Bosnia and Herzegovina convertible mark', N'ar', N'مارك البوسنة و الهرسك قابل للتحويل', N'n'),(N'Currencies',N'Bosnia and Herzegovina convertible mark', N'am', N'ቦስኒያ እና ሄርዘጎቪናቪያ የሚመነዘር ምልክት', N'n'),(N'Currencies',N'Bosnia and Herzegovina convertible mark', N'cn', N'波斯尼亚和黑塞哥维那可兑换商标', N'n'),
(N'Currencies',N'BB Dollar', N'ar', N'دولار بربادوس', N'n'),(N'Currencies',N'BB Dollar', N'am', N'ቢቢ ዶላር', N'n'),(N'Currencies',N'BB Dollar', N'cn', N'巴巴多斯元', N'n'),(N'Currencies',N'Barbados dollar', N'ar', N'دولار بربادوس', N'n'),(N'Currencies',N'Barbados dollar', N'am', N'ባርባዶዶ ዶላር', N'n'),(N'Currencies',N'Barbados dollar', N'cn', N'巴巴多斯元', N'n'),
(N'Currencies',N'Taka', N'ar', N'تاكا', N'n'),(N'Currencies',N'Taka', N'am', N'ታካ', N'n'),(N'Currencies',N'Taka', N'cn', N'孟加拉塔卡', N'n'),(N'Currencies',N'Bangladeshi taka', N'ar', N'تاكا بنجلاديشى', N'n'),(N'Currencies',N'Bangladeshi taka', N'am', N'ባንግላዴሽ ባሻ', N'n'),(N'Currencies',N'Bangladeshi taka', N'cn', N'孟加拉塔卡', N'n'),
(N'Currencies',N'Lev', N'ar', N'ليف', N'n'),(N'Currencies',N'Lev', N'am', N'ዘሌ', N'n'),(N'Currencies',N'Lev', N'cn', N'保加利亚列弗', N'n'),(N'Currencies',N'Bulgarian lev', N'ar', N'ليف بلغاري', N'n'),(N'Currencies',N'Bulgarian lev', N'am', N'ቡልጋሪያኛ ሌቭ', N'n'),(N'Currencies',N'Bulgarian lev', N'cn', N'保加利亚列弗', N'n'),
(N'Currencies',N'BH Dinar', N'ar', N'دينار ب.', N'n'),(N'Currencies',N'BH Dinar', N'am', N'ቢኤን ዲናር', N'n'),(N'Currencies',N'BH Dinar', N'cn', N'巴林第纳尔', N'n'),(N'Currencies',N'Bahraini dinar', N'ar', N'دينار بحريني', N'n'),(N'Currencies',N'Bahraini dinar', N'am', N'ባህራኒ ዲናር', N'n'),(N'Currencies',N'Bahraini dinar', N'cn', N'巴林第纳尔', N'n'),
(N'Currencies',N'Burundian franc', N'ar', N'فرنك بوروندي', N'n'),(N'Currencies',N'Burundian franc', N'am', N'ቡሩንዲ ፍራንክ', N'n'),(N'Currencies',N'Burundian franc', N'cn', N'布隆迪法郎', N'n'),(N'Currencies',N'Burundian franc', N'ar', N'فرنك بوروندي', N'n'),(N'Currencies',N'Burundian franc', N'am', N'ቡሩንዲ ፍራንክ', N'n'),(N'Currencies',N'Burundian franc', N'cn', N'布隆迪法郎', N'n'),
(N'Currencies',N'BM Dollar', N'ar', N'الدولار البرمودي', N'n'),(N'Currencies',N'BM Dollar', N'am', N'ቢኤም ዶላር', N'n'),(N'Currencies',N'BM Dollar', N'cn', N'百慕大元', N'n'),(N'Currencies',N'Bermudian dollar', N'ar', N'الدولار البرمودي', N'n'),(N'Currencies',N'Bermudian dollar', N'am', N'የቤርሜሚያን ዶላር', N'n'),(N'Currencies',N'Bermudian dollar', N'cn', N'百慕大元', N'n'),
(N'Currencies',N'Brunei dollar', N'ar', N'دولار بروناي', N'n'),(N'Currencies',N'Brunei dollar', N'am', N'ብሩኒ ዶላር', N'n'),(N'Currencies',N'Brunei dollar', N'cn', N'文莱元', N'n'),(N'Currencies',N'Brunei dollar', N'ar', N'دولار بروناي', N'n'),(N'Currencies',N'Brunei dollar', N'am', N'ብሩኒ ዶላር', N'n'),(N'Currencies',N'Brunei dollar', N'cn', N'文莱元', N'n'),
(N'Currencies',N'Boliviano', N'ar', N'بوليفيانو', N'n'),(N'Currencies',N'Boliviano', N'am', N'ቦሊቪያኖ', N'n'),(N'Currencies',N'Boliviano', N'cn', N'玻利维亚诺', N'n'),(N'Currencies',N'Boliviano', N'ar', N'بوليفيانو', N'n'),(N'Currencies',N'Boliviano', N'am', N'ቦሊቪያኖ', N'n'),(N'Currencies',N'Boliviano', N'cn', N'玻利维亚诺', N'n'),
(N'Currencies',N'Brazilian real', N'ar', N'ريال برازيلي', N'n'),(N'Currencies',N'Brazilian real', N'am', N'የብራዚል እውነተኛ', N'n'),(N'Currencies',N'Brazilian real', N'cn', N'巴西雷亚尔', N'n'),(N'Currencies',N'Brazilian real', N'ar', N'ريال برازيلي', N'n'),(N'Currencies',N'Brazilian real', N'am', N'የብራዚል እውነተኛ', N'n'),(N'Currencies',N'Brazilian real', N'cn', N'巴西雷亚尔', N'n'),
(N'Currencies',N'BS Dollar', N'ar', N'الدولار البهامي', N'n'),(N'Currencies',N'BS Dollar', N'am', N'ቢ.ኤስ ዶላር', N'n'),(N'Currencies',N'BS Dollar', N'cn', N'巴哈马元', N'n'),(N'Currencies',N'Bahamian dollar', N'ar', N'الدولار البهامي', N'n'),(N'Currencies',N'Bahamian dollar', N'am', N'የባሃሚያን ዶላር', N'n'),(N'Currencies',N'Bahamian dollar', N'cn', N'巴哈马元', N'n'),
(N'Currencies',N'Ngultrum', N'ar', N'نولترم', N'n'),(N'Currencies',N'Ngultrum', N'am', N'Ngultrum', N'n'),(N'Currencies',N'Ngultrum', N'cn', N'不丹努尔古特鲁姆', N'n'),(N'Currencies',N'Bhutanese ngultrum', N'ar', N'نولترم بوتاني', N'n'),(N'Currencies',N'Bhutanese ngultrum', N'am', N'ቡታንዝኛ ጎልጉል', N'n'),(N'Currencies',N'Bhutanese ngultrum', N'cn', N'不丹努尔古特鲁姆', N'n'),
(N'Currencies',N'Pula', N'ar', N'بولا', N'n'),(N'Currencies',N'Pula', N'am', N'Ulaላ', N'n'),(N'Currencies',N'Pula', N'cn', N'博茨瓦纳普拉', N'n'),(N'Currencies',N'Botswana pula', N'ar', N'بوتسوانا بولا', N'n'),(N'Currencies',N'Botswana pula', N'am', N'ቦትስዋና ulaላ', N'n'),(N'Currencies',N'Botswana pula', N'cn', N'博茨瓦纳普拉', N'n'),
(N'Currencies',N'Belarusian ruble', N'ar', N'الروبل البيلاروسي', N'n'),(N'Currencies',N'Belarusian ruble', N'am', N'የቤላሩስ ሩብል', N'n'),(N'Currencies',N'Belarusian ruble', N'cn', N'白俄罗斯卢布', N'n'),(N'Currencies',N'Belarusian ruble', N'ar', N'الروبل البيلاروسي', N'n'),(N'Currencies',N'Belarusian ruble', N'am', N'የቤላሩስ ሩብል', N'n'),(N'Currencies',N'Belarusian ruble', N'cn', N'白俄罗斯卢布', N'n'),
(N'Currencies',N'BZ Dollar', N'ar', N'دولار بليز', N'n'),(N'Currencies',N'BZ Dollar', N'am', N'BZ ዶላር', N'n'),(N'Currencies',N'BZ Dollar', N'cn', N'伯利兹元', N'n'),(N'Currencies',N'Belize dollar', N'ar', N'دولار بليز', N'n'),(N'Currencies',N'Belize dollar', N'am', N'ቤሊዝ ዶላር', N'n'),(N'Currencies',N'Belize dollar', N'cn', N'伯利兹元', N'n'),
(N'Currencies',N'CA Dollar', N'ar', N'دولار ك.', N'n'),(N'Currencies',N'CA Dollar', N'am', N'CA ዶላር', N'n'),(N'Currencies',N'CA Dollar', N'cn', N'加元', N'n'),(N'Currencies',N'Canadian dollar', N'ar', N'الدولار الكندي', N'n'),(N'Currencies',N'Canadian dollar', N'am', N'የካናዳ ዶላር', N'n'),(N'Currencies',N'Canadian dollar', N'cn', N'加元', N'n'),
(N'Currencies',N'Congolese franc', N'ar', N'فرنك كونغولي', N'n'),(N'Currencies',N'Congolese franc', N'am', N'ኮንጎ ፍራንክ', N'n'),(N'Currencies',N'Congolese franc', N'cn', N'刚果法郎', N'n'),(N'Currencies',N'Congolese franc', N'ar', N'فرنك كونغولي', N'n'),(N'Currencies',N'Congolese franc', N'am', N'ኮንጎ ፍራንክ', N'n'),(N'Currencies',N'Congolese franc', N'cn', N'刚果法郎', N'n'),
(N'Currencies',N'Swiss franc', N'ar', N'الفرنك السويسري', N'n'),(N'Currencies',N'Swiss franc', N'am', N'የስዊስ ፍራንክ', N'n'),(N'Currencies',N'Swiss franc', N'cn', N'瑞士法郎', N'n'),(N'Currencies',N'Swiss franc', N'ar', N'الفرنك السويسري', N'n'),(N'Currencies',N'Swiss franc', N'am', N'የስዊስ ፍራንክ', N'n'),(N'Currencies',N'Swiss franc', N'cn', N'瑞士法郎', N'n'),
(N'Currencies',N'Chilean peso', N'ar', N'البيزو التشيلي', N'n'),(N'Currencies',N'Chilean peso', N'am', N'የቺሊ ፔሶ', N'n'),(N'Currencies',N'Chilean peso', N'cn', N'智利比索', N'n'),(N'Currencies',N'Chilean peso', N'ar', N'البيزو التشيلي', N'n'),(N'Currencies',N'Chilean peso', N'am', N'የቺሊ ፔሶ', N'n'),(N'Currencies',N'Chilean peso', N'cn', N'智利比索', N'n'),
(N'Currencies',N'Yuan', N'ar', N'يوان', N'n'),(N'Currencies',N'Yuan', N'am', N'ዩዋን', N'n'),(N'Currencies',N'Yuan', N'cn', N'人民币元', N'n'),(N'Currencies',N'Renminbi (Chinese) yuan', N'ar', N'الرنمينبي (صيني) يوان', N'n'),(N'Currencies',N'Renminbi (Chinese) yuan', N'am', N'ሬንሚቢ (ቻይንኛ) ዩዋን', N'n'),(N'Currencies',N'Renminbi (Chinese) yuan', N'cn', N'人民币元', N'n'),
(N'Currencies',N'Colombian peso', N'ar', N'البيزو الكولومبي', N'n'),(N'Currencies',N'Colombian peso', N'am', N'የኮሎምቢያ ፔሶ', N'n'),(N'Currencies',N'Colombian peso', N'cn', N'哥伦比亚比索', N'n'),(N'Currencies',N'Colombian peso', N'ar', N'البيزو الكولومبي', N'n'),(N'Currencies',N'Colombian peso', N'am', N'የኮሎምቢያ ፔሶ', N'n'),(N'Currencies',N'Colombian peso', N'cn', N'哥伦比亚比索', N'n'),
(N'Currencies',N'Colon', N'ar', N'قولون', N'n'),(N'Currencies',N'Colon', N'am', N'ኮሎን', N'n'),(N'Currencies',N'Colon', N'cn', N'哥斯达黎加结肠', N'n'),(N'Currencies',N'Costa Rican colon', N'ar', N'القولون الكوستاريكي', N'n'),(N'Currencies',N'Costa Rican colon', N'am', N'የኮስታ ሪካ ኮሎን', N'n'),(N'Currencies',N'Costa Rican colon', N'cn', N'哥斯达黎加结肠', N'n'),
(N'Currencies',N'Cuban convertible peso', N'ar', N'بيزو كوبي قابل للتحويل', N'n'),(N'Currencies',N'Cuban convertible peso', N'am', N'የኩባ ሊለወጥ የሚችል ፓሶ', N'n'),(N'Currencies',N'Cuban convertible peso', N'cn', N'古巴可兑换比索', N'n'),(N'Currencies',N'Cuban convertible peso', N'ar', N'بيزو كوبي قابل للتحويل', N'n'),(N'Currencies',N'Cuban convertible peso', N'am', N'የኩባ ሊለወጥ የሚችል ፓሶ', N'n'),(N'Currencies',N'Cuban convertible peso', N'cn', N'古巴可兑换比索', N'n'),
(N'Currencies',N'Cuban peso', N'ar', N'البيزو الكوبي', N'n'),(N'Currencies',N'Cuban peso', N'am', N'የኩባ ፔሶ', N'n'),(N'Currencies',N'Cuban peso', N'cn', N'古巴比索', N'n'),(N'Currencies',N'Cuban peso', N'ar', N'البيزو الكوبي', N'n'),(N'Currencies',N'Cuban peso', N'am', N'የኩባ ፔሶ', N'n'),(N'Currencies',N'Cuban peso', N'cn', N'古巴比索', N'n'),
(N'Currencies',N'Escudo', N'ar', N'اسكودو', N'n'),(N'Currencies',N'Escudo', N'am', N'Escudo', N'n'),(N'Currencies',N'Escudo', N'cn', N'佛得角埃斯库多', N'n'),(N'Currencies',N'Cape Verdean escudo', N'ar', N'اسكودو الرأس الأخضر', N'n'),(N'Currencies',N'Cape Verdean escudo', N'am', N'ኬፕ ቨርዴያን እስኪያዱ', N'n'),(N'Currencies',N'Cape Verdean escudo', N'cn', N'佛得角埃斯库多', N'n'),
(N'Currencies',N'Koruna', N'ar', N'كورونا', N'n'),(N'Currencies',N'Koruna', N'am', N'ኮራና', N'n'),(N'Currencies',N'Koruna', N'cn', N'捷克克朗', N'n'),(N'Currencies',N'Czech koruna', N'ar', N'الكورونا التشيكية', N'n'),(N'Currencies',N'Czech koruna', N'am', N'ቼክ koruna', N'n'),(N'Currencies',N'Czech koruna', N'cn', N'捷克克朗', N'n'),
(N'Currencies',N'Djiboutian franc', N'ar', N'فرنك جيبوتي', N'n'),(N'Currencies',N'Djiboutian franc', N'am', N'የጅቡቲ ፍራንክ', N'n'),(N'Currencies',N'Djiboutian franc', N'cn', N'吉布提法郎', N'n'),(N'Currencies',N'Djiboutian franc', N'ar', N'فرنك جيبوتي', N'n'),(N'Currencies',N'Djiboutian franc', N'am', N'የጅቡቲ ፍራንክ', N'n'),(N'Currencies',N'Djiboutian franc', N'cn', N'吉布提法郎', N'n'),
(N'Currencies',N'Danish krone', N'ar', N'الكرونة الدنماركية', N'n'),(N'Currencies',N'Danish krone', N'am', N'ዳኒሽ ክሮን', N'n'),(N'Currencies',N'Danish krone', N'cn', N'丹麦克朗', N'n'),(N'Currencies',N'Danish krone', N'ar', N'الكرونة الدنماركية', N'n'),(N'Currencies',N'Danish krone', N'am', N'ዳኒሽ ክሮን', N'n'),(N'Currencies',N'Danish krone', N'cn', N'丹麦克朗', N'n'),
(N'Currencies',N'Dominican peso', N'ar', N'البيزو الدومينيكي', N'n'),(N'Currencies',N'Dominican peso', N'am', N'ዶሚኒካን ፔሶ', N'n'),(N'Currencies',N'Dominican peso', N'cn', N'多米尼加比索', N'n'),(N'Currencies',N'Dominican peso', N'ar', N'البيزو الدومينيكي', N'n'),(N'Currencies',N'Dominican peso', N'am', N'ዶሚኒካን ፔሶ', N'n'),(N'Currencies',N'Dominican peso', N'cn', N'多米尼加比索', N'n'),
(N'Currencies',N'Algerian dinar', N'ar', N'الدينار الجزائري', N'n'),(N'Currencies',N'Algerian dinar', N'am', N'የአልጄሪያ ዲናር', N'n'),(N'Currencies',N'Algerian dinar', N'cn', N'阿尔及利亚第纳尔', N'n'),(N'Currencies',N'Algerian dinar', N'ar', N'الدينار الجزائري', N'n'),(N'Currencies',N'Algerian dinar', N'am', N'የአልጄሪያ ዲናር', N'n'),(N'Currencies',N'Algerian dinar', N'cn', N'阿尔及利亚第纳尔', N'n'),
(N'Currencies',N'EG Pound', N'ar', N'الجنيه المصري', N'n'),(N'Currencies',N'EG Pound', N'am', N'EG ፓውንድ', N'n'),(N'Currencies',N'EG Pound', N'cn', N'埃及镑', N'n'),(N'Currencies',N'Egyptian pound', N'ar', N'الجنيه المصري', N'n'),(N'Currencies',N'Egyptian pound', N'am', N'የግብፅ ፓውንድ', N'n'),(N'Currencies',N'Egyptian pound', N'cn', N'埃及镑', N'n'),
(N'Currencies',N'Nakfa', N'ar', N'نقفة', N'n'),(N'Currencies',N'Nakfa', N'am', N'ናፋፋ', N'n'),(N'Currencies',N'Nakfa', N'cn', N'厄立特里亚纳克法', N'n'),(N'Currencies',N'Eritrean nakfa', N'ar', N'نقفة إريترية', N'n'),(N'Currencies',N'Eritrean nakfa', N'am', N'ኤርትራዊ nakfa', N'n'),(N'Currencies',N'Eritrean nakfa', N'cn', N'厄立特里亚纳克法', N'n'),
(N'Currencies',N'Birr', N'ar', N'بر', N'n'),(N'Currencies',N'Birr', N'am', N'ብር', N'n'),(N'Currencies',N'Birr', N'cn', N'埃塞俄比亚比尔', N'n'),(N'Currencies',N'Ethiopian birr', N'ar', N'بر إثيوبي', N'n'),(N'Currencies',N'Ethiopian birr', N'am', N'የኢትዮጵያ ብር', N'n'),(N'Currencies',N'Ethiopian birr', N'cn', N'埃塞俄比亚比尔', N'n'),
(N'Currencies',N'Euro', N'ar', N'يورو', N'n'),(N'Currencies',N'Euro', N'am', N'ዩሮ', N'n'),(N'Currencies',N'Euro', N'cn', N'欧元', N'n'),(N'Currencies',N'Euro', N'ar', N'اليورو', N'n'),(N'Currencies',N'Euro', N'am', N'ዩሮ', N'n'),(N'Currencies',N'Euro', N'cn', N'欧元', N'n'),
(N'Currencies',N'FJ Dollar', N'ar', N'دولار فيجي', N'n'),(N'Currencies',N'FJ Dollar', N'am', N'ኤፍጄ ዶላር', N'n'),(N'Currencies',N'FJ Dollar', N'cn', N'斐济元', N'n'),(N'Currencies',N'Fiji dollar', N'ar', N'دولار فيجي', N'n'),(N'Currencies',N'Fiji dollar', N'am', N'ፊጂ ዶላር', N'n'),(N'Currencies',N'Fiji dollar', N'cn', N'斐济元', N'n'),
(N'Currencies',N'Falkland Islands pound', N'ar', N'جنيه جزر فوكلاند', N'n'),(N'Currencies',N'Falkland Islands pound', N'am', N'የፎልክላንድ ደሴቶች ፓውንድ', N'n'),(N'Currencies',N'Falkland Islands pound', N'cn', N'福克兰群岛磅', N'n'),(N'Currencies',N'Falkland Islands pound', N'ar', N'جنيه جزر فوكلاند', N'n'),(N'Currencies',N'Falkland Islands pound', N'am', N'የፎልክላንድ ደሴቶች ፓውንድ', N'n'),(N'Currencies',N'Falkland Islands pound', N'cn', N'福克兰群岛磅', N'n'),
(N'Currencies',N'Pound sterling', N'ar', N'الجنيه الاسترليني', N'n'),(N'Currencies',N'Pound sterling', N'am', N'ፓውንድ ስታይሊንግ', N'n'),(N'Currencies',N'Pound sterling', N'cn', N'英镑', N'n'),(N'Currencies',N'Pound sterling', N'ar', N'الجنيه الاسترليني', N'n'),(N'Currencies',N'Pound sterling', N'am', N'ፓውንድ ስታይሊንግ', N'n'),(N'Currencies',N'Pound sterling', N'cn', N'英镑', N'n'),
(N'Currencies',N'Lari', N'ar', N'لاري', N'n'),(N'Currencies',N'Lari', N'am', N'ላሪ', N'n'),(N'Currencies',N'Lari', N'cn', N'格鲁吉亚拉里', N'n'),(N'Currencies',N'Georgian lari', N'ar', N'لاري جورجي', N'n'),(N'Currencies',N'Georgian lari', N'am', N'የጆርጂያ ላሪ', N'n'),(N'Currencies',N'Georgian lari', N'cn', N'格鲁吉亚拉里', N'n'),
(N'Currencies',N'Cedi', N'ar', N'سيدي', N'n'),(N'Currencies',N'Cedi', N'am', N'Cedi', N'n'),(N'Currencies',N'Cedi', N'cn', N'加纳塞地', N'n'),(N'Currencies',N'Ghanaian cedi', N'ar', N'سيدي الغاني', N'n'),(N'Currencies',N'Ghanaian cedi', N'am', N'ጋና ካዲ', N'n'),(N'Currencies',N'Ghanaian cedi', N'cn', N'加纳塞地', N'n'),
(N'Currencies',N'Gibraltar pound', N'ar', N'جنيه جبل طارق', N'n'),(N'Currencies',N'Gibraltar pound', N'am', N'ጊብራልታር ፓውንድ', N'n'),(N'Currencies',N'Gibraltar pound', N'cn', N'直布罗陀磅', N'n'),(N'Currencies',N'Gibraltar pound', N'ar', N'جنيه جبل طارق', N'n'),(N'Currencies',N'Gibraltar pound', N'am', N'ጊብራልታር ፓውንድ', N'n'),(N'Currencies',N'Gibraltar pound', N'cn', N'直布罗陀磅', N'n'),
(N'Currencies',N'Dalasi', N'ar', N'دالاسي', N'n'),(N'Currencies',N'Dalasi', N'am', N'ዳላሲ', N'n'),(N'Currencies',N'Dalasi', N'cn', N'冈比亚达拉西', N'n'),(N'Currencies',N'Gambian dalasi', N'ar', N'دالاسي غامبي', N'n'),(N'Currencies',N'Gambian dalasi', N'am', N'ጋምቢያን ዳሊሲ', N'n'),(N'Currencies',N'Gambian dalasi', N'cn', N'冈比亚达拉西', N'n'),
(N'Currencies',N'Guinean franc', N'ar', N'فرنك غيني', N'n'),(N'Currencies',N'Guinean franc', N'am', N'የጊኒ ፍራንክ', N'n'),(N'Currencies',N'Guinean franc', N'cn', N'几内亚法郎', N'n'),(N'Currencies',N'Guinean franc', N'ar', N'فرنك غيني', N'n'),(N'Currencies',N'Guinean franc', N'am', N'የጊኒ ፍራንክ', N'n'),(N'Currencies',N'Guinean franc', N'cn', N'几内亚法郎', N'n'),
(N'Currencies',N'Quetzal', N'ar', N'كوازال', N'n'),(N'Currencies',N'Quetzal', N'am', N'Quetzal', N'n'),(N'Currencies',N'Quetzal', N'cn', N'危地马拉格查尔', N'n'),(N'Currencies',N'Guatemalan quetzal', N'ar', N'كوازال جواتيمالي', N'n'),(N'Currencies',N'Guatemalan quetzal', N'am', N'የጓቲማላን ኳታዘል', N'n'),(N'Currencies',N'Guatemalan quetzal', N'cn', N'危地马拉格查尔', N'n'),
(N'Currencies',N'GY Dollar', N'ar', N'دولار جوياني', N'n'),(N'Currencies',N'GY Dollar', N'am', N'ጂኤ ዶላር', N'n'),(N'Currencies',N'GY Dollar', N'cn', N'圭亚那元', N'n'),(N'Currencies',N'Guyanese dollar', N'ar', N'دولار جوياني', N'n'),(N'Currencies',N'Guyanese dollar', N'am', N'የጊያንኛ ዶላር', N'n'),(N'Currencies',N'Guyanese dollar', N'cn', N'圭亚那元', N'n'),
(N'Currencies',N'HK dollar', N'ar', N'دولار ه.ك.', N'n'),(N'Currencies',N'HK dollar', N'am', N'ኤች. ዶላር', N'n'),(N'Currencies',N'HK dollar', N'cn', N'港元', N'n'),(N'Currencies',N'Hong Kong dollar', N'ar', N'الدولار هونج كونج', N'n'),(N'Currencies',N'Hong Kong dollar', N'am', N'የሆንግ ኮንግ ዶላር', N'n'),(N'Currencies',N'Hong Kong dollar', N'cn', N'港元', N'n'),
(N'Currencies',N'Lempira', N'ar', N'لمبيرا', N'n'),(N'Currencies',N'Lempira', N'am', N'ሎሚራራ', N'n'),(N'Currencies',N'Lempira', N'cn', N'洪都拉斯伦皮拉', N'n'),(N'Currencies',N'Honduran lempira', N'ar', N'لمبيرا هندوراسي', N'n'),(N'Currencies',N'Honduran lempira', N'am', N'የሆንዱራ ሌፓራራ', N'n'),(N'Currencies',N'Honduran lempira', N'cn', N'洪都拉斯伦皮拉', N'n'),
(N'Currencies',N'Kuna', N'ar', N'كونا', N'n'),(N'Currencies',N'Kuna', N'am', N'ኩን', N'n'),(N'Currencies',N'Kuna', N'cn', N'克罗地亚库纳', N'n'),(N'Currencies',N'Croatian kuna', N'ar', N'كونا كرواتي', N'n'),(N'Currencies',N'Croatian kuna', N'am', N'የክሮሺያ ኩን', N'n'),(N'Currencies',N'Croatian kuna', N'cn', N'克罗地亚库纳', N'n'),
(N'Currencies',N'Gourde', N'ar', N'غورد', N'n'),(N'Currencies',N'Gourde', N'am', N'ጉጉር', N'n'),(N'Currencies',N'Gourde', N'cn', N'海地古德', N'n'),(N'Currencies',N'Haitian gourde', N'ar', N'غورد هايتي', N'n'),(N'Currencies',N'Haitian gourde', N'am', N'የሄይቲ ጉጉር', N'n'),(N'Currencies',N'Haitian gourde', N'cn', N'海地古德', N'n'),
(N'Currencies',N'Hungarian forint', N'ar', N'فورنت مجري', N'n'),(N'Currencies',N'Hungarian forint', N'am', N'የሃንጋሪኛ ቅናሽ', N'n'),(N'Currencies',N'Hungarian forint', N'cn', N'匈牙利福林', N'n'),(N'Currencies',N'Hungarian forint', N'ar', N'فورنت مجري', N'n'),(N'Currencies',N'Hungarian forint', N'am', N'የሃንጋሪኛ ቅናሽ', N'n'),(N'Currencies',N'Hungarian forint', N'cn', N'匈牙利福林', N'n'),
(N'Currencies',N'ID Rupiah', N'ar', N'الروبية الاندونيسية', N'n'),(N'Currencies',N'ID Rupiah', N'am', N'የመታወቂያ Rupiah', N'n'),(N'Currencies',N'ID Rupiah', N'cn', N'印尼盾', N'n'),(N'Currencies',N'Indonesian rupiah', N'ar', N'الروبية الاندونيسية', N'n'),(N'Currencies',N'Indonesian rupiah', N'am', N'የኢንዶኔዥያ ሩፒያ', N'n'),(N'Currencies',N'Indonesian rupiah', N'cn', N'印尼盾', N'n'),
(N'Currencies',N'Shekel', N'ar', N'شيكل', N'n'),(N'Currencies',N'Shekel', N'am', N'Kelክ', N'n'),(N'Currencies',N'Shekel', N'cn', N'以色列新谢克尔', N'n'),(N'Currencies',N'Israeli new shekel', N'ar', N'شيكل إسرائيلي جديد', N'n'),(N'Currencies',N'Israeli new shekel', N'am', N'የእስራኤል አዲስ ሰቅል', N'n'),(N'Currencies',N'Israeli new shekel', N'cn', N'以色列新谢克尔', N'n'),
(N'Currencies',N'IN Rupee', N'ar', N'روبية هندية', N'n'),(N'Currencies',N'IN Rupee', N'am', N'ሩፒ ውስጥ', N'n'),(N'Currencies',N'IN Rupee', N'cn', N'印度卢比', N'n'),(N'Currencies',N'Indian rupee', N'ar', N'روبية هندية', N'n'),(N'Currencies',N'Indian rupee', N'am', N'የህንድ ሩፒ', N'n'),(N'Currencies',N'Indian rupee', N'cn', N'印度卢比', N'n'),
(N'Currencies',N'IQ Dinar', N'ar', N'دينار ع', N'n'),(N'Currencies',N'IQ Dinar', N'am', N'አይኬ ዲናር', N'n'),(N'Currencies',N'IQ Dinar', N'cn', N'伊拉克第纳尔', N'n'),(N'Currencies',N'Iraqi dinar', N'ar', N'الدينار العراقي', N'n'),(N'Currencies',N'Iraqi dinar', N'am', N'የኢራቅ ዲናር', N'n'),(N'Currencies',N'Iraqi dinar', N'cn', N'伊拉克第纳尔', N'n'),
(N'Currencies',N'IR Rial', N'ar', N'الريال الإيراني', N'n'),(N'Currencies',N'IR Rial', N'am', N'አይ.አር. ኪራይ', N'n'),(N'Currencies',N'IR Rial', N'cn', N'伊朗里亚尔', N'n'),(N'Currencies',N'Iranian rial', N'ar', N'الريال الإيراني', N'n'),(N'Currencies',N'Iranian rial', N'am', N'የኢራን ሪአል', N'n'),(N'Currencies',N'Iranian rial', N'cn', N'伊朗里亚尔', N'n'),
(N'Currencies',N'Icelandic króna', N'ar', N'الكرونا الأيسلندية', N'n'),(N'Currencies',N'Icelandic króna', N'am', N'አይስላንድኛ ክሮና', N'n'),(N'Currencies',N'Icelandic króna', N'cn', N'冰岛克朗', N'n'),(N'Currencies',N'Icelandic króna', N'ar', N'الكرونا الأيسلندية', N'n'),(N'Currencies',N'Icelandic króna', N'am', N'አይስላንድኛ ክሮና', N'n'),(N'Currencies',N'Icelandic króna', N'cn', N'冰岛克朗', N'n'),
(N'Currencies',N'JM Dollar', N'ar', N'دولار جامايكي', N'n'),(N'Currencies',N'JM Dollar', N'am', N'ጄ ኤም ዶላር', N'n'),(N'Currencies',N'JM Dollar', N'cn', N'牙买加元', N'n'),(N'Currencies',N'Jamaican dollar', N'ar', N'دولار جامايكي', N'n'),(N'Currencies',N'Jamaican dollar', N'am', N'የጃማይካ ዶላር', N'n'),(N'Currencies',N'Jamaican dollar', N'cn', N'牙买加元', N'n'),
(N'Currencies',N'JO Dinar', N'ar', N'دينار أردني', N'n'),(N'Currencies',N'JO Dinar', N'am', N'ጆ ዲናር', N'n'),(N'Currencies',N'JO Dinar', N'cn', N'约旦第纳尔', N'n'),(N'Currencies',N'Jordanian dinar', N'ar', N'دينار أردني', N'n'),(N'Currencies',N'Jordanian dinar', N'am', N'የዮርዳኖስ ዲናር', N'n'),(N'Currencies',N'Jordanian dinar', N'cn', N'约旦第纳尔', N'n'),
(N'Currencies',N'Yen', N'ar', N'ين', N'n'),(N'Currencies',N'Yen', N'am', N'አዎ', N'n'),(N'Currencies',N'Yen', N'cn', N'日圆', N'n'),(N'Currencies',N'Japanese yen', N'ar', N'الين الياباني', N'n'),(N'Currencies',N'Japanese yen', N'am', N'የጃፓን yen', N'n'),(N'Currencies',N'Japanese yen', N'cn', N'日圆', N'n'),
(N'Currencies',N'Kenyan shilling', N'ar', N'شلن كيني', N'n'),(N'Currencies',N'Kenyan shilling', N'am', N'የኬንያ ሺሊንግ', N'n'),(N'Currencies',N'Kenyan shilling', N'cn', N'肯尼亚先令', N'n'),(N'Currencies',N'Kenyan shilling', N'ar', N'شلن كيني', N'n'),(N'Currencies',N'Kenyan shilling', N'am', N'የኬንያ ሺሊንግ', N'n'),(N'Currencies',N'Kenyan shilling', N'cn', N'肯尼亚先令', N'n'),
(N'Currencies',N'Kyrgyzstani som', N'ar', N'سوم قرغيزستاني', N'n'),(N'Currencies',N'Kyrgyzstani som', N'am', N'ኪርጊስታስታን som', N'n'),(N'Currencies',N'Kyrgyzstani som', N'cn', N'吉尔吉斯斯坦', N'n'),(N'Currencies',N'Kyrgyzstani som', N'ar', N'سوم قرغيزستاني', N'n'),(N'Currencies',N'Kyrgyzstani som', N'am', N'ኪርጊስታስታን som', N'n'),(N'Currencies',N'Kyrgyzstani som', N'cn', N'吉尔吉斯斯坦', N'n'),
(N'Currencies',N'Cambodian riel', N'ar', N'رييل كمبودي', N'n'),(N'Currencies',N'Cambodian riel', N'am', N'የካምቦዲያ ሪል', N'n'),(N'Currencies',N'Cambodian riel', N'cn', N'柬埔寨瑞尔', N'n'),(N'Currencies',N'Cambodian riel', N'ar', N'رييل كمبودي', N'n'),(N'Currencies',N'Cambodian riel', N'am', N'የካምቦዲያ ሪል', N'n'),(N'Currencies',N'Cambodian riel', N'cn', N'柬埔寨瑞尔', N'n'),
(N'Currencies',N'Comoro franc', N'ar', N'فرنك جزر القمر', N'n'),(N'Currencies',N'Comoro franc', N'am', N'ኮሞሮ ፍራንክ', N'n'),(N'Currencies',N'Comoro franc', N'cn', N'科摩罗法郎', N'n'),(N'Currencies',N'Comoro franc', N'ar', N'فرنك جزر القمر', N'n'),(N'Currencies',N'Comoro franc', N'am', N'ኮሞሮ ፍራንክ', N'n'),(N'Currencies',N'Comoro franc', N'cn', N'科摩罗法郎', N'n'),
(N'Currencies',N'North Korean won', N'ar', N'وون كوري شمالي', N'n'),(N'Currencies',N'North Korean won', N'am', N'ሰሜን ኮሪያ አሸነፈ', N'n'),(N'Currencies',N'North Korean won', N'cn', N'朝鲜元', N'n'),(N'Currencies',N'North Korean won', N'ar', N'وون كوري شمالي', N'n'),(N'Currencies',N'North Korean won', N'am', N'ሰሜን ኮሪያ አሸነፈ', N'n'),(N'Currencies',N'North Korean won', N'cn', N'朝鲜元', N'n'),
(N'Currencies',N'South Korean won', N'ar', N'وون كوريا الجنوبية', N'n'),(N'Currencies',N'South Korean won', N'am', N'ደቡብ ኮሪያ አሸነፈ', N'n'),(N'Currencies',N'South Korean won', N'cn', N'韩元', N'n'),(N'Currencies',N'South Korean won', N'ar', N'وون كوريا الجنوبية', N'n'),(N'Currencies',N'South Korean won', N'am', N'ደቡብ ኮሪያ አሸነፈ', N'n'),(N'Currencies',N'South Korean won', N'cn', N'韩元', N'n'),
(N'Currencies',N'KW Dinar', N'ar', N'دينار ك.', N'n'),(N'Currencies',N'KW Dinar', N'am', N'KW ዲናር', N'n'),(N'Currencies',N'KW Dinar', N'cn', N'科威特第纳尔', N'n'),(N'Currencies',N'Kuwaiti dinar', N'ar', N'دينار كويتي', N'n'),(N'Currencies',N'Kuwaiti dinar', N'am', N'የኩዌይ ዲናር', N'n'),(N'Currencies',N'Kuwaiti dinar', N'cn', N'科威特第纳尔', N'n'),
(N'Currencies',N'Cayman Islands dollar', N'ar', N'دولار جزر كايمان', N'n'),(N'Currencies',N'Cayman Islands dollar', N'am', N'የካማን ደሴቶች ዶላር', N'n'),(N'Currencies',N'Cayman Islands dollar', N'cn', N'开曼群岛元', N'n'),(N'Currencies',N'Cayman Islands dollar', N'ar', N'دولار جزر كايمان', N'n'),(N'Currencies',N'Cayman Islands dollar', N'am', N'የካማን ደሴቶች ዶላር', N'n'),(N'Currencies',N'Cayman Islands dollar', N'cn', N'开曼群岛元', N'n'),
(N'Currencies',N'Tenge', N'ar', N'تنغي', N'n'),(N'Currencies',N'Tenge', N'am', N'ዘንግ', N'n'),(N'Currencies',N'Tenge', N'cn', N'哈萨克斯坦坚戈', N'n'),(N'Currencies',N'Kazakhstani tenge', N'ar', N'تنغي كازاخستاني', N'n'),(N'Currencies',N'Kazakhstani tenge', N'am', N'ካዛኪስታን ታንግ', N'n'),(N'Currencies',N'Kazakhstani tenge', N'cn', N'哈萨克斯坦坚戈', N'n'),
(N'Currencies',N'Kip', N'ar', N'كيب', N'n'),(N'Currencies',N'Kip', N'am', N'Kip', N'n'),(N'Currencies',N'Kip', N'cn', N'老挝基普', N'n'),(N'Currencies',N'Lao kip', N'ar', N'لاو كيب', N'n'),(N'Currencies',N'Lao kip', N'am', N'ላኦ ኪፕ', N'n'),(N'Currencies',N'Lao kip', N'cn', N'老挝基普', N'n'),
(N'Currencies',N'LB Pound', N'ar', N'ليرة ل.', N'n'),(N'Currencies',N'LB Pound', N'am', N'LB ፓውንድ', N'n'),(N'Currencies',N'LB Pound', N'cn', N'黎巴嫩镑', N'n'),(N'Currencies',N'Lebanese pound', N'ar', N'ليرة لبنانية', N'n'),(N'Currencies',N'Lebanese pound', N'am', N'የሊባኖስ ፓውንድ', N'n'),(N'Currencies',N'Lebanese pound', N'cn', N'黎巴嫩镑', N'n'),
(N'Currencies',N'Sri Lankan rupee', N'ar', N'روبية سريلانكية', N'n'),(N'Currencies',N'Sri Lankan rupee', N'am', N'ሲሪላንካ ሩፔ', N'n'),(N'Currencies',N'Sri Lankan rupee', N'cn', N'斯里兰卡卢比', N'n'),(N'Currencies',N'Sri Lankan rupee', N'ar', N'روبية سريلانكية', N'n'),(N'Currencies',N'Sri Lankan rupee', N'am', N'ሲሪላንካ ሩፔ', N'n'),(N'Currencies',N'Sri Lankan rupee', N'cn', N'斯里兰卡卢比', N'n'),
(N'Currencies',N'LR Dollar', N'ar', N'دولار ليبيري', N'n'),(N'Currencies',N'LR Dollar', N'am', N'LR ዶላር', N'n'),(N'Currencies',N'LR Dollar', N'cn', N'利比里亚元', N'n'),(N'Currencies',N'Liberian dollar', N'ar', N'دولار ليبيري', N'n'),(N'Currencies',N'Liberian dollar', N'am', N'የሊቤሪያ ዶላር', N'n'),(N'Currencies',N'Liberian dollar', N'cn', N'利比里亚元', N'n'),
(N'Currencies',N'Lesotho loti', N'ar', N'لوتي ليسوتو', N'n'),(N'Currencies',N'Lesotho loti', N'am', N'ሌሶቶ ሎቲ', N'n'),(N'Currencies',N'Lesotho loti', N'cn', N'莱索托洛蒂', N'n'),(N'Currencies',N'Lesotho loti', N'ar', N'لوتي ليسوتو', N'n'),(N'Currencies',N'Lesotho loti', N'am', N'ሌሶቶ ሎቲ', N'n'),(N'Currencies',N'Lesotho loti', N'cn', N'莱索托洛蒂', N'n'),
(N'Currencies',N'LY Dinar', N'ar', N'دينار ل.', N'n'),(N'Currencies',N'LY Dinar', N'am', N'LY Dinar', N'n'),(N'Currencies',N'LY Dinar', N'cn', N'利比亚第纳尔', N'n'),(N'Currencies',N'Libyan dinar', N'ar', N'دينار ليبي', N'n'),(N'Currencies',N'Libyan dinar', N'am', N'ሊቢያ ዲናር', N'n'),(N'Currencies',N'Libyan dinar', N'cn', N'利比亚第纳尔', N'n'),
(N'Currencies',N'MA Dirham', N'ar', N'درهم م.', N'n'),(N'Currencies',N'MA Dirham', N'am', N'ኤም ዲ Dirham', N'n'),(N'Currencies',N'MA Dirham', N'cn', N'摩洛哥迪拉姆', N'n'),(N'Currencies',N'Moroccan dirham', N'ar', N'الدرهم المغربي', N'n'),(N'Currencies',N'Moroccan dirham', N'am', N'የሞሮኮ ዲርሃም', N'n'),(N'Currencies',N'Moroccan dirham', N'cn', N'摩洛哥迪拉姆', N'n'),
(N'Currencies',N'Moldovan leu', N'ar', N'لو مولدوفا', N'n'),(N'Currencies',N'Moldovan leu', N'am', N'ሞልዶቫን ሉ', N'n'),(N'Currencies',N'Moldovan leu', N'cn', N'摩尔多瓦州', N'n'),(N'Currencies',N'Moldovan leu', N'ar', N'لو مولدوفا', N'n'),(N'Currencies',N'Moldovan leu', N'am', N'ሞልዶቫን ሉ', N'n'),(N'Currencies',N'Moldovan leu', N'cn', N'摩尔多瓦州', N'n'),
(N'Currencies',N'Malagasy ariary', N'ar', N'ارياري مدغشقر', N'n'),(N'Currencies',N'Malagasy ariary', N'am', N'የማለጋሲ አሪሪየስ', N'n'),(N'Currencies',N'Malagasy ariary', N'cn', N'马达加斯加人的ariary', N'n'),(N'Currencies',N'Malagasy ariary', N'ar', N'ارياري مدغشقر', N'n'),(N'Currencies',N'Malagasy ariary', N'am', N'የማለጋሲ አሪሪየስ', N'n'),(N'Currencies',N'Malagasy ariary', N'cn', N'马达加斯加人的ariary', N'n'),
(N'Currencies',N'Macedonian denar', N'ar', N'دينار مقدوني', N'n'),(N'Currencies',N'Macedonian denar', N'am', N'የመቄዶንያ ዲናር', N'n'),(N'Currencies',N'Macedonian denar', N'cn', N'马其顿第纳尔', N'n'),(N'Currencies',N'Macedonian denar', N'ar', N'دينار مقدوني', N'n'),(N'Currencies',N'Macedonian denar', N'am', N'የመቄዶንያ ዲናር', N'n'),(N'Currencies',N'Macedonian denar', N'cn', N'马其顿第纳尔', N'n'),
(N'Currencies',N'Myanmar kyat', N'ar', N'كيات ميانمار', N'n'),(N'Currencies',N'Myanmar kyat', N'am', N'ምያንማር ኪያ', N'n'),(N'Currencies',N'Myanmar kyat', N'cn', N'缅甸缅元', N'n'),(N'Currencies',N'Myanmar kyat', N'ar', N'كيات ميانمار', N'n'),(N'Currencies',N'Myanmar kyat', N'am', N'ምያንማር ኪያ', N'n'),(N'Currencies',N'Myanmar kyat', N'cn', N'缅甸缅元', N'n'),
(N'Currencies',N'tögrög', N'ar', N'tögrög المنغولية', N'n'),(N'Currencies',N'tögrög', N'am', N'tögrög', N'n'),(N'Currencies',N'tögrög', N'cn', N'蒙古语tögrög', N'n'),(N'Currencies',N'Mongolian tögrög', N'ar', N'tögrög المنغولية', N'n'),(N'Currencies',N'Mongolian tögrög', N'am', N'የሞንጎሊያ ቱርገን', N'n'),(N'Currencies',N'Mongolian tögrög', N'cn', N'蒙古语tögrög', N'n'),
(N'Currencies',N'Pataca', N'ar', N'باتاكا', N'n'),(N'Currencies',N'Pataca', N'am', N'ፓትካካ', N'n'),(N'Currencies',N'Pataca', N'cn', N'澳门币', N'n'),(N'Currencies',N'Macanese pataca', N'ar', N'باتاكا ماكا', N'n'),(N'Currencies',N'Macanese pataca', N'am', N'ማካኒዝ ፓታካ', N'n'),(N'Currencies',N'Macanese pataca', N'cn', N'澳门币', N'n'),
(N'Currencies',N'Ouguiya', N'ar', N'أوقية', N'n'),(N'Currencies',N'Ouguiya', N'am', N'ኦውጉያ', N'n'),(N'Currencies',N'Ouguiya', N'cn', N'毛里塔尼亚ouguiya', N'n'),(N'Currencies',N'Mauritanian ouguiya', N'ar', N'أوقية موريتانية', N'n'),(N'Currencies',N'Mauritanian ouguiya', N'am', N'የሞሪታኒያ ኦጉሊያያ', N'n'),(N'Currencies',N'Mauritanian ouguiya', N'cn', N'毛里塔尼亚ouguiya', N'n'),
(N'Currencies',N'Mauritian rupee', N'ar', N'روبية موريشيوسية', N'n'),(N'Currencies',N'Mauritian rupee', N'am', N'ሞሪሺያን ሩፔ', N'n'),(N'Currencies',N'Mauritian rupee', N'cn', N'毛里求斯卢比', N'n'),(N'Currencies',N'Mauritian rupee', N'ar', N'روبية موريشيوسية', N'n'),(N'Currencies',N'Mauritian rupee', N'am', N'ሞሪሺያን ሩፔ', N'n'),(N'Currencies',N'Mauritian rupee', N'cn', N'毛里求斯卢比', N'n'),
(N'Currencies',N'Rufiyaa', N'ar', N'روفية', N'n'),(N'Currencies',N'Rufiyaa', N'am', N'ሩፋሚ', N'n'),(N'Currencies',N'Rufiyaa', N'cn', N'马尔代夫拉菲亚', N'n'),(N'Currencies',N'Maldivian rufiyaa', N'ar', N'روفية جزر المالديف', N'n'),(N'Currencies',N'Maldivian rufiyaa', N'am', N'ማልዲቪያ ሩፊያና', N'n'),(N'Currencies',N'Maldivian rufiyaa', N'cn', N'马尔代夫拉菲亚', N'n'),
(N'Currencies',N'Malawian kwacha', N'ar', N'كواشا ملاوي', N'n'),(N'Currencies',N'Malawian kwacha', N'am', N'ማላዊዊኪካቻ', N'n'),(N'Currencies',N'Malawian kwacha', N'cn', N'马拉维夸瓦', N'n'),(N'Currencies',N'Malawian kwacha', N'ar', N'كواشا ملاوي', N'n'),(N'Currencies',N'Malawian kwacha', N'am', N'ማላዊዊኪካቻ', N'n'),(N'Currencies',N'Malawian kwacha', N'cn', N'马拉维夸瓦', N'n'),
(N'Currencies',N'Mexican peso', N'ar', N'البيزو المكسيكي', N'n'),(N'Currencies',N'Mexican peso', N'am', N'የሜክሲኮ ፔሶ', N'n'),(N'Currencies',N'Mexican peso', N'cn', N'墨西哥比索', N'n'),(N'Currencies',N'Mexican peso', N'ar', N'البيزو المكسيكي', N'n'),(N'Currencies',N'Mexican peso', N'am', N'የሜክሲኮ ፔሶ', N'n'),(N'Currencies',N'Mexican peso', N'cn', N'墨西哥比索', N'n'),
(N'Currencies',N'Malaysian ringgit', N'ar', N'رينغيت ماليزي', N'n'),(N'Currencies',N'Malaysian ringgit', N'am', N'የማሌsianያ የስልክ ጥሪ', N'n'),(N'Currencies',N'Malaysian ringgit', N'cn', N'马来西亚林吉特', N'n'),(N'Currencies',N'Malaysian ringgit', N'ar', N'رينغيت ماليزي', N'n'),(N'Currencies',N'Malaysian ringgit', N'am', N'የማሌsianያ የስልክ ጥሪ', N'n'),(N'Currencies',N'Malaysian ringgit', N'cn', N'马来西亚林吉特', N'n'),
(N'Currencies',N'Mozambican metical', N'ar', N'متكال موزمبيقي', N'n'),(N'Currencies',N'Mozambican metical', N'am', N'የሞዛምቢክ ሜታል', N'n'),(N'Currencies',N'Mozambican metical', N'cn', N'莫桑比克梅蒂卡尔', N'n'),(N'Currencies',N'Mozambican metical', N'ar', N'متكال موزمبيقي', N'n'),(N'Currencies',N'Mozambican metical', N'am', N'የሞዛምቢክ ሜታል', N'n'),(N'Currencies',N'Mozambican metical', N'cn', N'莫桑比克梅蒂卡尔', N'n'),
(N'Currencies',N'NA Dollar', N'ar', N'الدولار الناميبي', N'n'),(N'Currencies',N'NA Dollar', N'am', N'ኤን ዶላር', N'n'),(N'Currencies',N'NA Dollar', N'cn', N'纳米比亚元', N'n'),(N'Currencies',N'Namibian dollar', N'ar', N'الدولار الناميبي', N'n'),(N'Currencies',N'Namibian dollar', N'am', N'የናሚቢያ ዶላር', N'n'),(N'Currencies',N'Namibian dollar', N'cn', N'纳米比亚元', N'n'),
(N'Currencies',N'Naira', N'ar', N'نيرة', N'n'),(N'Currencies',N'Naira', N'am', N'ናይ', N'n'),(N'Currencies',N'Naira', N'cn', N'尼日利亚奈拉', N'n'),(N'Currencies',N'Nigerian naira', N'ar', N'نيرة نيجيرية', N'n'),(N'Currencies',N'Nigerian naira', N'am', N'ናይጄሪያ ናይጄሪያ', N'n'),(N'Currencies',N'Nigerian naira', N'cn', N'尼日利亚奈拉', N'n'),
(N'Currencies',N'Córdoba', N'ar', N'قرطبة', N'n'),(N'Currencies',N'Córdoba', N'am', N'ኮርዶባ', N'n'),(N'Currencies',N'Córdoba', N'cn', N'尼加拉瓜科尔多瓦', N'n'),(N'Currencies',N'Nicaraguan córdoba', N'ar', N'قرطبة النيكاراغوية', N'n'),(N'Currencies',N'Nicaraguan córdoba', N'am', N'ኒካራጉዋ ኮርዶባ', N'n'),(N'Currencies',N'Nicaraguan córdoba', N'cn', N'尼加拉瓜科尔多瓦', N'n');
INSERT INTO @Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]) VALUES
(N'Currencies',N'Norwegian krone', N'ar', N'كرونة نرويجية', N'n'),(N'Currencies',N'Norwegian krone', N'am', N'የኖርዌይ ክሮነር', N'n'),(N'Currencies',N'Norwegian krone', N'cn', N'挪威克朗', N'n'),(N'Currencies',N'Norwegian krone', N'ar', N'كرونة نرويجية', N'n'),(N'Currencies',N'Norwegian krone', N'am', N'የኖርዌይ ክሮነር', N'n'),(N'Currencies',N'Norwegian krone', N'cn', N'挪威克朗', N'n'),
(N'Currencies',N'Nepalese rupee', N'ar', N'روبية نيبالية', N'n'),(N'Currencies',N'Nepalese rupee', N'am', N'Nepalese rupee', N'n'),(N'Currencies',N'Nepalese rupee', N'cn', N'尼泊尔卢比', N'n'),(N'Currencies',N'Nepalese rupee', N'ar', N'روبية نيبالية', N'n'),(N'Currencies',N'Nepalese rupee', N'am', N'Nepalese rupee', N'n'),(N'Currencies',N'Nepalese rupee', N'cn', N'尼泊尔卢比', N'n'),
(N'Currencies',N'NZ Dollar', N'ar', N'دولار نيوزيلندي', N'n'),(N'Currencies',N'NZ Dollar', N'am', N'NZ ዶላር', N'n'),(N'Currencies',N'NZ Dollar', N'cn', N'新西兰元', N'n'),(N'Currencies',N'New Zealand dollar', N'ar', N'الدولار النيوزيلندي', N'n'),(N'Currencies',N'New Zealand dollar', N'am', N'የኒውዚላንድ ዶላር', N'n'),(N'Currencies',N'New Zealand dollar', N'cn', N'新西兰元', N'n'),
(N'Currencies',N'OM Rial', N'ar', N'ريال ع.', N'n'),(N'Currencies',N'OM Rial', N'am', N'ኦኤም ኪራይ', N'n'),(N'Currencies',N'OM Rial', N'cn', N'阿曼里亚尔', N'n'),(N'Currencies',N'Omani rial', N'ar', N'الريال العماني', N'n'),(N'Currencies',N'Omani rial', N'am', N'ኦማኒ ሪአል', N'n'),(N'Currencies',N'Omani rial', N'cn', N'阿曼里亚尔', N'n'),
(N'Currencies',N'Balboa', N'ar', N'بالبوا', N'n'),(N'Currencies',N'Balboa', N'am', N'ባልባል', N'n'),(N'Currencies',N'Balboa', N'cn', N'巴拿马巴波亚', N'n'),(N'Currencies',N'Panamanian balboa', N'ar', N'بالبوا البنمي', N'n'),(N'Currencies',N'Panamanian balboa', N'am', N'የፓናማ ቦልባባ', N'n'),(N'Currencies',N'Panamanian balboa', N'cn', N'巴拿马巴波亚', N'n'),
(N'Currencies',N'Peruvian sol', N'ar', N'سول بيرو', N'n'),(N'Currencies',N'Peruvian sol', N'am', N'የፔሩቪያ ሶል', N'n'),(N'Currencies',N'Peruvian sol', N'cn', N'秘鲁溶胶', N'n'),(N'Currencies',N'Peruvian sol', N'ar', N'سول بيرو', N'n'),(N'Currencies',N'Peruvian sol', N'am', N'የፔሩቪያ ሶል', N'n'),(N'Currencies',N'Peruvian sol', N'cn', N'秘鲁溶胶', N'n'),
(N'Currencies',N'Kina', N'ar', N'كينا', N'n'),(N'Currencies',N'Kina', N'am', N'ኪና', N'n'),(N'Currencies',N'Kina', N'cn', N'巴布亚新几内亚基那', N'n'),(N'Currencies',N'Papua New Guinean kina', N'ar', N'كينا بابوا غينيا الجديدة', N'n'),(N'Currencies',N'Papua New Guinean kina', N'am', N'ፓፓዋ ኒው ጊኒና ካና', N'n'),(N'Currencies',N'Papua New Guinean kina', N'cn', N'巴布亚新几内亚基那', N'n'),
(N'Currencies',N'Philippine peso', N'ar', N'البيزو الفلبيني [13]', N'n'),(N'Currencies',N'Philippine peso', N'am', N'የፊሊፒንስ ፔሶ', N'n'),(N'Currencies',N'Philippine peso', N'cn', N'菲律宾比索[13]', N'n'),(N'Currencies',N'Philippine peso', N'ar', N'البيزو الفلبيني [13]', N'n'),(N'Currencies',N'Philippine peso', N'am', N'የፊሊፒንስ ፔሶ [13]', N'n'),(N'Currencies',N'Philippine peso', N'cn', N'菲律宾比索[13]', N'n'),
(N'Currencies',N'Pakistani rupee', N'ar', N'روبية باكستانية', N'n'),(N'Currencies',N'Pakistani rupee', N'am', N'የፓኪስታን ሩፔ', N'n'),(N'Currencies',N'Pakistani rupee', N'cn', N'巴基斯坦卢比', N'n'),(N'Currencies',N'Pakistani rupee', N'ar', N'روبية باكستانية', N'n'),(N'Currencies',N'Pakistani rupee', N'am', N'የፓኪስታን ሩፔ', N'n'),(N'Currencies',N'Pakistani rupee', N'cn', N'巴基斯坦卢比', N'n'),
(N'Currencies',N'Złoty', N'ar', N'زلوتي', N'n'),(N'Currencies',N'Złoty', N'am', N'ዚቲ', N'n'),(N'Currencies',N'Złoty', N'cn', N'波兰兹罗提', N'n'),(N'Currencies',N'Polish złoty', N'ar', N'زلوتي بولندي', N'n'),(N'Currencies',N'Polish złoty', N'am', N'የፖላንድ złoty', N'n'),(N'Currencies',N'Polish złoty', N'cn', N'波兰兹罗提', N'n'),
(N'Currencies',N'Guaraní', N'ar', N'غواراني', N'n'),(N'Currencies',N'Guaraní', N'am', N'ጉራኒ', N'n'),(N'Currencies',N'Guaraní', N'cn', N'巴拉圭瓜拉尼', N'n'),(N'Currencies',N'Paraguayan guaraní', N'ar', N'الغواراني الباراغواي', N'n'),(N'Currencies',N'Paraguayan guaraní', N'am', N'ፓራጓይ garaní', N'n'),(N'Currencies',N'Paraguayan guaraní', N'cn', N'巴拉圭瓜拉尼', N'n'),
(N'Currencies',N'QA Riyal', N'ar', N'ريال ق.', N'n'),(N'Currencies',N'QA Riyal', N'am', N'QA Riyal', N'n'),(N'Currencies',N'QA Riyal', N'cn', N'卡塔尔里亚尔', N'n'),(N'Currencies',N'Qatari riyal', N'ar', N'الريال القطري', N'n'),(N'Currencies',N'Qatari riyal', N'am', N'የኳታር ሪአል', N'n'),(N'Currencies',N'Qatari riyal', N'cn', N'卡塔尔里亚尔', N'n'),
(N'Currencies',N'Romanian leu', N'ar', N'ليو روماني', N'n'),(N'Currencies',N'Romanian leu', N'am', N'የሮማኒያ ሊ', N'n'),(N'Currencies',N'Romanian leu', N'cn', N'罗马尼亚列伊', N'n'),(N'Currencies',N'Romanian leu', N'ar', N'ليو روماني', N'n'),(N'Currencies',N'Romanian leu', N'am', N'የሮማኒያ ሊ', N'n'),(N'Currencies',N'Romanian leu', N'cn', N'罗马尼亚列伊', N'n'),
(N'Currencies',N'RS Dinar', N'ar', N'دينار ص.', N'n'),(N'Currencies',N'RS Dinar', N'am', N'አርኤስ ዲናር', N'n'),(N'Currencies',N'RS Dinar', N'cn', N'塞尔维亚第纳尔', N'n'),(N'Currencies',N'Serbian dinar', N'ar', N'دينار صربي', N'n'),(N'Currencies',N'Serbian dinar', N'am', N'ሰርቢያ ዲናር', N'n'),(N'Currencies',N'Serbian dinar', N'cn', N'塞尔维亚第纳尔', N'n'),
(N'Currencies',N'Russian ruble', N'ar', N'الروبل الروسي', N'n'),(N'Currencies',N'Russian ruble', N'am', N'የሩሲያ ሩብል', N'n'),(N'Currencies',N'Russian ruble', N'cn', N'俄罗斯卢布', N'n'),(N'Currencies',N'Russian ruble', N'ar', N'الروبل الروسي', N'n'),(N'Currencies',N'Russian ruble', N'am', N'የሩሲያ ሩብል', N'n'),(N'Currencies',N'Russian ruble', N'cn', N'俄罗斯卢布', N'n'),
(N'Currencies',N'Rwandan franc', N'ar', N'فرنك رواندي', N'n'),(N'Currencies',N'Rwandan franc', N'am', N'የሩዋንዳ ፍራንክ', N'n'),(N'Currencies',N'Rwandan franc', N'cn', N'卢旺达法郎', N'n'),(N'Currencies',N'Rwandan franc', N'ar', N'فرنك رواندي', N'n'),(N'Currencies',N'Rwandan franc', N'am', N'የሩዋንዳ ፍራንክ', N'n'),(N'Currencies',N'Rwandan franc', N'cn', N'卢旺达法郎', N'n'),
(N'Currencies',N'SA Riyal', N'ar', N'ريال س.', N'n'),(N'Currencies',N'SA Riyal', N'am', N'ኤስ አር ሪል', N'n'),(N'Currencies',N'SA Riyal', N'cn', N'沙特里亚尔', N'n'),(N'Currencies',N'Saudi Riyal', N'ar', N'ريال سعودي', N'n'),(N'Currencies',N'Saudi Riyal', N'am', N'ሳዑዲ ታጋይ', N'n'),(N'Currencies',N'Saudi Riyal', N'cn', N'沙特里亚尔', N'n'),
(N'Currencies',N'SB Dollar', N'ar', N'دولار جزر سليمان', N'n'),(N'Currencies',N'SB Dollar', N'am', N'SB ዶላር', N'n'),(N'Currencies',N'SB Dollar', N'cn', N'所罗门群岛元', N'n'),(N'Currencies',N'Solomon Islands dollar', N'ar', N'دولار جزر سليمان', N'n'),(N'Currencies',N'Solomon Islands dollar', N'am', N'የሰለሞን ደሴቶች ዶላር', N'n'),(N'Currencies',N'Solomon Islands dollar', N'cn', N'所罗门群岛元', N'n'),
(N'Currencies',N'Seychelles rupee', N'ar', N'روبية سيشيل', N'n'),(N'Currencies',N'Seychelles rupee', N'am', N'ሲሸልስ ሩፔ', N'n'),(N'Currencies',N'Seychelles rupee', N'cn', N'塞舌尔卢比', N'n'),(N'Currencies',N'Seychelles rupee', N'ar', N'روبية سيشيل', N'n'),(N'Currencies',N'Seychelles rupee', N'am', N'ሲሸልስ ሩፔ', N'n'),(N'Currencies',N'Seychelles rupee', N'cn', N'塞舌尔卢比', N'n'),
(N'Currencies',N'SD Pound', N'ar', N'جنيه س.', N'n'),(N'Currencies',N'SD Pound', N'am', N'ኤስዲ ፓውንድ', N'n'),(N'Currencies',N'SD Pound', N'cn', N'苏丹镑', N'n'),(N'Currencies',N'Sudanese Pound', N'ar', N'جنيه سوداني', N'n'),(N'Currencies',N'Sudanese Pound', N'am', N'የሱዳን ፓውንድ', N'n'),(N'Currencies',N'Sudanese Pound', N'cn', N'苏丹镑', N'n'),
(N'Currencies',N'Krona', N'ar', N'كرونة', N'n'),(N'Currencies',N'Krona', N'am', N'ክሮና', N'n'),(N'Currencies',N'Krona', N'cn', N'瑞典克朗/克朗', N'n'),(N'Currencies',N'Swedish krona/kronor', N'ar', N'كرونة سويدية / كرونة', N'n'),(N'Currencies',N'Swedish krona/kronor', N'am', N'የስዊድን ክሮና / ክሮነር', N'n'),(N'Currencies',N'Swedish krona/kronor', N'cn', N'瑞典克朗/克朗', N'n'),
(N'Currencies',N'SG Dollar', N'ar', N'دولار س.', N'n'),(N'Currencies',N'SG Dollar', N'am', N'SG ዶላር', N'n'),(N'Currencies',N'SG Dollar', N'cn', N'新加坡元', N'n'),(N'Currencies',N'Singapore dollar', N'ar', N'دولار سينغافوري', N'n'),(N'Currencies',N'Singapore dollar', N'am', N'የሲንጋፖር ዶላር', N'n'),(N'Currencies',N'Singapore dollar', N'cn', N'新加坡元', N'n'),
(N'Currencies',N'SH Pound', N'ar', N'جنيه سانت هيلانة', N'n'),(N'Currencies',N'SH Pound', N'am', N'SH ፓውንድ', N'n'),(N'Currencies',N'SH Pound', N'cn', N'圣海伦娜镑', N'n'),(N'Currencies',N'Saint Helena pound', N'ar', N'جنيه سانت هيلانة', N'n'),(N'Currencies',N'Saint Helena pound', N'am', N'ቅድስት ሄለና ፓውንድ', N'n'),(N'Currencies',N'Saint Helena pound', N'cn', N'圣海伦娜镑', N'n'),
(N'Currencies',N'Sierra Leonean leone', N'ar', N'ليون سيراليوني', N'n'),(N'Currencies',N'Sierra Leonean leone', N'am', N'ሴራሊዮን ሊዮን', N'n'),(N'Currencies',N'Sierra Leonean leone', N'cn', N'塞拉利昂利昂', N'n'),(N'Currencies',N'Sierra Leonean leone', N'ar', N'ليون سيراليوني', N'n'),(N'Currencies',N'Sierra Leonean leone', N'am', N'ሴራሊዮን ሊዮን', N'n'),(N'Currencies',N'Sierra Leonean leone', N'cn', N'塞拉利昂利昂', N'n'),
(N'Currencies',N'Somali shilling', N'ar', N'شلن صومالي', N'n'),(N'Currencies',N'Somali shilling', N'am', N'የሶማሊ ሺሊንግ', N'n'),(N'Currencies',N'Somali shilling', N'cn', N'索马里先令', N'n'),(N'Currencies',N'Somali shilling', N'ar', N'شلن صومالي', N'n'),(N'Currencies',N'Somali shilling', N'am', N'የሶማሊ ሺሊንግ', N'n'),(N'Currencies',N'Somali shilling', N'cn', N'索马里先令', N'n'),
(N'Currencies',N'SR Dollar', N'ar', N'دولار سورينامي', N'n'),(N'Currencies',N'SR Dollar', N'am', N'SR ዶላር', N'n'),(N'Currencies',N'SR Dollar', N'cn', N'苏里南元', N'n'),(N'Currencies',N'Surinamese dollar', N'ar', N'دولار سورينامي', N'n'),(N'Currencies',N'Surinamese dollar', N'am', N'የሱሪናሚዝ ዶላር', N'n'),(N'Currencies',N'Surinamese dollar', N'cn', N'苏里南元', N'n'),
(N'Currencies',N'SS Pound', N'ar', N'جنيه ج.س.', N'n'),(N'Currencies',N'SS Pound', N'am', N'ኤስ ኤስ ፓውንድ', N'n'),(N'Currencies',N'SS Pound', N'cn', N'南苏丹镑', N'n'),(N'Currencies',N'South Sudanese pound', N'ar', N'جنيه جنوب السودان', N'n'),(N'Currencies',N'South Sudanese pound', N'am', N'የደቡብ ሱዳን ፓውንድ', N'n'),(N'Currencies',N'South Sudanese pound', N'cn', N'南苏丹镑', N'n'),
(N'Currencies',N'Dobra', N'ar', N'دوبرا', N'n'),(N'Currencies',N'Dobra', N'am', N'ዶብራ', N'n'),(N'Currencies',N'Dobra', N'cn', N'圣多美和普林西比多布拉', N'n'),(N'Currencies',N'São Tomé and Príncipe dobra', N'ar', N'ساو تومي وبرينسيبي دوبرا', N'n'),(N'Currencies',N'São Tomé and Príncipe dobra', N'am', N'ሳኦ ቶሜ እና ፕሪንሲፔ ዶብራ', N'n'),(N'Currencies',N'São Tomé and Príncipe dobra', N'cn', N'圣多美和普林西比多布拉', N'n'),
(N'Currencies',N'Salvadoran colón', N'ar', N'كولون سلفادوري', N'n'),(N'Currencies',N'Salvadoran colón', N'am', N'ሳልቫዶራን ኮሎን', N'n'),(N'Currencies',N'Salvadoran colón', N'cn', N'萨尔瓦多科隆', N'n'),(N'Currencies',N'Salvadoran colón', N'ar', N'كولون سلفادوري', N'n'),(N'Currencies',N'Salvadoran colón', N'am', N'ሳልቫዶራን ኮሎን', N'n'),(N'Currencies',N'Salvadoran colón', N'cn', N'萨尔瓦多科隆', N'n'),
(N'Currencies',N'SY Pound', N'ar', N'ليرة س.', N'n'),(N'Currencies',N'SY Pound', N'am', N'SY ፓውንድ', N'n'),(N'Currencies',N'SY Pound', N'cn', N'叙利亚镑', N'n'),(N'Currencies',N'Syrian pound', N'ar', N'الليرة السورية', N'n'),(N'Currencies',N'Syrian pound', N'am', N'የሶሪያ ፓውንድ', N'n'),(N'Currencies',N'Syrian pound', N'cn', N'叙利亚镑', N'n'),
(N'Currencies',N'Swazi lilangeni', N'ar', N'ليلانجيني سوازي', N'n'),(N'Currencies',N'Swazi lilangeni', N'am', N'ስዋዚ ሊላጊኒ', N'n'),(N'Currencies',N'Swazi lilangeni', N'cn', N'斯威士兰', N'n'),(N'Currencies',N'Swazi lilangeni', N'ar', N'ليلانجيني سوازي', N'n'),(N'Currencies',N'Swazi lilangeni', N'am', N'ስዋዚ ሊላጊኒ', N'n'),(N'Currencies',N'Swazi lilangeni', N'cn', N'斯威士兰', N'n'),
(N'Currencies',N'Baht', N'ar', N'بات', N'n'),(N'Currencies',N'Baht', N'am', N'ባህት', N'n'),(N'Currencies',N'Baht', N'cn', N'泰铢', N'n'),(N'Currencies',N'Thai baht', N'ar', N'البات التايلندي', N'n'),(N'Currencies',N'Thai baht', N'am', N'የታይ ባht', N'n'),(N'Currencies',N'Thai baht', N'cn', N'泰铢', N'n'),
(N'Currencies',N'Somoni', N'ar', N'سوموني', N'n'),(N'Currencies',N'Somoni', N'am', N'ሶኒ', N'n'),(N'Currencies',N'Somoni', N'cn', N'塔吉克斯坦索莫尼', N'n'),(N'Currencies',N'Tajikistani somoni', N'ar', N'سوموني طاجيكستاني', N'n'),(N'Currencies',N'Tajikistani somoni', N'am', N'ታጂኪስታን ሶኒኒ', N'n'),(N'Currencies',N'Tajikistani somoni', N'cn', N'塔吉克斯坦索莫尼', N'n'),
(N'Currencies',N'Manat', N'ar', N'مانات', N'n'),(N'Currencies',N'Manat', N'am', N'ማን', N'n'),(N'Currencies',N'Manat', N'cn', N'土库曼斯坦马纳特', N'n'),(N'Currencies',N'Turkmenistan manat', N'ar', N'مانات تركمانستان', N'n'),(N'Currencies',N'Turkmenistan manat', N'am', N'የቱርክሜኒስታን ማንቴ', N'n'),(N'Currencies',N'Turkmenistan manat', N'cn', N'土库曼斯坦马纳特', N'n'),
(N'Currencies',N'TN Dinar', N'ar', N'دينار ت.', N'n'),(N'Currencies',N'TN Dinar', N'am', N'ቲን ዲናር', N'n'),(N'Currencies',N'TN Dinar', N'cn', N'突尼斯第纳尔', N'n'),(N'Currencies',N'Tunisian dinar', N'ar', N'دينار تونسي', N'n'),(N'Currencies',N'Tunisian dinar', N'am', N'የቱኒዚያ ዲናር', N'n'),(N'Currencies',N'Tunisian dinar', N'cn', N'突尼斯第纳尔', N'n'),
(N'Currencies',N'Paʻanga', N'ar', N'paʻanga التونغية', N'n'),(N'Currencies',N'Paʻanga', N'am', N'ፓራጋን', N'n'),(N'Currencies',N'Paʻanga', N'cn', N'汤加潘加', N'n'),(N'Currencies',N'Tongan paʻanga', N'ar', N'paʻanga التونغية', N'n'),(N'Currencies',N'Tongan paʻanga', N'am', N'ቶንጋን ፓንጋን', N'n'),(N'Currencies',N'Tongan paʻanga', N'cn', N'汤加潘加', N'n'),
(N'Currencies',N'Lira', N'ar', N'ليرة ت.', N'n'),(N'Currencies',N'Lira', N'am', N'ሊራ', N'n'),(N'Currencies',N'Lira', N'cn', N'土耳其里拉', N'n'),(N'Currencies',N'Turkish lira', N'ar', N'الليرة التركية', N'n'),(N'Currencies',N'Turkish lira', N'am', N'የቱርክ ሊራ', N'n'),(N'Currencies',N'Turkish lira', N'cn', N'土耳其里拉', N'n'),
(N'Currencies',N'TT Dollar', N'ar', N'دولار ت.ت.', N'n'),(N'Currencies',N'TT Dollar', N'am', N'ቲ ቲ ዶላር', N'n'),(N'Currencies',N'TT Dollar', N'cn', N'特立尼达和多巴哥元', N'n'),(N'Currencies',N'Trinidad and Tobago dollar', N'ar', N'دولار ترينيداد وتوباغو', N'n'),(N'Currencies',N'Trinidad and Tobago dollar', N'am', N'ትሪኒዳድ እና ቶባጎ ዶላር', N'n'),(N'Currencies',N'Trinidad and Tobago dollar', N'cn', N'特立尼达和多巴哥元', N'n'),
(N'Currencies',N'TW Dollar', N'ar', N'دولار تايواني جديد', N'n'),(N'Currencies',N'TW Dollar', N'am', N'TW ዶላር', N'n'),(N'Currencies',N'TW Dollar', N'cn', N'新台币', N'n'),(N'Currencies',N'New Taiwan dollar', N'ar', N'دولار تايواني جديد', N'n'),(N'Currencies',N'New Taiwan dollar', N'am', N'አዲስ ታይዋን ዶላር', N'n'),(N'Currencies',N'New Taiwan dollar', N'cn', N'新台币', N'n'),
(N'Currencies',N'Tanzanian shilling', N'ar', N'شلن تنزاني', N'n'),(N'Currencies',N'Tanzanian shilling', N'am', N'የታንዛኒያ shilling', N'n'),(N'Currencies',N'Tanzanian shilling', N'cn', N'坦桑尼亚先令', N'n'),(N'Currencies',N'Tanzanian shilling', N'ar', N'شلن تنزاني', N'n'),(N'Currencies',N'Tanzanian shilling', N'am', N'የታንዛኒያ shilling', N'n'),(N'Currencies',N'Tanzanian shilling', N'cn', N'坦桑尼亚先令', N'n'),
(N'Currencies',N'Hryvnia', N'ar', N'هريفنيا', N'n'),(N'Currencies',N'Hryvnia', N'am', N'ሂሪቪኒያ', N'n'),(N'Currencies',N'Hryvnia', N'cn', N'乌克兰格里夫纳汇率', N'n'),(N'Currencies',N'Ukrainian hryvnia', N'ar', N'هريفنيا أوكرانية', N'n'),(N'Currencies',N'Ukrainian hryvnia', N'am', N'የዩክሬንኛ hryvnia', N'n'),(N'Currencies',N'Ukrainian hryvnia', N'cn', N'乌克兰格里夫纳汇率', N'n'),
(N'Currencies',N'Ugandan shilling', N'ar', N'شلن أوغندي', N'n'),(N'Currencies',N'Ugandan shilling', N'am', N'የኡጋንዳ ሽሪንግ', N'n'),(N'Currencies',N'Ugandan shilling', N'cn', N'乌干达先令', N'n'),(N'Currencies',N'Ugandan shilling', N'ar', N'شلن أوغندي', N'n'),(N'Currencies',N'Ugandan shilling', N'am', N'የኡጋንዳ ሽሪንግ', N'n'),(N'Currencies',N'Ugandan shilling', N'cn', N'乌干达先令', N'n'),
(N'Currencies',N'US Dollar', N'ar', N'دولار أمريكي', N'n'),(N'Currencies',N'US Dollar', N'am', N'የአሜሪካ ዶላር', N'n'),(N'Currencies',N'US Dollar', N'cn', N'美国美元', N'n'),(N'Currencies',N'United States dollar', N'ar', N'دولار الولايات المتحدة', N'n'),(N'Currencies',N'United States dollar', N'am', N'የአሜሪካ ዶላር', N'n'),(N'Currencies',N'United States dollar', N'cn', N'美国美元', N'n'),
(N'Currencies',N'Uruguayan peso', N'ar', N'بيزو أوروغواي', N'n'),(N'Currencies',N'Uruguayan peso', N'am', N'የኡራጓይ ፔሶ', N'n'),(N'Currencies',N'Uruguayan peso', N'cn', N'乌拉圭比索', N'n'),(N'Currencies',N'Uruguayan peso', N'ar', N'بيزو أوروغواي', N'n'),(N'Currencies',N'Uruguayan peso', N'am', N'የኡራጓይ ፔሶ', N'n'),(N'Currencies',N'Uruguayan peso', N'cn', N'乌拉圭比索', N'n'),
(N'Currencies',N'Unidad previsional', N'ar', N'Unidad السابق', N'n'),(N'Currencies',N'Unidad previsional', N'am', N'ያልተለመደ ቅድመ-ዕይታ', N'n'),(N'Currencies',N'Unidad previsional', N'cn', N'Unidad临时', N'n'),(N'Currencies',N'Unidad previsional', N'ar', N'Unidad السابق', N'n'),(N'Currencies',N'Unidad previsional', N'am', N'ያልተለመደ ቅድመ-ዕይታ', N'n'),(N'Currencies',N'Unidad previsional', N'cn', N'Unidad临时', N'n'),
(N'Currencies',N'Som', N'ar', N'سوم', N'n'),(N'Currencies',N'Som', N'am', N'ሶም', N'n'),(N'Currencies',N'Som', N'cn', N'乌兹别克斯坦索姆', N'n'),(N'Currencies',N'Uzbekistan som', N'ar', N'سوم أوزبكستان', N'n'),(N'Currencies',N'Uzbekistan som', N'am', N'ኡዝቤኪስታን som', N'n'),(N'Currencies',N'Uzbekistan som', N'cn', N'乌兹别克斯坦索姆', N'n'),
(N'Currencies',N'Venezuelan bolívar soberano', N'ar', N'بوليفار فنزويلي سوبرانو', N'n'),(N'Currencies',N'Venezuelan bolívar soberano', N'am', N'Eneንዙዌላ ቦሊቫር ሶቤራንኖ', N'n'),(N'Currencies',N'Venezuelan bolívar soberano', N'cn', N'委内瑞拉玻利瓦尔soberano', N'n'),(N'Currencies',N'Venezuelan bolívar soberano', N'ar', N'بوليفار فنزويلي سوبرانو', N'n'),(N'Currencies',N'Venezuelan bolívar soberano', N'am', N'Eneንዙዌላ ቦሊቫር ሶቤራንኖ', N'n'),(N'Currencies',N'Venezuelan bolívar soberano', N'cn', N'委内瑞拉玻利瓦尔soberano', N'n'),
(N'Currencies',N'đồng', N'ar', N'الفيتنامية đồng', N'n'),(N'Currencies',N'đồng', N'am', N'.ንግ', N'n'),(N'Currencies',N'đồng', N'cn', N'越南语', N'n'),(N'Currencies',N'Vietnamese đồng', N'ar', N'الفيتنامية đồng', N'n'),(N'Currencies',N'Vietnamese đồng', N'am', N'የቪዬትናም đồng', N'n'),(N'Currencies',N'Vietnamese đồng', N'cn', N'越南语', N'n'),
(N'Currencies',N'Vatu', N'ar', N'فاتو', N'n'),(N'Currencies',N'Vatu', N'am', N'ቫቱ', N'n'),(N'Currencies',N'Vatu', N'cn', N'瓦努阿图瓦图', N'n'),(N'Currencies',N'Vanuatu vatu', N'ar', N'فانواتو فاتو', N'n'),(N'Currencies',N'Vanuatu vatu', N'am', N'ቫኑዋቱ ቫቱ', N'n'),(N'Currencies',N'Vanuatu vatu', N'cn', N'瓦努阿图瓦图', N'n'),
(N'Currencies',N'Tala', N'ar', N'تالا', N'n'),(N'Currencies',N'Tala', N'am', N'ታል', N'n'),(N'Currencies',N'Tala', N'cn', N'萨摩亚塔拉', N'n'),(N'Currencies',N'Samoan tala', N'ar', N'تالا ساموا', N'n'),(N'Currencies',N'Samoan tala', N'am', N'ሳሞአን Tala', N'n'),(N'Currencies',N'Samoan tala', N'cn', N'萨摩亚塔拉', N'n'),
(N'Currencies',N'CFA franc BEAC', N'ar', N'فرنك وسط أفريفيا', N'n'),(N'Currencies',N'CFA franc BEAC', N'am', N'ሲኤፍ ፍራንክ ቤክ', N'n'),(N'Currencies',N'CFA franc BEAC', N'cn', N'非洲金融共同体法郎', N'n'),(N'Currencies',N'CFA franc BEAC', N'ar', N'فرنك وسط أفريفيا', N'n'),(N'Currencies',N'CFA franc BEAC', N'am', N'ሲኤፍ ፍራንክ ቤክ', N'n'),(N'Currencies',N'CFA franc BEAC', N'cn', N'非洲金融共同体法郎', N'n'),
(N'Currencies',N'Silver (one troy ounce)', N'ar', N'الفضة (أونصة تروي)', N'n'),(N'Currencies',N'Silver (one troy ounce)', N'am', N'ብር (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Silver (one troy ounce)', N'cn', N'银（一金衡盎司）', N'n'),(N'Currencies',N'Silver (one troy ounce)', N'ar', N'الفضة (أونصة تروي)', N'n'),(N'Currencies',N'Silver (one troy ounce)', N'am', N'ብር (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Silver (one troy ounce)', N'cn', N'银（一金衡盎司）', N'n'),
(N'Currencies',N'Gold (one troy ounce)', N'ar', N'الذهب (أونصة تروي)', N'n'),(N'Currencies',N'Gold (one troy ounce)', N'am', N'ወርቅ (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Gold (one troy ounce)', N'cn', N'黄金（一金衡盎司）', N'n'),(N'Currencies',N'Gold (one troy ounce)', N'ar', N'الذهب (أونصة تروي)', N'n'),(N'Currencies',N'Gold (one troy ounce)', N'am', N'ወርቅ (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Gold (one troy ounce)', N'cn', N'黄金（一金衡盎司）', N'n'),
(N'Currencies',N'EURCO', N'ar', N'EURCO', N'n'),(N'Currencies',N'EURCO', N'am', N'ዩሮ', N'n'),(N'Currencies',N'EURCO', N'cn', N'EURCO', N'n'),(N'Currencies',N'European Composite Unit (EURCO) (bond market unit)', N'ar', N'الوحدة الأوروبية المركبة (EURCO) (وحدة سوق السندات)', N'n'),(N'Currencies',N'European Composite Unit (EURCO) (bond market unit)', N'am', N'የአውሮፓውያን አሃድ (ዩሮ)', N'n'),(N'Currencies',N'European Composite Unit (EURCO) (bond market unit)', N'cn', N'欧洲综合股（EURCO）（债券市场股）', N'n'),
(N'Currencies',N'E.M.U.-6', N'ar', N'E.M.U.-6', N'n'),(N'Currencies',N'E.M.U.-6', N'am', N'እ.አ.አ. -6', N'n'),(N'Currencies',N'E.M.U.-6', N'cn', N'E.M.U.-8', N'n'),(N'Currencies',N'European Monetary Unit (E.M.U.-6) (bond market unit)', N'ar', N'وحدة النقد الأوروبية (E.M.U.-6) (وحدة سوق السندات)', N'n'),(N'Currencies',N'European Monetary Unit (E.M.U.-6) (bond market unit)', N'am', N'የአውሮፓ ገንዘብ ክፍል (E.M.U.-6) (የቦንድ ገበያው ክፍል)', N'n'),(N'Currencies',N'European Monetary Unit (E.M.U.-6) (bond market unit)', N'cn', N'欧洲货币单位（E.M.U.-6）（债券市场单位）', N'n'),
(N'Currencies',N'E.U.A.-9', N'ar', N'E.U.A.-9', N'n'),(N'Currencies',N'E.U.A.-9', N'am', N'E.U.A.-9', N'n'),(N'Currencies',N'E.U.A.-9', N'cn', N'E.U.A.-9', N'n'),(N'Currencies',N'European Unit of Account 9 (E.U.A.-9) (bond market unit)', N'ar', N'الوحدة الأوروبية للحساب 9 (الاتحاد الأوروبي - 9) (وحدة سوق السندات)', N'n'),(N'Currencies',N'European Unit of Account 9 (E.U.A.-9) (bond market unit)', N'am', N'የሂሳብ 9 የአውሮፓ ክፍል 9 (E.U.A.-9) (የቦንድ የገበያ ክፍል)', N'n'),(N'Currencies',N'European Unit of Account 9 (E.U.A.-9) (bond market unit)', N'cn', N'欧洲账户单位9（E.U.A.-9）（债券市场单位）', N'n'),
(N'Currencies',N'E.U.A.-17', N'ar', N'E.U.A.-17', N'n'),(N'Currencies',N'E.U.A.-17', N'am', N'E.U.A.-17', N'n'),(N'Currencies',N'E.U.A.-17', N'cn', N'E.U.A.-17', N'n'),(N'Currencies',N'European Unit of Account 17 (E.U.A.-17) (bond market unit)', N'ar', N'الوحدة الأوروبية للحساب 17 (الاتحاد الأوروبي - 17) (وحدة سوق السندات)', N'n'),(N'Currencies',N'European Unit of Account 17 (E.U.A.-17) (bond market unit)', N'am', N'የሂሳብ ቁጥር 17 የአውሮፓ ክፍል 17 (E.U.A.-17) (የቦንድ የገበያ ክፍል)', N'n'),(N'Currencies',N'European Unit of Account 17 (E.U.A.-17) (bond market unit)', N'cn', N'欧洲账户单位17（E.U.A.-17）（债券市场单位）', N'n'),
(N'Currencies',N'East Caribbean dollar', N'ar', N'دولار شرق الكاريبي', N'n'),(N'Currencies',N'East Caribbean dollar', N'am', N'የምስራቅ ካሪቢያን ዶላር', N'n'),(N'Currencies',N'East Caribbean dollar', N'cn', N'东加勒比元', N'n'),(N'Currencies',N'East Caribbean dollar', N'ar', N'دولار شرق الكاريبي', N'n'),(N'Currencies',N'East Caribbean dollar', N'am', N'የምስራቅ ካሪቢያን ዶላር', N'n'),(N'Currencies',N'East Caribbean dollar', N'cn', N'东加勒比元', N'n'),
(N'Currencies',N'Special drawing rights', N'ar', N'حقوق السحب الخاصة', N'n'),(N'Currencies',N'Special drawing rights', N'am', N'ልዩ የስዕል መብቶች', N'n'),(N'Currencies',N'Special drawing rights', N'cn', N'特别提款权', N'n'),(N'Currencies',N'Special drawing rights', N'ar', N'حقوق السحب الخاصة', N'n'),(N'Currencies',N'Special drawing rights', N'am', N'ልዩ የስዕል መብቶች', N'n'),(N'Currencies',N'Special drawing rights', N'cn', N'特别提款权', N'n'),
(N'Currencies',N'CFA franc BCEAO', N'ar', N'فرنك CFA BCEAO', N'n'),(N'Currencies',N'CFA franc BCEAO', N'am', N'ሲኤፍ ፍራንክሳኤአኦ', N'n'),(N'Currencies',N'CFA franc BCEAO', N'cn', N'非洲金融共同体法郎', N'n'),(N'Currencies',N'CFA franc BCEAO', N'ar', N'فرنك CFA BCEAO', N'n'),(N'Currencies',N'CFA franc BCEAO', N'am', N'ሲኤፍ ፍራንክሳኤአኦ', N'n'),(N'Currencies',N'CFA franc BCEAO', N'cn', N'非洲金融共同体法郎', N'n'),
(N'Currencies',N'Palladium (one troy ounce)', N'ar', N'البلاديوم (أوقية واحدة)', N'n'),(N'Currencies',N'Palladium (one troy ounce)', N'am', N'ፓላዲየም (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Palladium (one troy ounce)', N'cn', N'钯（一金衡盎司）', N'n'),(N'Currencies',N'Palladium (one troy ounce)', N'ar', N'البلاديوم (أوقية واحدة)', N'n'),(N'Currencies',N'Palladium (one troy ounce)', N'am', N'ፓላዲየም (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Palladium (one troy ounce)', N'cn', N'钯（一金衡盎司）', N'n'),
(N'Currencies',N'CFP franc (franc Pacifique)', N'ar', N'فرنك سي اف بي (فرنك باسيفيك)', N'n'),(N'Currencies',N'CFP franc (franc Pacifique)', N'am', N'CFP ፍራንክ (ፍራንክ ifiፋፋque)', N'n'),(N'Currencies',N'CFP franc (franc Pacifique)', N'cn', N'CFP法郎（franc Pacifique）', N'n'),(N'Currencies',N'CFP franc (franc Pacifique)', N'ar', N'فرنك سي اف بي (فرنك باسيفيك)', N'n'),(N'Currencies',N'CFP franc (franc Pacifique)', N'am', N'CFP ፍራንክ (ፍራንክ ifiፋፋque)', N'n'),(N'Currencies',N'CFP franc (franc Pacifique)', N'cn', N'CFP法郎（franc Pacifique）', N'n'),
(N'Currencies',N'Platinum (one troy ounce)', N'ar', N'البلاتين (أوقية واحدة)', N'n'),(N'Currencies',N'Platinum (one troy ounce)', N'am', N'ፕላቲኒየም (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Platinum (one troy ounce)', N'cn', N'铂金（一金衡盎司）', N'n'),(N'Currencies',N'Platinum (one troy ounce)', N'ar', N'البلاتين (أوقية واحدة)', N'n'),(N'Currencies',N'Platinum (one troy ounce)', N'am', N'ፕላቲኒየም (አንድ ትሪ አውንስ)', N'n'),(N'Currencies',N'Platinum (one troy ounce)', N'cn', N'铂金（一金衡盎司）', N'n'),
(N'Currencies',N'SUCRE', N'ar', N'SUCRE', N'n'),(N'Currencies',N'SUCRE', N'am', N'ስኬት', N'n'),(N'Currencies',N'SUCRE', N'cn', N'苏克雷', N'n'),(N'Currencies',N'SUCRE', N'ar', N'SUCRE', N'n'),(N'Currencies',N'SUCRE', N'am', N'ስኬት', N'n'),(N'Currencies',N'SUCRE', N'cn', N'苏克雷', N'n'),
(N'Currencies',N'Code reserved for testing', N'ar', N'الرمز المخصص للاختبار', N'n'),(N'Currencies',N'Code reserved for testing', N'am', N'ኮድ ለሙከራ ተይ resል', N'n'),(N'Currencies',N'Code reserved for testing', N'cn', N'保留用于测试的代码', N'n'),(N'Currencies',N'Code reserved for testing', N'ar', N'الرمز المخصص للاختبار', N'n'),(N'Currencies',N'Code reserved for testing', N'am', N'ኮድ ለሙከራ ተይ resል', N'n'),(N'Currencies',N'Code reserved for testing', N'cn', N'保留用于测试的代码', N'n'),
(N'Currencies',N'ADB Unit of Account', N'ar', N'وحدة حساب ADB', N'n'),(N'Currencies',N'ADB Unit of Account', N'am', N'የሂሳብ ADB ክፍል', N'n'),(N'Currencies',N'ADB Unit of Account', N'cn', N'亚行账户单位', N'n'),(N'Currencies',N'ADB Unit of Account', N'ar', N'وحدة حساب ADB', N'n'),(N'Currencies',N'ADB Unit of Account', N'am', N'የሂሳብ ADB ክፍል', N'n'),(N'Currencies',N'ADB Unit of Account', N'cn', N'亚行账户单位', N'n'),
(N'Currencies',N'No currency', N'ar', N'لا عملة', N'n'),(N'Currencies',N'No currency', N'am', N'ምንም ገንዘብ የለም', N'n'),(N'Currencies',N'No currency', N'cn', N'没有货币', N'n'),(N'Currencies',N'No currency', N'ar', N'لا عملة', N'n'),(N'Currencies',N'No currency', N'am', N'ምንም ገንዘብ የለም', N'n'),(N'Currencies',N'No currency', N'cn', N'没有货币', N'n'),
(N'Currencies',N'YE Rial', N'ar', N'ريال ي.', N'n'),(N'Currencies',N'YE Rial', N'am', N'YE YE ኪራይ', N'n'),(N'Currencies',N'YE Rial', N'cn', N'也门里亚尔', N'n'),(N'Currencies',N'Yemeni rial', N'ar', N'الريال اليمني', N'n'),(N'Currencies',N'Yemeni rial', N'am', N'የየመን ሪል', N'n'),(N'Currencies',N'Yemeni rial', N'cn', N'也门里亚尔', N'n'),
(N'Currencies',N'Rand', N'ar', N'راند', N'n'),(N'Currencies',N'Rand', N'am', N'ራንድ', N'n'),(N'Currencies',N'Rand', N'cn', N'南非兰特', N'n'),(N'Currencies',N'South African rand', N'ar', N'راند جنوب أفريقيا', N'n'),(N'Currencies',N'South African rand', N'am', N'የደቡብ አፍሪካው ሮድ', N'n'),(N'Currencies',N'South African rand', N'cn', N'南非兰特', N'n'),
(N'Currencies',N'Kwacha', N'ar', N'كواشا', N'n'),(N'Currencies',N'Kwacha', N'am', N'Kwacha', N'n'),(N'Currencies',N'Kwacha', N'cn', N'赞比亚克瓦查', N'n'),(N'Currencies',N'Zambian kwacha', N'ar', N'كواشا زامبيا', N'n'),(N'Currencies',N'Zambian kwacha', N'am', N'የዛምቢያ kwacha', N'n'),(N'Currencies',N'Zambian kwacha', N'cn', N'赞比亚克瓦查', N'n'),
(N'Currencies',N'ZW Dollar', N'ar', N'دولار ز.', N'n'),(N'Currencies',N'ZW Dollar', N'am', N'ZW ዶላር', N'n'),(N'Currencies',N'ZW Dollar', N'cn', N'津巴布韦元', N'n'),(N'Currencies',N'Zimbabwean dollar', N'ar', N'الدولار الزيمبابوي', N'n'),(N'Currencies',N'Zimbabwean dollar', N'am', N'ዚምባብዌ ዶላር', N'n'),(N'Currencies',N'Zimbabwean dollar', N'cn', N'津巴布韦元', N'n');

WITH NonDuplicateTranslationIds([Id]) AS
(
	SELECT MIN([Id])
	FROM @Translations
	GROUP BY [TableName], [SourceEnglishWord], [DestinationCultureId], [Form]
)
INSERT INTO dbo.Translations([TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form])
SELECT [TableName],[SourceEnglishWord],[DestinationCultureId],[DestinationWord],[Form]
FROM @Translations
WHERE [Id] IN (SELECT [Id] FROM NonDuplicateTranslationIds)
------------------------------------------------------------------------------------------------------------------------
-- Users
UPDATE dbo.Users
SET
	[Name]  = dbo.fn_TranslateFromEnglish(N'Users', [Name], @PrimaryLanguageId, 'n'),
	[Name2] = dbo.fn_TranslateFromEnglish(N'Users', [Name], @SecondaryLanguageId, 'n'),
	[Name3] = dbo.fn_TranslateFromEnglish(N'Users', [Name], @TernaryLanguageId, 'n')
WHERE [Name] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'Users' AND [Form] = N'n')
-- Roles
UPDATE dbo.Roles
SET
	[Name]  = dbo.fn_TranslateFromEnglish(N'Roles', [Name], @PrimaryLanguageId, 'n'),
	[Name2] = dbo.fn_TranslateFromEnglish(N'Roles', [Name], @SecondaryLanguageId, 'n'),
	[Name3] = dbo.fn_TranslateFromEnglish(N'Roles', [Name], @TernaryLanguageId, 'n')
WHERE [Name] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'Roles' AND [Form] = N'n')
-- Entry Types
-- Account Types
-- IfrsConcepts
-- IfrsDisclosures

-- Report Definitions
-- Lookup Definitions
UPDATE dbo.LookupDefinitions
SET
	[TitleSingular]  = dbo.fn_TranslateFromEnglish(N'LookupDefinitions', [TitleSingular], @PrimaryLanguageId, 's'),
	[TitleSingular2] = dbo.fn_TranslateFromEnglish(N'LookupDefinitions', [TitleSingular], @SecondaryLanguageId, 's'),
	[TitleSingular3] = dbo.fn_TranslateFromEnglish(N'LookupDefinitions', [TitleSingular], @TernaryLanguageId, 's'),
	[TitlePlural]  = dbo.fn_TranslateFromEnglish(N'LookupDefinitions', [TitlePlural], @PrimaryLanguageId, 'p'),
	[TitlePlural2] = dbo.fn_TranslateFromEnglish(N'LookupDefinitions', [TitlePlural], @SecondaryLanguageId, 'p'),
	[TitlePlural3] = dbo.fn_TranslateFromEnglish(N'LookupDefinitions', [TitlePlural], @TernaryLanguageId, 'p')
WHERE [TitleSingular] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'LookupDefinitions' AND [Form] = N's')
AND [TitlePlural] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'LookupDefinitions' AND [Form] = N'p')
-- Resource Definitions
UPDATE dbo.ResourceDefinitions
SET
	[TitleSingular]  = dbo.fn_TranslateFromEnglish(N'ResourceDefinitions', [TitleSingular], @PrimaryLanguageId, 's'),
	[TitleSingular2] = dbo.fn_TranslateFromEnglish(N'ResourceDefinitions', [TitleSingular], @SecondaryLanguageId, 's'),
	[TitleSingular3] = dbo.fn_TranslateFromEnglish(N'ResourceDefinitions', [TitleSingular], @TernaryLanguageId, 's'),
	[TitlePlural]  = dbo.fn_TranslateFromEnglish(N'ResourceDefinitions', [TitlePlural], @PrimaryLanguageId, 'p'),
	[TitlePlural2] = dbo.fn_TranslateFromEnglish(N'ResourceDefinitions', [TitlePlural], @SecondaryLanguageId, 'p'),
	[TitlePlural3] = dbo.fn_TranslateFromEnglish(N'ResourceDefinitions', [TitlePlural], @TernaryLanguageId, 'p')
WHERE [TitleSingular] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'ResourceDefinitions' AND [Form] = N's')
AND [TitlePlural] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'ResourceDefinitions' AND [Form] = N'p');
-- Contract Definitions
UPDATE dbo.ContractDefinitions
SET
	[TitleSingular]  = dbo.fn_TranslateFromEnglish(N'ContractDefinitions', [TitleSingular], @PrimaryLanguageId, 's'),
	[TitleSingular2] = dbo.fn_TranslateFromEnglish(N'ContractDefinitions', [TitleSingular], @SecondaryLanguageId, 's'),
	[TitleSingular3] = dbo.fn_TranslateFromEnglish(N'ContractDefinitions', [TitleSingular], @TernaryLanguageId, 's'),
	[TitlePlural]  = dbo.fn_TranslateFromEnglish(N'ContractDefinitions', [TitlePlural], @PrimaryLanguageId, 'p'),
	[TitlePlural2] = dbo.fn_TranslateFromEnglish(N'ContractDefinitions', [TitlePlural], @SecondaryLanguageId, 'p'),
	[TitlePlural3] = dbo.fn_TranslateFromEnglish(N'ContractDefinitions', [TitlePlural], @TernaryLanguageId, 'p')
WHERE [TitleSingular] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'ContractDefinitions' AND [Form] = N's')
AND [TitlePlural] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'ContractDefinitions' AND [Form] = N'p');
-- Currencies
UPDATE dbo.Currencies
SET
	[Name]  = dbo.fn_TranslateFromEnglish(N'Currencies', [Name], @PrimaryLanguageId, 'n'),
	[Name2] = dbo.fn_TranslateFromEnglish(N'Currencies', [Name], @SecondaryLanguageId, 'n'),
	[Name3] = dbo.fn_TranslateFromEnglish(N'Currencies', [Name], @TernaryLanguageId, 'n'),
	[Description]  = dbo.fn_TranslateFromEnglish(N'Currencies', [Description], @PrimaryLanguageId, 'n'),
	[Description2] = dbo.fn_TranslateFromEnglish(N'Currencies', [Description], @SecondaryLanguageId, 'n'),
	[Description3] = dbo.fn_TranslateFromEnglish(N'Currencies', [Description], @TernaryLanguageId, 'n')
WHERE [Name] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'Currencies' AND [Form] = N'n')
AND [Description] IN (SELECT [SourceEnglishWord] FROM dbo.Translations WHERE [TableName] = N'Currencies' AND [Form] = N'n')
-- Line Definitions
-- Document Definitions