-- Activate needed resource definitions
DELETE FROM @ResourceDefinitionIds;
INSERT INTO @ResourceDefinitionIds([Id]) VALUES
(@LandMemberRD),
(@BuildingsMemberRD),
(@MachineryMemberRD),
(@MotorVehiclesMemberRD),
--(@FixturesAndFittingsMemberRD),
(@OfficeEquipmentMemberRD),
(@ComputerEquipmentMemberRD),
--(@CommunicationAndNetworkEquipmentMemberRD),
--(@NetworkInfrastructureMemberRD),
--(@BearerPlantsMemberRD),
--(@TangibleExplorationAndEvaluationAssetsMemberRD),
--(@MiningAssetsMemberRD),
--(@OilAndGasAssetsMemberRD),
(@PowerGeneratingAssetsMemberRD),
(@LeaseholdImprovementsMemberRD),
(@ConstructionInProgressMemberRD),
(@OwneroccupiedPropertyMeasuredUsingInvestmentPropertyFairValueModelMemberRD),
(@OtherPropertyPlantAndEquipmentMemberRD),
(@InvestmentPropertyCompletedMemberRD),
--(@InvestmentPropertyUnderConstructionOrDevelopmentMemberRD),
--(@MerchandiseRD),
--(@CurrentFoodAndBeverageRD),
--(@CurrentAgriculturalProduceRD),
--(@FinishedGoodsRD),
--(@PropertyIntendedForSaleInOrdinaryCourseOfBusinessRD),
(@WorkInProgressRD),
--(@RawMaterialsRD),
(@ProductionSuppliesRD),
(@CurrentPackagingAndStorageMaterialsRD),
(@SparePartsRD),
--(@CurrentFuelRD),
(@OtherInventoriesRD),
(@TradeMedicineRD),
(@TradeConstructionMaterialRD),
(@TradeSparePartRD),
(@FinishedGrainRD),
(@ByproductGrainRD),
(@FinishedVehicleRD),
(@FinishedOilRD),
(@ByproductOilRD),
(@RawGrainRD),
(@RawVehicleRD),
(@RevenueServiceRD),
(@EmployeeBenefitRD),
--(@CheckReceivedRD),
(@AccrualsRD),
(@AccruedIncomeRD),
(@EmployeeLoanRD),
(@CurrentBilledButNotIssuedRD),
(@DeferredIncomeRD),
(@PrepaymentsRD),
(@ReceivablesFromRentalOfPropertiesRD),
--(@ReceivablesFromSaleOfPropertiesRD),
--(@RefundsProvisionRD),
(@RentDeferredIncomeRD),
--(@RestructuringProvisionRD),
(@RetentionPayableRD),
(@TradePayableRD),
(@TradeReceivableRD),
(@WarrantyProvisionRD);

EXEC [dal].[ResourceDefinitions__UpdateState]
	@Ids = @ResourceDefinitionIds,
	@State = N'Visible'

DELETE FROM LineDefinitionEntryResourceDefinitions
WHERE ResourceDefinitionId IN (SELECT [Id] FROM dbo.ResourceDefinitions WHERE [State] <> N'Visible')