CREATE TABLE [dbo].[GlobalUsers]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [ExternalId] NVARCHAR(450) NULL, 
    [Email] NVARCHAR(255) NOT NULL,
	[CreatedAt]		DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[CreatedById]	INT	NOT NULL DEFAULT CONVERT(INT, SESSION_CONTEXT(N'UserId')),
	[ModifiedAt]	DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(), 
	[ModifiedById]	INT	NOT NULL DEFAULT CONVERT(INT, SESSION_CONTEXT(N'UserId')), 
    CONSTRAINT [FK_GlobalUsers_GlobalUsers_CreatedById] FOREIGN KEY ([CreatedById]) REFERENCES [GlobalUsers]([Id]),
    CONSTRAINT [FK_GlobalUsers_GlobalUsers_ModifiedById] FOREIGN KEY ([ModifiedById]) REFERENCES [GlobalUsers]([Id])
)
