// <auto-generated />
using BSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BSharp.Data.Migrations.Localization
{
    [DbContext(typeof(LocalizationContext))]
    [Migration("20181125194226_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BSharp.Data.Model.Localization.CoreTranslation", b =>
                {
                    b.Property<string>("Tier")
                        .HasMaxLength(50);

                    b.Property<string>("Culture")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(450);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.HasKey("Tier", "Culture", "Name");

                    b.ToTable("CoreTranslations");

                    b.HasData(
                        new { Tier = "C#", Culture = "en", Name = "CouldNotRetrieveTheRecordWithId{0}", Value = "Sorry, could not retrieve the record with Id {0}" },
                        new { Tier = "C#", Culture = "ar", Name = "CouldNotRetrieveTheRecordWithId{0}", Value = "المعذرة لم يتم العثور على البيان ذي المفتاح {0}" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
