CREATE TABLE [dbo].[Views] (
	[Id]			NVARCHAR (255)		CONSTRAINT [FK_Views] PRIMARY KEY,
	[IsActive]		BIT					NOT NULL DEFAULT 1,
	[CreatedAt]		DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[CreatedById]	INT					NOT NULL DEFAULT CONVERT(INT, SESSION_CONTEXT(N'UserId')) CONSTRAINT [FK_Views__CreatedById] REFERENCES [dbo].[Users] ([Id]),
	[ModifiedAt]	DATETIMEOFFSET(7)	NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	[ModifiedById]	INT					NOT NULL DEFAULT CONVERT(INT, SESSION_CONTEXT(N'UserId')) CONSTRAINT [FK_Views__ModifiedById] REFERENCES [dbo].[Users] ([Id])
);
GO