CREATE TABLE [dbo].[AccountDefinitions] (
	[Id]									NVARCHAR (50) PRIMARY KEY,
	[Description]							NVARCHAR (255),
	[Description2]							NVARCHAR (255),
	[Description3]							NVARCHAR (255),
	[TitleSingular]							NVARCHAR (255) NOT NULL,
	[TitleSingular2]						NVARCHAR (255),
	[TitleSingular3]						NVARCHAR (255),
	[TitlePlural]							NVARCHAR (255) NOT NULL,
	[TitlePlural2]							NVARCHAR (255),
	[TitlePlural3]							NVARCHAR (255),
	-- TODO: move to table AccountTypes?
	-- If defined and leaf, then any entry using an account with the said definition would have this IfrsEntryClassification
	-- If defined and parent, then in the entry IfrsEntryClassification will be limited to the leaf children
	-- If null, then IfrsEntryClassification field will be hidden
	[IfrsEntryClassificationId]				NVARCHAR (255),
	[PartyReferenceVisibility]				NVARCHAR (50) DEFAULT N'None' CHECK ([PartyReferenceVisibility] IN (N'None', N'RequiredInAccounts', N'OptionalInAccounts')),
	[PartyReferenceLabel]					NVARCHAR (50),
	-- When optional, it is used only for detailed reports such as account statement.
	-- When required, it is also used for summary report and to define the account statement parameters (will disappear from report)
	-- If required in Account, the field will be read/only in the statement parameters header.
	-- If required in Account Entries, the field will be editable in the statement parameters header
	[ResponsibleVisibility]					NVARCHAR (50) DEFAULT N'None' CHECK ([ResponsibleVisibility] IN (N'None', N'RequiredInAccounts', N'RequiredInEntries', N'OptionalInEntries')),
	[ResponsibleLabel]						NVARCHAR (50),
	[ResponsibleLabel2]						NVARCHAR (50),
	[ResponsibleLabel3]						NVARCHAR (50),
	[ResponsibleRelationDefinitionList]		NVARCHAR (255),
	[CustodianVisibility]					NVARCHAR (50) DEFAULT N'None' CHECK ([CustodianVisibility] IN (N'None', N'RequiredInAccounts', N'RequiredInEntries', N'OptionalInEntries')),
	[CustodianLabel]						NVARCHAR (50),
	[CustodianLabel2]						NVARCHAR (50),
	[CustodianLabel3]						NVARCHAR (50),
	[CustodianRelationDefinitionList]		NVARCHAR (255),
	[ResourceVisibility]					NVARCHAR (50) DEFAULT N'None' CHECK ([ResourceVisibility] IN (N'None', N'RequiredInAccounts', N'RequiredInEntries', N'OptionalInEntries')),
	[ResourceLabel]							NVARCHAR (50),
	[ResourceLabel2]						NVARCHAR (50),
	[ResourceLabel3]						NVARCHAR (50),
	[ResourceDefinitionList]				NVARCHAR (255),
	[LocationVisibility]					NVARCHAR (50) DEFAULT N'None' CHECK ([LocationVisibility] IN (N'None', N'RequiredInAccounts', N'RequiredInEntries', N'OptionalInEntries')),
	[LocationLabel]							NVARCHAR (50),
	[LocationLabel2]						NVARCHAR (50),
	[LocationLabel3]						NVARCHAR (50),
	[LocationDefinitionList]				NVARCHAR (255),
	[DueDateVisibility]						NVARCHAR (50) DEFAULT N'None' CHECK ([DueDateVisibility] IN (N'None', N'RequiredInEntries', N'OptionalInEntries')),
	[DueDateLabel]							NVARCHAR (50),
	[DueDateLabel2]							NVARCHAR (50),
	[DueDateLabel3]							NVARCHAR (50),
	[RelatedAgentVisibility]				NVARCHAR (50) DEFAULT N'None' CHECK ([RelatedAgentVisibility] IN (N'None', N'RequiredInEntries', N'OptionalInEntries')),
	[RelatedAgentLabel]						NVARCHAR (50),
	[RelatedAgentLabel2]					NVARCHAR (50),
	[RelatedAgentLabel3]					NVARCHAR (50),
	[RelatedAgentRelationDefinitionList]	NVARCHAR (255),
	[RelatedMonetaryAmountVisibility]		NVARCHAR (50) DEFAULT N'None' CHECK ([RelatedMonetaryAmountVisibility] IN (N'None', N'RequiredInEntries', N'OptionalInEntries')),
	[RelatedMonetaryAmountLabel]			NVARCHAR (50),
	[RelatedMonetaryAmountLabel2]			NVARCHAR (50),
	[RelatedMonetaryAmountLabel3]			NVARCHAR (50),
	[ExternalReferenceVisibility]			NVARCHAR (50) DEFAULT N'None' CHECK ([ExternalReferenceVisibility] IN (N'None', N'RequiredInEntries', N'OptionalInEntries')),
	[ExternalReferenceLabel]				NVARCHAR (50),
	[ExternalReferenceLabel2]				NVARCHAR (50),
	[ExternalReferenceLabel3]				NVARCHAR (50),
	[AdditionalReferenceVisibility]			NVARCHAR (50) DEFAULT N'None' CHECK ([AdditionalReferenceVisibility] IN (N'None', N'RequiredInEntries', N'OptionalInEntries')),
	[AdditionalReferenceLabel]				NVARCHAR (50),
	[AdditionalReferenceLabel2]				NVARCHAR (50),
	[AdditionalReferenceLabel3]				NVARCHAR (50)
);